// web/src/frontends/classic/features/home/HomeSpend.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { RouterLink } from 'vue-router'

import type { HomeStatisticsDto } from '@/app/resources/home'
import { monitorLocation } from '@/app/route-locations'
import DataTable from '@/components/ui/DataTable.vue'
import SkeletonBlock from '@/components/ui/SkeletonBlock.vue'

import HomeSectionHeading from './HomeSectionHeading.vue'
import { formatEstimatedCost, formatInteger, formatTokens } from '@shared/lib/format'

const props = withDefaults(
  defineProps<{
    snapshot: HomeStatisticsDto | null
    loading?: boolean
  }>(),
  { loading: false },
)

const { locale, t } = useI18n()

const rows = computed(() => props.snapshot?.rankings.models.slice(0, 5) ?? [])
const totalCost = computed(() =>
  props.snapshot === null
    ? '—'
    : formatEstimatedCost(props.snapshot.summary.estimated_cost_nano_usd, locale.value),
)

function modelName(model: string): string {
  return model || t('home.ledger.spend.unknownModel')
}

function modelUsageLocation(model: string) {
  return monitorLocation(
    model === ''
      ? { tab: 'usage', range: '30d' }
      : { tab: 'usage', range: '30d', upstream_model: model },
  )
}

function tokenCellAttributes(totalTokens: number): { title: string; 'aria-label': string } {
  const exactTokenCount = t('home.ledger.tokens', {
    count: formatInteger(totalTokens, locale.value),
  })
  return { title: exactTokenCount, 'aria-label': exactTokenCount }
}
</script>

<template>
  <section class="home-spend" aria-labelledby="home-spend-title">
    <HomeSectionHeading id="home-spend-title" :title="t('home.ledger.spend.title')">
      <template #actions>
        <RouterLink class="home-spend__link" :to="monitorLocation({ tab: 'usage', range: '30d' })">
          {{ t('home.ledger.spend.viewDetail') }}
        </RouterLink>
      </template>
    </HomeSectionHeading>

    <SkeletonBlock
      v-if="loading"
      class="home-spend__value-skeleton"
      width="140px"
      height="2.25rem"
    />
    <p v-else class="home-spend__value">{{ totalCost }}</p>

    <DataTable
      appearance="editorial"
      column-collapse="narrow"
      dense
      :aria-busy="loading ? 'true' : undefined"
      :caption="t('home.ledger.spend.caption')"
      :scroll-hint="t('home.ledger.spend.scrollHint')"
    >
      <thead>
        <tr>
          <th scope="col">{{ t('home.ledger.spend.columns.model') }}</th>
          <th scope="col" class="home-spend__number">
            {{ t('home.ledger.spend.columns.requests') }}
          </th>
          <th scope="col" class="home-spend__number" data-column-priority="low">
            {{ t('home.ledger.spend.columns.tokens') }}
          </th>
          <th scope="col" class="home-spend__number">
            {{ t('home.ledger.spend.columns.cost') }}
          </th>
        </tr>
      </thead>
      <tbody>
        <template v-if="loading">
          <tr v-for="row in 5" :key="`loading-${row}`">
            <td v-for="column in 4" :key="column">
              <SkeletonBlock
                height="0.72rem"
                :width="column === 1 ? '72%' : column === 2 ? '58%' : '44%'"
              />
            </td>
          </tr>
        </template>
        <tr v-else-if="rows.length === 0">
          <td class="home-spend__empty" colspan="4">{{ t('home.ledger.spend.empty') }}</td>
        </tr>
        <tr v-for="row in rows" v-else :key="row.model">
          <td class="home-spend__model">
            <RouterLink
              class="home-spend__model-link"
              :to="modelUsageLocation(row.model)"
              :aria-label="t('home.ledger.spend.viewModel', { model: modelName(row.model) })"
            >
              {{ modelName(row.model) }}
            </RouterLink>
          </td>
          <td class="home-spend__number home-spend__mono">
            {{ formatInteger(row.request_count, locale) }}
          </td>
          <td
            class="home-spend__number home-spend__mono"
            data-column-priority="low"
            v-bind="tokenCellAttributes(row.total_tokens)"
          >
            {{ formatTokens(row.total_tokens, locale) }}
          </td>
          <td class="home-spend__number home-spend__mono">
            {{ formatEstimatedCost(row.estimated_cost_nano_usd, locale) }}
          </td>
        </tr>
      </tbody>
    </DataTable>
  </section>
</template>

<style scoped>
.home-spend {
  margin-top: 36px;
  border-top: 1px solid var(--color-border-subtle);
  padding: 20px 0 4px;
}

.home-spend__link {
  color: var(--color-action);
  font-size: var(--text-meta);
  font-weight: 600;
  white-space: nowrap;
}

.home-spend__link:hover {
  text-decoration: underline;
}

.home-spend__value {
  margin: 10px 0 16px;
  font-family: var(--font-mono);
  font-size: var(--stat-value);
  font-weight: 550;
  line-height: 1.05;
  letter-spacing: -0.03em;
  font-variant-numeric: tabular-nums;
}

.home-spend__value-skeleton {
  margin-bottom: 18px;
}

.home-spend__number {
  text-align: right !important;
}

.home-spend__mono {
  font-family: var(--font-mono);
  font-variant-numeric: tabular-nums;
}

.home-spend__model {
  color: var(--color-text-muted);
  font-family: var(--font-mono);
  font-size: var(--text-sm);
}

.home-spend__model-link {
  color: inherit;
}

.home-spend__model-link:hover {
  color: var(--color-action);
  text-decoration: underline;
}

.home-spend__empty {
  color: var(--color-text-faint);
  font-size: var(--text-sm);
  padding-block: var(--space-3) !important;
}
</style>

// web/src/frontends/astryx/features/home/HomeSpend.tsx
import * as stylex from '@stylexjs/stylex'
import { Skeleton } from '@astryxdesign/core'
import { useIntl } from 'react-intl'

import type { HomeStatisticsDto } from '@shared/control/resources/home'
import { pagePath } from '@shared/routing/page-routes'
import { formatEstimatedCost, formatInteger, formatTokens } from '@shared/lib/format'

import { useT } from '../../app/i18n'
import { RouteLink } from '../../app/route-link'
import { HomeSectionHeading } from './home-chrome'

const NARROW = '@media (max-width: 560px)'

const styles = stylex.create({
  section: {
    marginTop: 36,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingTop: 20,
    paddingBottom: 4,
  },
  link: {
    color: 'var(--color-action)',
    fontSize: 'var(--text-meta)',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    textDecoration: { default: 'none', ':hover': 'underline' },
  },
  value: {
    margin: '10px 0 16px',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--stat-value)',
    fontWeight: 550,
    lineHeight: 1.05,
    letterSpacing: '-0.03em',
    fontVariantNumeric: 'tabular-nums',
  },
  valueSkeleton: {
    marginTop: 10,
    marginBottom: 18,
  },
  tableWrap: {
    overflowX: 'auto',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 'var(--text-sm)',
  },
  caption: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    whiteSpace: 'nowrap',
  },
  headCell: {
    paddingTop: 7,
    paddingBottom: 7,
    paddingInline: 0,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
    fontWeight: 600,
    textAlign: 'left',
    whiteSpace: 'nowrap',
  },
  headCellNumber: {
    textAlign: 'right',
  },
  cell: {
    paddingTop: 7,
    paddingBottom: 7,
    paddingInline: 0,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    color: 'var(--color-text)',
    verticalAlign: 'middle',
  },
  number: {
    fontFamily: 'var(--font-mono)',
    fontVariantNumeric: 'tabular-nums',
    textAlign: 'right',
    whiteSpace: 'nowrap',
  },
  model: {
    color: 'var(--color-text-muted)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)',
    maxWidth: {
      default: 'none',
      [NARROW]: '38vw',
    },
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  modelLink: {
    color: { default: 'inherit', ':hover': 'var(--color-action)' },
    textDecoration: { default: 'none', ':hover': 'underline' },
  },
  empty: {
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-sm)',
    paddingBlock: 'var(--space-3)',
  },
  lowPriority: {
    display: {
      default: 'table-cell',
      [NARROW]: 'none',
    },
  },
})

function modelUsageHref(model: string): string {
  const base = `${pagePath('monitor')}?tab=usage&range=30d`
  return model === '' ? base : `${base}&upstream_model=${encodeURIComponent(model)}`
}

const skeletonWidths = ['72%', '58%', '44%', '36%'] as const
const skeletonRows = [1, 2, 3, 4, 5] as const

export function HomeSpend({
  snapshot,
  loading = false,
}: {
  snapshot: HomeStatisticsDto | null
  loading?: boolean
}) {
  const intl = useIntl()
  const t = useT()

  const rows = snapshot?.rankings.models.slice(0, 5) ?? []
  const totalCost =
    snapshot === null
      ? '—'
      : formatEstimatedCost(snapshot.summary.estimated_cost_nano_usd, intl.locale)

  const modelName = (model: string): string => model || t('home.ledger.spend.unknownModel')

  return (
    <section {...stylex.props(styles.section)} aria-labelledby="home-spend-title">
      <HomeSectionHeading
        id="home-spend-title"
        title={t('home.ledger.spend.title')}
        actions={
          <RouteLink
            to={`${pagePath('monitor')}?tab=usage&range=30d`}
            {...stylex.props(styles.link)}
          >
            {t('home.ledger.spend.viewDetail')}
          </RouteLink>
        }
      />

      {loading ? (
        <div {...stylex.props(styles.valueSkeleton)}>
          <Skeleton width={140} height={36} />
        </div>
      ) : (
        <p {...stylex.props(styles.value)}>{totalCost}</p>
      )}

      <div {...stylex.props(styles.tableWrap)}>
        <table {...stylex.props(styles.table)} aria-busy={loading ? 'true' : undefined}>
          <caption {...stylex.props(styles.caption)}>{t('home.ledger.spend.caption')}</caption>
          <thead>
            <tr>
              <th scope="col" {...stylex.props(styles.headCell)}>
                {t('home.ledger.spend.columns.model')}
              </th>
              <th scope="col" {...stylex.props(styles.headCell, styles.headCellNumber)}>
                {t('home.ledger.spend.columns.requests')}
              </th>
              <th
                scope="col"
                {...stylex.props(styles.headCell, styles.headCellNumber, styles.lowPriority)}
              >
                {t('home.ledger.spend.columns.tokens')}
              </th>
              <th scope="col" {...stylex.props(styles.headCell, styles.headCellNumber)}>
                {t('home.ledger.spend.columns.cost')}
              </th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              skeletonRows.map((row) => (
                <tr key={row}>
                  {skeletonWidths.map((width, column) => (
                    <td key={column} {...stylex.props(styles.cell)}>
                      <Skeleton height={12} width={width} />
                    </td>
                  ))}
                </tr>
              ))
            ) : rows.length === 0 ? (
              <tr>
                <td colSpan={4} {...stylex.props(styles.cell, styles.empty)}>
                  {t('home.ledger.spend.empty')}
                </td>
              </tr>
            ) : (
              rows.map((row) => {
                const exactTokens = t('home.ledger.tokens', {
                  count: formatInteger(row.total_tokens, intl.locale),
                })
                return (
                  <tr key={row.model}>
                    <td {...stylex.props(styles.cell, styles.model)}>
                      <RouteLink
                        to={modelUsageHref(row.model)}
                        aria-label={t('home.ledger.spend.viewModel', {
                          model: modelName(row.model),
                        })}
                        {...stylex.props(styles.modelLink)}
                      >
                        {modelName(row.model)}
                      </RouteLink>
                    </td>
                    <td {...stylex.props(styles.cell, styles.number)}>
                      {formatInteger(row.request_count, intl.locale)}
                    </td>
                    <td
                      {...stylex.props(styles.cell, styles.number, styles.lowPriority)}
                      title={exactTokens}
                      aria-label={exactTokens}
                    >
                      {formatTokens(row.total_tokens, intl.locale)}
                    </td>
                    <td {...stylex.props(styles.cell, styles.number)}>
                      {formatEstimatedCost(row.estimated_cost_nano_usd, intl.locale)}
                    </td>
                  </tr>
                )
              })
            )}
          </tbody>
        </table>
      </div>
    </section>
  )
}
