// web/src/frontends/astryx/features/monitor/LogProtocolConversion.tsx
import * as stylex from '@stylexjs/stylex'
import { Tooltip } from '@astryxdesign/core'
import { ArrowRightLeft } from 'lucide-react'

import type {
  RequestLogRouteMode,
  RequestLogUpstreamProtocol,
} from '@shared/control/resources/request-logs'
import type { AccessProtocol } from '@shared/control/types'

import { useT } from '../../app/i18n'

const styles = stylex.create({
  marker: {
    display: 'inline-flex',
    width: 20,
    height: 20,
    flex: '0 0 auto',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 'var(--radius-tag)',
    color: 'var(--color-warning)',
    cursor: 'help',
    backgroundColor: {
      ':hover': 'color-mix(in srgb, var(--color-warning) 10%, transparent)',
    },
    outlineWidth: { ':focus-visible': 2 },
    outlineStyle: { ':focus-visible': 'solid' },
    outlineColor: { ':focus-visible': 'var(--color-focus)' },
    outlineOffset: { ':focus-visible': 1 },
  },
})

/**
 * Protocol-conversion marker for a request log — classic
 * LogProtocolConversion.vue. Only renders when the request was routed through
 * a protocol conversion (`mode === 'converted'`).
 */
export function LogProtocolConversion({
  mode,
  clientProtocol,
  upstreamProtocol,
}: {
  mode: RequestLogRouteMode | null
  clientProtocol: AccessProtocol
  upstreamProtocol: RequestLogUpstreamProtocol | null
}) {
  const t = useT()
  if (mode !== 'converted') return null

  const clientProtocolLabel: string = clientProtocol
  const upstreamProtocolLabel =
    upstreamProtocol === null ? t('monitor.logs.protocolConversion.notRecorded') : upstreamProtocol
  const tooltip =
    upstreamProtocol === null
      ? t('monitor.logs.protocolConversion.tooltipNotRecorded', {
          client: clientProtocolLabel,
        })
      : t('monitor.logs.protocolConversion.tooltip', {
          client: clientProtocolLabel,
          upstream: upstreamProtocolLabel,
        })
  const label = t('monitor.logs.protocolConversion.label', {
    client: clientProtocolLabel,
    upstream: upstreamProtocolLabel,
  })

  return (
    <Tooltip content={tooltip}>
      <span {...stylex.props(styles.marker)} tabIndex={0} aria-label={label}>
        <ArrowRightLeft size={14} strokeWidth={1.8} aria-hidden="true" />
      </span>
    </Tooltip>
  )
}

// web/src/frontends/classic/features/monitor/LogProtocolConversion.vue
<script setup lang="ts">
import { ArrowRightLeft } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { AccessProtocol } from '@shared/control/types'
import type { RequestLogRouteMode, RequestLogUpstreamProtocol } from '@/app/resources/request-logs'
import AppTooltip from '@/components/ui/AppTooltip.vue'

const props = defineProps<{
  mode: RequestLogRouteMode | null
  clientProtocol: AccessProtocol
  upstreamProtocol: RequestLogUpstreamProtocol | null
}>()

const { t } = useI18n()
const clientProtocolLabel = computed(() => props.clientProtocol)
const upstreamProtocolLabel = computed(() =>
  props.upstreamProtocol === null
    ? t('monitor.logs.protocolConversion.notRecorded')
    : props.upstreamProtocol,
)
const tooltip = computed(() => {
  if (props.upstreamProtocol === null) {
    return t('monitor.logs.protocolConversion.tooltipNotRecorded', {
      client: clientProtocolLabel.value,
    })
  }
  return t('monitor.logs.protocolConversion.tooltip', {
    client: clientProtocolLabel.value,
    upstream: upstreamProtocolLabel.value,
  })
})
const label = computed(() =>
  t('monitor.logs.protocolConversion.label', {
    client: clientProtocolLabel.value,
    upstream: upstreamProtocolLabel.value,
  }),
)
</script>

<template>
  <AppTooltip v-if="mode === 'converted'" :content="tooltip">
    <span class="log-protocol-conversion" tabindex="0" :aria-label="label">
      <ArrowRightLeft :size="14" :stroke-width="1.8" aria-hidden="true" />
    </span>
  </AppTooltip>
</template>

<style scoped>
.log-protocol-conversion {
  display: inline-flex;
  width: 24px;
  height: 24px;
  flex: 0 0 auto;
  align-items: center;
  justify-content: center;
  border-radius: var(--radius-tag);
  color: var(--color-warning);
  cursor: help;
}

.log-protocol-conversion:hover {
  background: color-mix(in srgb, var(--color-warning) 10%, transparent);
}

.log-protocol-conversion:focus-visible {
  outline: 2px solid var(--color-focus);
  outline-offset: 1px;
}
</style>
