// web/src/frontends/astryx/features/monitor/MonitorView.tsx
import * as stylex from '@stylexjs/stylex'
import { Button, Selector, Tab, TabList } from '@astryxdesign/core'
import { useNavigate, useRouterState } from '@tanstack/react-router'
import { ListFilter, RefreshCw } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react'

import { isTimeRange } from '@shared/lib/time'
import { usageRanges } from '@shared/control/resources/usage'
import { pagePath } from '@shared/routing/page-routes'
import {
  normalizeAccessKeyMonitorQuery,
  normalizeMonitorQuery,
  normalizeMonitorTab,
  parseHealthMonitorState,
  parseUsageMonitorState,
  sameMonitorQuery,
  scopeAccessKeyUsageFilters,
  usageMonitorQuery,
} from '@shared/routing/monitor-route'
import { parseAppliedUsageFilters } from '@shared/domain/monitor/usage-filters'
import type { SharedRouteQuery } from '@shared/routing/route-query'
import type { MessageId } from '@shared/i18n/message-ids'

import { useAppServices } from '../../app/services'
import { useT } from '../../app/i18n'
import { HealthTab, type HealthTabHandle } from './HealthTab'
import { InspectorTab } from './InspectorTab'
import { UsageTab, type UsageTabHandle } from './UsageTab'

const styles = stylex.create({
  page: {
    display: 'grid',
    minWidth: 0,
  },
  sheet: {
    display: 'grid',
    minWidth: 0,
    alignContent: 'start',
    gap: 0,
    minHeight: {
      default: '760px',
      '@media (max-width: 800px)': '0',
    },
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--space-3)',
  },
  title: {
    margin: 0,
    fontSize: 'var(--text-title)',
    fontWeight: 650,
  },
  tabRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--space-2)',
    minWidth: 0,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border)',
  },
  usageActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-2)',
    paddingBottom: 'var(--space-1)',
  },
  filterCount: {
    display: 'inline-grid',
    minWidth: '17px',
    height: '17px',
    placeItems: 'center',
    borderRadius: '999px',
    background: 'var(--color-action-soft)',
    color: 'var(--color-action)',
    paddingInline: '4px',
    fontFamily: 'var(--font-mono)',
    fontSize: '10px',
  },
  panel: {
    minWidth: 0,
    paddingTop: {
      default: 'var(--detail-panel-padding-top, var(--space-5))',
      '@media (max-width: 800px)': 'var(--detail-panel-padding-top-compact, var(--space-4))',
    },
  },
})

export function MonitorView() {
  const t = useT()
  const navigate = useNavigate()
  const { authSession } = useAppServices()
  const sessionState = useSyncExternalStore(authSession.subscribe, authSession.getState)
  const isAccessKey = sessionState.principalType === 'access_key'
  const isAdmin = sessionState.principalType === 'admin'

  const { rawSearch, searchStr } = useRouterState({
    select: (state) => ({
      rawSearch: state.location.search as SharedRouteQuery,
      searchStr: state.location.searchStr,
    }),
  })
  const monitorPath = pagePath('monitor')

  const canonicalQuery = useMemo(
    () =>
      isAccessKey ? normalizeAccessKeyMonitorQuery(rawSearch) : normalizeMonitorQuery(rawSearch),
    [rawSearch, isAccessKey],
  )
  const activeTab = normalizeMonitorTab(canonicalQuery.tab)
  const isCanonicalQuery = sameMonitorQuery(rawSearch, canonicalQuery)

  // Classic deep watch on route.query (immediate): canonicalize by replace.
  useEffect(() => {
    if (!isCanonicalQuery) {
      void navigate({
        to: monitorPath,
        search: canonicalQuery,
        replace: true,
        resetScroll: false,
      })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- keyed on the URL string
  }, [searchStr])

  const usageFilters = useMemo(() => {
    const filters = parseAppliedUsageFilters(rawSearch)
    return isAccessKey ? scopeAccessKeyUsageFilters(filters) : filters
  }, [rawSearch, isAccessKey])
  const usageFilterCount =
    Number(!isAccessKey && usageFilters.group_id !== undefined) +
    Number(!isAccessKey && usageFilters.channel_id !== undefined) +
    Number(!isAccessKey && usageFilters.credential_id !== undefined) +
    Number(usageFilters.upstream_model !== undefined)

  const usageRangeOptions = useMemo(
    () =>
      usageRanges.map((value) => ({
        value,
        label: t(`monitor.usage.filters.ranges.${value}` as MessageId),
      })),
    [t],
  )

  const tabs = isAdmin ? (['health', 'usage', 'inspector'] as const) : (['usage'] as const)

  function selectTab(value: string): void {
    const tab = normalizeMonitorTab(value)
    if (tab === activeTab) return
    if (isAccessKey && tab !== 'usage') return
    void navigate({ to: monitorPath, search: { tab }, resetScroll: false })
  }

  const healthTabRef = useRef<HealthTabHandle | null>(null)
  const usageTabRef = useRef<UsageTabHandle | null>(null)
  const [healthRefreshPending, setHealthRefreshPending] = useState(false)
  const [usageRefreshPending, setUsageRefreshPending] = useState(false)

  async function refreshHealth(): Promise<void> {
    if (!healthTabRef.current || healthRefreshPending) return
    setHealthRefreshPending(true)
    try {
      await healthTabRef.current.refresh()
    } finally {
      setHealthRefreshPending(false)
    }
  }

  async function refreshUsage(): Promise<void> {
    if (!usageTabRef.current || usageRefreshPending) return
    setUsageRefreshPending(true)
    try {
      await usageTabRef.current.refresh()
    } finally {
      setUsageRefreshPending(false)
    }
  }

  function selectUsageRange(value: string | number): void {
    if (!isTimeRange(value)) return
    const state = parseUsageMonitorState(rawSearch)
    void navigate({
      to: monitorPath,
      search: usageMonitorQuery(
        { ...usageFilters, range: value },
        { filtersOpen: false, seriesExpanded: false, metric: state.metric },
      ),
      resetScroll: false,
    })
  }

  return (
    <section {...stylex.props(styles.page)} aria-labelledby="monitor-title">
      <div {...stylex.props(styles.sheet)}>
        <div {...stylex.props(styles.headerRow)}>
          <h1 id="monitor-title" {...stylex.props(styles.title)}>
            {t('monitor.title')}
          </h1>
        </div>

        <div {...stylex.props(styles.tabRow)}>
          <TabList
            value={activeTab}
            onChange={selectTab}
            size="sm"
            role="tablist"
            aria-label={t('monitor.tabs.label')}
          >
            {tabs.map((tab) => (
              <Tab key={tab} value={tab} label={t(`monitor.tabs.${tab}` as MessageId)} />
            ))}
          </TabList>

          {activeTab === 'health' && (
            <Button
              variant="secondary"
              size="sm"
              isLoading={healthRefreshPending}
              icon={<RefreshCw size={14} aria-hidden />}
              label={t('monitor.health.refresh')}
              onClick={() => void refreshHealth()}
            />
          )}
          {activeTab === 'usage' && (
            <div {...stylex.props(styles.usageActions)}>
              <Selector
                label={t('monitor.usage.filters.range')}
                isLabelHidden
                variant="ghost"
                size="sm"
                value={usageFilters.range}
                options={usageRangeOptions}
                onChange={selectUsageRange}
              />
              <Button
                variant="secondary"
                size="sm"
                icon={<ListFilter size={14} aria-hidden />}
                label={t('monitor.usage.filters.button')}
                onClick={() => usageTabRef.current?.openFilters()}
              />
              {usageFilterCount > 0 && (
                <span {...stylex.props(styles.filterCount)}>{usageFilterCount}</span>
              )}
              <Button
                variant="secondary"
                size="sm"
                isLoading={usageRefreshPending}
                icon={<RefreshCw size={14} aria-hidden />}
                label={t('monitor.usage.filters.refresh')}
                onClick={() => void refreshUsage()}
              />
            </div>
          )}
        </div>

        {isCanonicalQuery && (
          <div {...stylex.props(styles.panel)} role="tabpanel">
            {activeTab === 'health' && (
              <HealthTab
                handleRef={healthTabRef}
                groupsExpanded={parseHealthMonitorState(canonicalQuery).groupsExpanded}
              />
            )}
            {activeTab === 'usage' && <UsageTab handleRef={usageTabRef} />}
            {activeTab === 'inspector' && <InspectorTab />}
          </div>
        )}
      </div>
    </section>
  )
}

// web/src/frontends/classic/features/monitor/MonitorView.vue
<script setup lang="ts">
import { ListFilter, RefreshCw } from '@lucide/vue'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'

import { lazySurface } from '@/app/async-surface'
import { monitorLocation } from '@/app/route-locations'
import { usageRanges } from '@/app/resources/usage'
import LedgerSheet from '@/components/layout/LedgerSheet.vue'
import PageFrame from '@/components/layout/PageFrame.vue'
import AppButton from '@/components/ui/AppButton.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import AppTabs, { type AppTabItem } from '@/components/ui/AppTabs.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import { isTimeRange } from '@shared/lib/time'
import { useAuthSession } from '@/features/auth/auth-session'

import HealthTab from './HealthTab.vue'
import {
  normalizeAccessKeyMonitorQuery,
  normalizeMonitorQuery,
  normalizeMonitorTab,
  parseUsageMonitorState,
  sameMonitorQuery,
  scopeAccessKeyUsageFilters,
} from './monitor-route'
import { usageMonitorQuery } from './monitor-route'
import { parseAppliedUsageFilters } from './usage-filters'

const InspectorTab = lazySurface(() => import('./InspectorTab.vue'))
const UsageTab = lazySurface(() => import('./UsageTab.vue'))

const route = useRoute()
const session = useAuthSession()
const router = useRouter()
const { t } = useI18n()
const healthTab = ref<InstanceType<typeof HealthTab> | null>(null)
const usageTab = ref<{ openFilters: () => void; refresh: () => Promise<void> } | null>(null)
const healthRefreshPending = ref(false)
const usageRefreshPending = ref(false)
const isAccessKey = computed(() => session.state.principalType === 'access_key')
const isAdmin = computed(() => session.state.principalType === 'admin')
const canonicalQuery = computed(() => {
  if (isAdmin.value) return normalizeMonitorQuery(route.query)
  if (isAccessKey.value) return normalizeAccessKeyMonitorQuery(route.query)
  return normalizeMonitorQuery(route.query)
})
const activeTab = computed(() => normalizeMonitorTab(canonicalQuery.value.tab))
const isCanonicalQuery = computed(() => sameMonitorQuery(route.query, canonicalQuery.value))
const items = computed<AppTabItem[]>(() => {
  const shared = [{ value: 'usage', label: t('monitor.tabs.usage') }]
  return isAdmin.value
    ? [
        { value: 'health', label: t('monitor.tabs.health') },
        ...shared,
        { value: 'inspector', label: t('monitor.tabs.inspector') },
      ]
    : shared
})
const usageFilters = computed(() => {
  const filters = parseAppliedUsageFilters(route.query)
  return isAccessKey.value ? scopeAccessKeyUsageFilters(filters) : filters
})
const usageRangeOptions = computed(() =>
  usageRanges.map((value) => ({
    value,
    label: t(`monitor.usage.filters.ranges.${value}`),
  })),
)
const usageFilterCount = computed(
  () =>
    Number(!isAccessKey.value && usageFilters.value.group_id !== undefined) +
    Number(!isAccessKey.value && usageFilters.value.channel_id !== undefined) +
    Number(!isAccessKey.value && usageFilters.value.credential_id !== undefined) +
    Number(usageFilters.value.upstream_model !== undefined),
)

watch(
  () => route.query,
  (query) => {
    const normalized = canonicalQuery.value
    if (!sameMonitorQuery(query, normalized)) {
      void router.replace(monitorLocation(normalized))
    }
  },
  { immediate: true },
)

function selectTab(value: string): void {
  const tab = normalizeMonitorTab(value)
  if (tab === activeTab.value) return
  if (isAccessKey.value && tab !== 'usage') return
  void router.push(monitorLocation({ tab }))
}

async function refreshHealth(): Promise<void> {
  if (!healthTab.value || healthRefreshPending.value) return
  healthRefreshPending.value = true
  try {
    await healthTab.value.refresh()
  } finally {
    healthRefreshPending.value = false
  }
}

async function refreshUsage(): Promise<void> {
  if (!usageTab.value || usageRefreshPending.value) return
  usageRefreshPending.value = true
  try {
    await usageTab.value.refresh()
  } finally {
    usageRefreshPending.value = false
  }
}

function selectUsageRange(value: string): void {
  if (!isTimeRange(value)) return
  const state = parseUsageMonitorState(route.query)
  void router.push(
    monitorLocation(
      usageMonitorQuery(
        { ...usageFilters.value, range: value },
        {
          filtersOpen: false,
          seriesExpanded: false,
          metric: state.metric,
        },
      ),
    ),
  )
}
</script>

<template>
  <PageFrame aria-labelledby="monitor-title">
    <LedgerSheet class="monitor-page">
      <PageHeader id="monitor-title" :title="t('monitor.title')" />
      <AppTabs
        class="monitor-tabs"
        :model-value="activeTab"
        :label="t('monitor.tabs.label')"
        :items="items"
        appearance="detail"
        @update:model-value="selectTab"
      >
        <template #actions>
          <AppButton
            v-if="activeTab === 'health'"
            class="monitor-refresh"
            variant="secondary"
            size="compact"
            :busy="healthRefreshPending"
            @click="refreshHealth"
          >
            <RefreshCw
              :class="{ 'monitor-refresh-icon--spinning': healthRefreshPending }"
              :size="14"
              aria-hidden="true"
            />
            {{ t('monitor.health.refresh') }}
          </AppButton>
          <div v-else-if="activeTab === 'usage'" class="monitor-usage-actions">
            <AppSelect
              :model-value="usageFilters.range"
              :label="t('monitor.usage.filters.range')"
              :options="usageRangeOptions"
              size="compact"
              @update:model-value="selectUsageRange"
            />
            <AppButton variant="secondary" size="compact" @click="usageTab?.openFilters()">
              <ListFilter :size="14" aria-hidden="true" />
              {{ t('monitor.usage.filters.button') }}
              <span v-if="usageFilterCount > 0" class="monitor-filter-count">
                {{ usageFilterCount }}
              </span>
            </AppButton>
            <AppButton
              class="monitor-refresh"
              variant="secondary"
              size="compact"
              :busy="usageRefreshPending"
              @click="refreshUsage"
            >
              <RefreshCw
                :class="{ 'monitor-refresh-icon--spinning': usageRefreshPending }"
                :size="14"
                aria-hidden="true"
              />
              {{ t('monitor.usage.filters.refresh') }}
            </AppButton>
          </div>
        </template>

        <template v-if="isCanonicalQuery">
          <div v-if="activeTab === 'health'" class="monitor-panel">
            <HealthTab ref="healthTab" />
          </div>
          <div v-else-if="activeTab === 'usage'" class="monitor-panel">
            <UsageTab ref="usageTab" />
          </div>
          <div v-else-if="activeTab === 'inspector'" class="monitor-panel">
            <InspectorTab />
          </div>
        </template>
      </AppTabs>
    </LedgerSheet>
  </PageFrame>
</template>

<style scoped>
.monitor-page {
  display: grid;
  min-height: 760px;
  min-width: 0;
  align-content: start;
  gap: 0;
}

.monitor-panel {
  min-width: 0;
  padding-top: var(--detail-panel-padding-top);
}

.monitor-tabs {
  min-width: 0;
}

.monitor-tabs :deep(.app-tabs__content) {
  min-width: 0;
}

.monitor-tabs :deep(.app-tabs__bar) {
  border-top: 0;
}

.monitor-refresh-icon--spinning {
  animation: monitor-refresh-spin 800ms linear infinite;
}

.monitor-refresh[aria-busy='true'] {
  opacity: 1;
}

.monitor-usage-actions {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.monitor-filter-count {
  display: inline-grid;
  min-width: 17px;
  height: 17px;
  place-items: center;
  border-radius: 999px;
  background: var(--color-action-soft);
  color: var(--color-action);
  padding-inline: 4px;
  font-family: var(--font-mono);
  font-size: 10px;
}

@keyframes monitor-refresh-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (max-width: 800px) {
  .monitor-page {
    min-height: 0;
  }

  .monitor-panel {
    padding-top: var(--detail-panel-padding-top-compact);
  }
}

@media (max-width: 560px) {
  .monitor-usage-actions {
    gap: var(--space-1);
  }
}

@media (prefers-reduced-motion: reduce) {
  .monitor-refresh-icon--spinning {
    animation: none;
  }
}
</style>
