// web/src/frontends/astryx/features/monitor/ScheduleView.tsx
import * as stylex from '@stylexjs/stylex'
import { useNavigate, useRouterState } from '@tanstack/react-router'
import { useEffect, useMemo, useRef, useSyncExternalStore } from 'react'
import { useIntl } from 'react-intl'

import { pagePath } from '@shared/routing/page-routes'
import {
  parseScheduleMonitorState,
  sameMonitorQuery,
  scheduleMonitorQuery,
  type ScheduleDrafts,
  type ScheduleMonitorState,
} from '@shared/routing/monitor-route'
import type { SharedRouteQuery } from '@shared/routing/route-query'
import type { MessageId } from '@shared/i18n/message-ids'

import { useAppServices } from '../../app/services'
import { useT } from '../../app/i18n'
import { SchedulePanel, type SchedulePanelLabels } from './SchedulePanel'

const styles = stylex.create({
  page: {
    display: 'grid',
    minWidth: 0,
  },
  sheet: {
    display: 'grid',
    minWidth: 0,
    alignContent: 'start',
    gap: 0,
    minHeight: {
      default: '760px',
      '@media (max-width: 800px)': '0',
    },
  },
  title: {
    margin: 0,
    fontSize: 'var(--text-title)',
    fontWeight: 650,
  },
  panel: {
    minWidth: 0,
    paddingTop: {
      default: 'var(--detail-panel-padding-top)',
      '@media (max-width: 800px)': 'var(--detail-panel-padding-top-compact)',
    },
  },
})

const scheduleReasonCodes = [
  'access_key_disabled',
  'access_key_expired',
  'protocol_filtered',
  'model_filtered',
  'model_required_by_filter',
  'operation_unsupported',
  'native_route_required',
  'no_route_target',
  'group_disabled',
  'group_filtered',
  'no_available_group',
  'no_credentials',
  'credential_blacklisted',
  'credential_cooldown',
  'credential_auth_unavailable',
  'credential_not_allowed',
  'no_available_credential',
  'entry_disabled',
  'entry_blacklisted',
  'entry_cooldown',
  'entry_weight_zero',
  'tier_demoted',
] as const

export function ScheduleView() {
  const t = useT()
  const intl = useIntl()
  const navigate = useNavigate()
  const { authSession } = useAppServices()
  const sessionState = useSyncExternalStore(authSession.subscribe, authSession.getState)
  const isAdmin = sessionState.principalType === 'admin'

  const { rawSearch, searchStr } = useRouterState({
    select: (state) => ({
      rawSearch: state.location.search as SharedRouteQuery,
      searchStr: state.location.searchStr,
    }),
  })
  const schedulePath = pagePath('schedule')

  const scheduleState = useMemo(() => parseScheduleMonitorState(rawSearch), [rawSearch])
  const canonicalQuery = useMemo(
    () => scheduleMonitorQuery(scheduleState),
    [scheduleState],
  )
  const isCanonicalQuery = sameMonitorQuery(rawSearch, canonicalQuery)

  // Classic deep watch on route.query (immediate): canonicalize by replace.
  useEffect(() => {
    if (!isCanonicalQuery) {
      void navigate({
        to: schedulePath,
        search: canonicalQuery,
        replace: true,
        resetScroll: false,
      })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- keyed on the URL string
  }, [searchStr])

  // Classic pendingScheduleState: consecutive draft/row replaces must merge
  // onto the in-flight target, not the last committed URL. Kept in a ref —
  // rendering always follows the committed location.
  const pendingStateRef = useRef<ScheduleMonitorState | null>(null)
  const pendingGenerationRef = useRef(0)

  async function navigateScheduleState(
    next: ScheduleMonitorState,
    method: 'push' | 'replace',
  ): Promise<void> {
    pendingGenerationRef.current += 1
    const generation = pendingGenerationRef.current
    pendingStateRef.current = next
    await navigate({
      to: schedulePath,
      search: scheduleMonitorQuery(next),
      replace: method === 'replace',
      resetScroll: false,
    })
    if (generation !== pendingGenerationRef.current) return
    pendingStateRef.current = null
  }

  function updateScheduleContext(
    next: Partial<ScheduleMonitorState>,
    method: 'push' | 'replace',
  ): void {
    const current = pendingStateRef.current ?? scheduleState
    const contextChanged =
      next.externalModel !== undefined && next.externalModel !== current.externalModel
    const nextState: ScheduleMonitorState = contextChanged
      ? { ...current, ...next, selectedRow: undefined, sourceGroupId: undefined, drafts: {} }
      : { ...current, ...next }
    void navigateScheduleState(nextState, method)
  }

  // Classic commitScheduleContext: context commits push; draft/row churn stays
  // replace-only so it never pollutes history.
  function commitScheduleContext(context: { externalModel?: string }): void {
    const current = pendingStateRef.current ?? scheduleState
    const externalModel = context.externalModel?.trim() || undefined
    const contextChanged = externalModel !== current.externalModel
    const next: ScheduleMonitorState = contextChanged
      ? {
          ...current,
          externalModel,
          selectedRow: undefined,
          sourceGroupId: undefined,
          drafts: {},
        }
      : { ...current, externalModel }
    if (sameMonitorQuery(rawSearch, scheduleMonitorQuery(next))) return
    void navigateScheduleState(next, 'push')
  }

  const scheduleLabels = useMemo<SchedulePanelLabels>(
    () => ({
      model: t('monitor.schedule.panel.model'),
      selectModel: t('monitor.schedule.panel.selectModel'),
      loadingOptions: t('monitor.schedule.panel.loadingOptions'),
      contextRequired: t('monitor.schedule.panel.contextRequired'),
      kicker: t('monitor.schedule.panel.kicker'),
      contextReady: t('monitor.schedule.panel.contextReady'),
      context: t('monitor.schedule.panel.context'),
      retry: t('monitor.schedule.panel.retry'),
      indexFailed: t('monitor.schedule.panel.indexFailed'),
      detailFailed: t('monitor.schedule.panel.detailFailed'),
      detail: {
        title: t('monitor.schedule.detail.title'),
        loading: t('monitor.schedule.detail.loading'),
        refresh: t('monitor.schedule.detail.refresh'),
        stale: t('monitor.schedule.detail.stale'),
        observedAt: t('monitor.schedule.detail.observedAt'),
        routeUnavailable: t('monitor.schedule.detail.routeUnavailable'),
        group: t('monitor.schedule.detail.group'),
        upstreamModel: t('monitor.schedule.detail.upstreamModel'),
        weight: t('monitor.schedule.detail.weight'),
        priority: t('monitor.schedule.detail.priority'),
        share: t('monitor.schedule.detail.share'),
        status: t('monitor.schedule.detail.status'),
        available: t('monitor.schedule.detail.available'),
        cooldown: t('monitor.schedule.detail.cooldown'),
        blacklisted: t('monitor.schedule.detail.blacklisted'),
        failures: t('monitor.schedule.detail.failures'),
        recover: t('monitor.schedule.detail.recover'),
        breakerRecovery: t('monitor.schedule.detail.breakerRecovery'),
        breakerThreshold: t('monitor.schedule.detail.breakerThreshold'),
        breakerCooldown: t('monitor.schedule.detail.breakerCooldown'),
        invalidValue: t('monitor.schedule.detail.invalidValue'),
        derivedReadOnly: t('monitor.schedule.detail.derivedReadOnly'),
        save: t('monitor.schedule.detail.save'),
        discard: t('monitor.schedule.detail.discard'),
        unsaved: t('monitor.schedule.detail.unsaved'),
        saved: t('monitor.schedule.detail.saved'),
        saveFailed: t('monitor.schedule.detail.saveFailed'),
        conflict: t('monitor.schedule.detail.conflict'),
        refreshToResolve: t('monitor.schedule.detail.refreshToResolve'),
        recoverFailed: t('monitor.schedule.detail.recoverFailed'),
        noEntries: t('monitor.schedule.detail.noEntries'),
        unknownReason: t('monitor.schedule.detail.unknownReason'),
        draftPreview: t('monitor.schedule.detail.draftPreview'),
        reasonLabels: Object.fromEntries(
          scheduleReasonCodes.map((code) => [
            code,
            t(`monitor.schedule.reasons.${code}` as MessageId),
          ]),
        ),
      },
    }),
    [t],
  )

  return (
    <section {...stylex.props(styles.page)} aria-labelledby="schedule-title">
      <div {...stylex.props(styles.sheet)} data-testid="schedule-page">
        <h1 id="schedule-title" {...stylex.props(styles.title)}>
          {t('shell.schedule')}
        </h1>
        {isAdmin && isCanonicalQuery && (
          <div {...stylex.props(styles.panel)}>
            <SchedulePanel
              externalModel={scheduleState.externalModel}
              selectedRow={scheduleState.selectedRow}
              sourceGroupId={scheduleState.sourceGroupId}
              drafts={scheduleState.drafts}
              labels={scheduleLabels}
              locale={intl.locale}
              onChangeContext={commitScheduleContext}
              onDraftChange={(drafts: ScheduleDrafts) =>
                updateScheduleContext({ drafts }, 'replace')
              }
              onRowChange={(row) => updateScheduleContext({ selectedRow: row }, 'replace')}
              onSaved={() => updateScheduleContext({}, 'replace')}
              onRecovered={() => updateScheduleContext({}, 'replace')}
              onRefresh={() => updateScheduleContext({}, 'replace')}
            />
          </div>
        )}
      </div>
    </section>
  )
}

// web/src/frontends/classic/features/monitor/ScheduleView.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'

import { lazySurface } from '@/app/async-surface'
import { scheduleLocation } from '@/app/route-locations'
import LedgerSheet from '@/components/layout/LedgerSheet.vue'
import PageFrame from '@/components/layout/PageFrame.vue'
import PageHeader from '@/components/ui/PageHeader.vue'
import { useAuthSession } from '@/features/auth/auth-session'

import type { ScheduleDrafts, ScheduleMonitorState } from './monitor-route'
import { parseScheduleMonitorState, sameMonitorQuery, scheduleMonitorQuery } from './monitor-route'
import type { SchedulePanelLabels } from './SchedulePanel.vue'

const SchedulePanel = lazySurface(() => import('./SchedulePanel.vue'))

const route = useRoute()
const session = useAuthSession()
const router = useRouter()
const { locale, t } = useI18n()

const isAdmin = computed(() => session.state.principalType === 'admin')
const scheduleState = computed(() => parseScheduleMonitorState(route.query))
const pendingScheduleState = ref<ScheduleMonitorState>()
const pendingNavigationGeneration = ref(0)
const renderedScheduleState = computed(() => pendingScheduleState.value ?? scheduleState.value)
const canonicalQuery = computed(() => scheduleMonitorQuery(scheduleState.value))
const isCanonicalQuery = computed(() => sameMonitorQuery(route.query, canonicalQuery.value))

watch(
  () => route.query,
  (query) => {
    const pending = pendingScheduleState.value
    if (pending) {
      pendingNavigationGeneration.value += 1
      pendingScheduleState.value = undefined
    }
    const normalized = canonicalQuery.value
    if (!sameMonitorQuery(query, normalized)) {
      void router.replace(scheduleLocation(normalized))
    }
  },
  { immediate: true },
)

async function navigateScheduleState(
  next: ScheduleMonitorState,
  method: 'push' | 'replace',
): Promise<void> {
  const generation = pendingNavigationGeneration.value + 1
  pendingNavigationGeneration.value = generation
  pendingScheduleState.value = next
  const target = scheduleLocation(scheduleMonitorQuery(next))
  const failure = await router[method](target)
  if (generation !== pendingNavigationGeneration.value) return
  pendingScheduleState.value = undefined
  if (failure) return
}

function replaceScheduleState(next: ScheduleMonitorState): void {
  void navigateScheduleState(next, 'replace')
}

function updateScheduleContext(next: Partial<ReturnType<typeof parseScheduleMonitorState>>): void {
  const current = renderedScheduleState.value
  const contextChanged =
    next.externalModel !== undefined && next.externalModel !== current.externalModel
  const nextState = contextChanged
    ? { ...current, ...next, selectedRow: undefined, sourceGroupId: undefined, drafts: {} }
    : { ...current, ...next }
  replaceScheduleState(nextState)
}

function commitScheduleContext(context: { externalModel?: string }): void {
  const current = renderedScheduleState.value
  const externalModel = context.externalModel?.trim() || undefined
  const contextChanged = externalModel !== current.externalModel
  const next = contextChanged
    ? {
        ...current,
        ...context,
        externalModel,
        selectedRow: undefined,
        sourceGroupId: undefined,
        drafts: {},
      }
    : { ...current, ...context, externalModel }
  if (sameMonitorQuery(route.query, scheduleMonitorQuery(next))) return
  void navigateScheduleState(next, 'push')
}

function updateScheduleDrafts(drafts: ScheduleDrafts): void {
  updateScheduleContext({ drafts })
}

function updateScheduleRow(row: string | undefined): void {
  updateScheduleContext({ selectedRow: row })
}

function refreshScheduleRoute(): void {
  replaceScheduleState(renderedScheduleState.value)
}

const scheduleLabels = computed<SchedulePanelLabels>(() => ({
  model: t('monitor.schedule.panel.model'),
  selectModel: t('monitor.schedule.panel.selectModel'),
  loadingOptions: t('monitor.schedule.panel.loadingOptions'),
  contextRequired: t('monitor.schedule.panel.contextRequired'),
  kicker: t('monitor.schedule.panel.kicker'),
  contextReady: t('monitor.schedule.panel.contextReady'),
  context: t('monitor.schedule.panel.context'),
  retry: t('monitor.schedule.panel.retry'),
  indexFailed: t('monitor.schedule.panel.indexFailed'),
  detailFailed: t('monitor.schedule.panel.detailFailed'),
  detail: {
    title: t('monitor.schedule.detail.title'),
    loading: t('monitor.schedule.detail.loading'),
    refresh: t('monitor.schedule.detail.refresh'),
    stale: t('monitor.schedule.detail.stale'),
    observedAt: t('monitor.schedule.detail.observedAt'),
    routeUnavailable: t('monitor.schedule.detail.routeUnavailable'),
    group: t('monitor.schedule.detail.group'),
    upstreamModel: t('monitor.schedule.detail.upstreamModel'),
    weight: t('monitor.schedule.detail.weight'),
    priority: t('monitor.schedule.detail.priority'),
    share: t('monitor.schedule.detail.share'),
    status: t('monitor.schedule.detail.status'),
    available: t('monitor.schedule.detail.available'),
    cooldown: t('monitor.schedule.detail.cooldown'),
    blacklisted: t('monitor.schedule.detail.blacklisted'),
    failures: t('monitor.schedule.detail.failures'),
    recover: t('monitor.schedule.detail.recover'),
    breakerRecovery: t('monitor.schedule.detail.breakerRecovery'),
    breakerThreshold: t('monitor.schedule.detail.breakerThreshold'),
    breakerCooldown: t('monitor.schedule.detail.breakerCooldown'),
    invalidValue: t('monitor.schedule.detail.invalidValue'),
    derivedReadOnly: t('monitor.schedule.detail.derivedReadOnly'),
    save: t('monitor.schedule.detail.save'),
    discard: t('monitor.schedule.detail.discard'),
    unsaved: t('monitor.schedule.detail.unsaved'),
    saved: t('monitor.schedule.detail.saved'),
    saveFailed: t('monitor.schedule.detail.saveFailed'),
    conflict: t('monitor.schedule.detail.conflict'),
    refreshToResolve: t('monitor.schedule.detail.refreshToResolve'),
    recoverFailed: t('monitor.schedule.detail.recoverFailed'),
    noEntries: t('monitor.schedule.detail.noEntries'),
    unknownReason: t('monitor.schedule.detail.unknownReason'),
    draftPreview: t('monitor.schedule.detail.draftPreview'),
    reasonLabels: Object.fromEntries(
      [
        'access_key_disabled',
        'access_key_expired',
        'protocol_filtered',
        'model_filtered',
        'model_required_by_filter',
        'operation_unsupported',
        'native_route_required',
        'no_route_target',
        'group_disabled',
        'group_filtered',
        'no_available_group',
        'no_credentials',
        'credential_blacklisted',
        'credential_cooldown',
        'credential_auth_unavailable',
        'credential_not_allowed',
        'no_available_credential',
        'entry_disabled',
        'entry_blacklisted',
        'entry_cooldown',
        'entry_weight_zero',
        'tier_demoted',
      ].map((code) => [code, t(`monitor.schedule.reasons.${code}`)]),
    ),
  },
}))
</script>

<template>
  <PageFrame aria-labelledby="schedule-title" wide>
    <LedgerSheet class="schedule-page">
      <PageHeader id="schedule-title" :title="t('shell.schedule')" />
      <div v-if="isAdmin && isCanonicalQuery" class="schedule-page__panel">
        <SchedulePanel
          :external-model="renderedScheduleState.externalModel"
          :selected-row="renderedScheduleState.selectedRow"
          :source-group-id="renderedScheduleState.sourceGroupId"
          :drafts="renderedScheduleState.drafts"
          :labels="scheduleLabels"
          :locale="locale"
          @change-context="commitScheduleContext"
          @draft-change="updateScheduleDrafts"
          @row-change="updateScheduleRow"
          @saved="refreshScheduleRoute"
          @recovered="refreshScheduleRoute"
          @refresh="refreshScheduleRoute"
        />
      </div>
    </LedgerSheet>
  </PageFrame>
</template>

<style scoped>
.schedule-page {
  display: grid;
  min-height: 760px;
  min-width: 0;
  align-content: start;
  gap: 0;
}

.schedule-page__panel {
  min-width: 0;
  padding-top: var(--detail-panel-padding-top);
}

@media (max-width: 800px) {
  .schedule-page {
    min-height: 0;
  }

  .schedule-page__panel {
    padding-top: var(--detail-panel-padding-top-compact);
  }
}
</style>
