// web/src/frontends/astryx/features/monitor/UsageTab.tsx
import * as stylex from '@stylexjs/stylex'
import { Banner, Button, EmptyState, Skeleton } from '@astryxdesign/core'
import { useQuery } from '@tanstack/react-query'
import { useNavigate, useRouterState } from '@tanstack/react-router'
import { Database, TriangleAlert } from 'lucide-react'
import { useImperativeHandle, useMemo, useState, useSyncExternalStore, type Ref } from 'react'

import { controlQueryKeys } from '@shared/control/query-keys'
import { listChannels } from '@shared/control/resources/channels'
import { groupOptionsQueryOptions } from '@shared/control/resources/groups'
import {
  normalizeUsageBreakdownSort,
  normalizeUsageBreakdownSortDirection,
  usageQueryOptions,
  type UsageBreakdownSort,
  type UsageBreakdownSortDirection,
  type UsageFilters,
} from '@shared/control/resources/usage'
import {
  applyUsageFilterDraft,
  createUsageFilterDraft,
  parseAppliedUsageFilters,
  validateUsageFilterDraft,
  type UsageFilterDraft,
  type UsageFilterErrors,
} from '@shared/domain/monitor/usage-filters'
import { pagePath } from '@shared/routing/page-routes'
import { scopeAccessKeyUsageFilters, usageMonitorQuery } from '@shared/routing/monitor-route'
import type { SharedRouteQuery } from '@shared/routing/route-query'

import { useAppServices } from '../../app/services'
import { useCollectionLoading } from '../../app/collection-loading'
import { useT } from '../../app/i18n'
import { MonitorSectionHeading } from './MonitorSectionHeading'
import { UsageBreakdownTable } from './UsageBreakdownTable'
import { UsageFilterBar } from './UsageFilterBar'

const styles = stylex.create({
  root: {
    display: 'grid',
    minWidth: 0,
    gap: '22px',
  },
  refreshing: {
    minHeight: 'var(--space-4)',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
  },
  skeleton: {
    display: 'grid',
    gap: 'var(--space-2)',
  },
  section: {
    display: 'grid',
    minWidth: 0,
    gap: '12px',
  },
})

export interface UsageTabHandle {
  refresh(): Promise<void>
}

export function UsageTab({ handleRef }: { handleRef?: Ref<UsageTabHandle> }) {
  const t = useT()
  const navigate = useNavigate()
  const { apiClient, authSession } = useAppServices()
  const sessionState = useSyncExternalStore(authSession.subscribe, authSession.getState)
  const isAccessKey = sessionState.principalType === 'access_key'

  const rawSearch = useRouterState({
    select: (state) => state.location.search as SharedRouteQuery,
  })
  const monitorPath = pagePath('monitor')

  const appliedFilters = useMemo(() => {
    const filters = parseAppliedUsageFilters(rawSearch)
    return isAccessKey ? scopeAccessKeyUsageFilters(filters) : filters
  }, [rawSearch, isAccessKey])
  const breakdownSort = normalizeUsageBreakdownSort(appliedFilters.breakdown_sort)
  const breakdownSortDirection = normalizeUsageBreakdownSortDirection(
    appliedFilters.breakdown_sort_direction,
    breakdownSort,
  )
  // Resets the draft whenever the applied filter fields change — carried here
  // as a render adjustment on a signature key.
  const draftSignature = `${appliedFilters.range}|${appliedFilters.group_id ?? ''}|${
    appliedFilters.upstream_model ?? ''
  }`
  const [draftState, setDraftState] = useState<{
    signature: string
    draft: UsageFilterDraft
    errors: UsageFilterErrors
  }>(() => ({
    signature: draftSignature,
    draft: createUsageFilterDraft(appliedFilters),
    errors: {},
  }))
  if (draftState.signature !== draftSignature) {
    setDraftState({
      signature: draftSignature,
      draft: createUsageFilterDraft(appliedFilters),
      errors: {},
    })
  }
  const draft = draftState.draft
  const filterErrors = draftState.errors

  const groupsQuery = useQuery(groupOptionsQueryOptions(apiClient, !isAccessKey))
  const channelsQuery = useQuery({
    queryKey: controlQueryKeys.channels.list(''),
    queryFn: ({ signal }) => listChannels(apiClient, '', signal),
    enabled: !isAccessKey,
    staleTime: Number.POSITIVE_INFINITY,
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  })
  const usageQuery = useQuery(usageQueryOptions(apiClient, appliedFilters))
  const report = usageQuery.data

  const loading = useCollectionLoading(
    {
      pending: usageQuery.isPending,
      placeholder: usageQuery.isPlaceholderData,
      fetching: usageQuery.isFetching,
      hasData: report !== undefined,
      itemCount: report?.breakdown.rows.length ?? 0,
    },
    { fallbackRows: 5 },
  )
  const usageRefreshing =
    loading.refreshing ||
    (!isAccessKey && groupsQuery.data !== undefined && groupsQuery.isFetching) ||
    (!isAccessKey && channelsQuery.data !== undefined && channelsQuery.isFetching)

  const hasData = (report?.summary.request_count ?? 0) > 0

  function navigateUsage(filters: UsageFilters): Promise<void> {
    const scopedFilters = isAccessKey ? scopeAccessKeyUsageFilters(filters) : filters
    return navigate({
      to: monitorPath,
      search: usageMonitorQuery(scopedFilters),
      resetScroll: false,
    }) as Promise<void>
  }

  function updateDraftField(field: keyof UsageFilterDraft, value: string): void {
    setDraftState((prev) => ({
      ...prev,
      draft: { ...prev.draft, [field]: value },
    }))
  }

  async function applyFilters(): Promise<void> {
    const errors = validateUsageFilterDraft(draft)
    setDraftState((prev) => ({ ...prev, errors }))
    if (Object.keys(errors).length > 0) return
    await navigateUsage({
      ...applyUsageFilterDraft(draft),
      breakdown_sort: breakdownSort,
      breakdown_sort_direction: breakdownSortDirection,
    })
  }

  async function resetFilters(): Promise<void> {
    setDraftState((prev) => ({
      ...prev,
      draft: createUsageFilterDraft({ range: appliedFilters.range }),
      errors: {},
    }))
    await navigateUsage({
      range: appliedFilters.range,
      breakdown_sort: breakdownSort,
      breakdown_sort_direction: breakdownSortDirection,
    })
  }

  async function setBreakdownPage(page: number): Promise<void> {
    await navigateUsage({ ...appliedFilters, breakdown_page: page })
  }

  async function setBreakdownPageSize(pageSize: 20 | 50 | 100): Promise<void> {
    await navigateUsage({
      ...appliedFilters,
      breakdown_page: 1,
      breakdown_page_size: pageSize,
    })
  }

  async function setBreakdownSort(
    sort: UsageBreakdownSort,
    direction: UsageBreakdownSortDirection,
  ): Promise<void> {
    await navigateUsage({
      ...appliedFilters,
      breakdown_page: 1,
      breakdown_sort: sort,
      breakdown_sort_direction: direction,
    })
  }

  async function refresh(): Promise<void> {
    await Promise.all([
      usageQuery.refetch(),
      ...(!isAccessKey ? [groupsQuery.refetch(), channelsQuery.refetch()] : []),
    ])
  }

  useImperativeHandle(handleRef, () => ({ refresh }))

  return (
    <div {...stylex.props(styles.root)}>
      <span aria-live="polite" {...stylex.props(styles.refreshing)}>
        {usageRefreshing ? t('monitor.usage.loading') : ''}
      </span>

      <UsageFilterBar
        draft={draft}
        errors={filterErrors}
        groups={groupsQuery.data ?? []}
        groupsFailed={groupsQuery.isError}
        selfScoped={isAccessKey}
        onFieldChange={updateDraftField}
        onApply={() => void applyFilters()}
        onReset={() => void resetFilters()}
      />

      {usageQuery.isPending || loading.initial || loading.transition ? (
        <div {...stylex.props(styles.skeleton)} aria-label={t('monitor.usage.loading')}>
          <Skeleton height={38} radius={2} />
          <Skeleton height={320} radius={2} />
        </div>
      ) : usageQuery.isError && !report ? (
        <div role="alert">
          <EmptyState
            title={t('monitor.usage.loadFailed')}
            icon={<TriangleAlert size={20} />}
            actions={
              <Button
                variant="secondary"
                size="sm"
                label={t('common.retry')}
                onClick={() => void usageQuery.refetch()}
              />
            }
          />
        </div>
      ) : report ? (
        <>
          {usageQuery.isError && (
            <Banner
              status="warning"
              title={t('monitor.usage.stale')}
              endContent={
                <Button
                  variant="secondary"
                  size="sm"
                  label={t('common.retry')}
                  onClick={() => void usageQuery.refetch()}
                />
              }
            />
          )}

          {!isAccessKey && (groupsQuery.isError || channelsQuery.isError) && (
            <Banner status="warning" title={t('monitor.usage.options.partialFailed')} />
          )}

          {!hasData ? (
            <EmptyState
              title={t('monitor.usage.empty.title')}
              description={t('monitor.usage.empty.description')}
              icon={<Database size={20} aria-hidden />}
            />
          ) : (
            <section {...stylex.props(styles.section)} aria-labelledby="usage-breakdown-title">
              <MonitorSectionHeading
                id="usage-breakdown-title"
                title={t('monitor.usage.breakdown.title')}
                description={t('monitor.usage.breakdown.description')}
                meta={t('monitor.usage.breakdown.rowCount', {
                  count: report.breakdown.pagination.total_items,
                })}
              />
              <UsageBreakdownTable
                breakdown={report.breakdown}
                groups={groupsQuery.data ?? []}
                channels={channelsQuery.data?.items ?? []}
                sort={breakdownSort}
                sortDirection={breakdownSortDirection}
                onPage={(page) => void setBreakdownPage(page)}
                onPageSize={(size) => void setBreakdownPageSize(size)}
                onSort={(sort, direction) => void setBreakdownSort(sort, direction)}
              />
            </section>
          )}
        </>
      ) : null}
    </div>
  )
}

// web/src/frontends/classic/features/monitor/UsageTab.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import { Database } from '@lucide/vue'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'

import { useApiClient } from '@/app/api-client-context'
import { useCollectionLoading } from '@/app/loading-state'
import { listAccessKeyOptions } from '@/app/resources/access-keys'
import { groupOptionsQueryOptions } from '@/app/resources/groups'
import { listChannels } from '@/app/resources/channels'
import { controlQueryKeys } from '@shared/control/query-keys'
import {
  usageQueryOptions,
  normalizeUsageBreakdownSort,
  normalizeUsageBreakdownSortDirection,
  type UsageAggregateDto,
  type UsageBreakdownSort,
  type UsageBreakdownSortDirection,
  type UsageDistributionDimension,
  type UsageDistributionMetric,
  type UsageFilters,
  type UsageRange,
} from '@/app/resources/usage'
import { monitorLocation } from '@/app/route-locations'
import AppDateTime from '@/components/ui/AppDateTime.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import AsyncRefreshIndicator from '@/components/ui/AsyncRefreshIndicator.vue'
import DataTable from '@/components/ui/DataTable.vue'
import EmptyState from '@/components/ui/EmptyState.vue'
import InlineFeedback from '@/components/ui/InlineFeedback.vue'
import QueryFeedback from '@/components/ui/QueryFeedback.vue'
import SegmentedControl from '@/components/ui/SegmentedControl.vue'
import SkeletonSurface from '@/components/ui/SkeletonSurface.vue'
import { formatEstimatedCost, formatInteger, formatTokens } from '@shared/lib/format'
import { useAuthSession } from '@/features/auth/auth-session'

import MonitorSectionHeading from './MonitorSectionHeading.vue'
import UsageBarChart from './UsageBarChart.vue'
import UsageBreakdownTable from './UsageBreakdownTable.vue'
import UsageDistribution from './UsageDistribution.vue'
import {
  applyUsageFilterDraft,
  createUsageFilterDraft,
  parseAppliedUsageFilters,
  validateUsageFilterDraft,
  type UsageFilterDraft,
  type UsageFilterErrors,
} from './usage-filters'
import type { UsageBarDatum } from './usage-bar-chart'
import {
  parseUsageMonitorState,
  usageMonitorQuery,
  type UsageMonitorState,
  type UsageTrendMetric,
  scopeAccessKeyUsageFilters,
} from './monitor-route'
import UsageFilterForm from './UsageFilterForm.vue'
import UsageSummary from './UsageSummary.vue'

const client = useApiClient()
const session = useAuthSession()
const route = useRoute()
const router = useRouter()
const { locale, t } = useI18n()
const isAccessKey = computed(() => session.state.principalType === 'access_key')
const appliedFilters = computed(() => {
  const filters = parseAppliedUsageFilters(route.query)
  return isAccessKey.value ? scopeAccessKeyUsageFilters(filters) : filters
})
const breakdownSort = computed<UsageBreakdownSort>(() =>
  normalizeUsageBreakdownSort(appliedFilters.value.breakdown_sort),
)
const breakdownSortDirection = computed<UsageBreakdownSortDirection>(() =>
  normalizeUsageBreakdownSortDirection(
    appliedFilters.value.breakdown_sort_direction,
    breakdownSort.value,
  ),
)
const routeState = computed(() => parseUsageMonitorState(route.query))
const filterOpen = computed(() => routeState.value.filtersOpen)
const draft = ref<UsageFilterDraft>(createUsageFilterDraft(appliedFilters.value))
const filterErrors = ref<UsageFilterErrors>({})

const groupsQuery = useQuery({
  ...groupOptionsQueryOptions(client, () => !isAccessKey.value),
})
const channelsQuery = useQuery({
  queryKey: controlQueryKeys.channels.list(''),
  queryFn: ({ signal }) => listChannels(client, '', signal),
  enabled: computed(() => !isAccessKey.value),
  staleTime: Number.POSITIVE_INFINITY,
  refetchOnMount: false,
  refetchOnWindowFocus: false,
  refetchOnReconnect: false,
})
const accessKeysQuery = useQuery({
  queryKey: controlQueryKeys.accessKeys.options(),
  queryFn: ({ signal }) => listAccessKeyOptions(client, signal),
  enabled: computed(() => !isAccessKey.value),
  staleTime: Number.POSITIVE_INFINITY,
  refetchOnMount: false,
  refetchOnWindowFocus: false,
  refetchOnReconnect: false,
})
const usageQuery = useQuery(usageQueryOptions(client, appliedFilters))
const report = computed(() => usageQuery.data.value)
const distributionDimension = ref<UsageDistributionDimension>('model')
const distributionMetric = ref<UsageDistributionMetric>('cost')
const distribution = computed(() => {
  const distributions = report.value?.distributions
  if (distributions === undefined) return undefined
  if (isAccessKey.value || distributionDimension.value === 'model') {
    return distributions.model[distributionMetric.value]
  }
  if (distributionDimension.value === 'access_key') {
    return (
      distributions.access_key?.[distributionMetric.value] ??
      distributions.model[distributionMetric.value]
    )
  }
  return (
    distributions.group?.[distributionMetric.value] ?? distributions.model[distributionMetric.value]
  )
})
const {
  initial: initialLoading,
  transition: reportTransition,
  refreshing: reportRefreshing,
} = useCollectionLoading(
  {
    pending: () => usageQuery.isPending.value,
    placeholder: () => usageQuery.isPlaceholderData.value,
    fetching: () => usageQuery.isFetching.value,
    hasData: () => report.value !== undefined,
    itemCount: () =>
      (distribution.value?.items.length ?? 0) + (distribution.value?.other === null ? 0 : 1),
  },
  { fallbackRows: 5 },
)
const usageRefreshing = computed(
  () =>
    reportRefreshing.value ||
    (!isAccessKey.value && groupsQuery.data.value !== undefined && groupsQuery.isFetching.value) ||
    (!isAccessKey.value &&
      channelsQuery.data.value !== undefined &&
      channelsQuery.isFetching.value) ||
    (!isAccessKey.value &&
      accessKeysQuery.data.value !== undefined &&
      accessKeysQuery.isFetching.value),
)
const hasData = computed(() => (report.value?.summary.request_count ?? 0) > 0)
const distributionDimensionOptions = computed(() => [
  { value: 'model', label: t('monitor.usage.distribution.dimensions.model') },
  { value: 'group', label: t('monitor.usage.distribution.dimensions.group') },
  { value: 'access_key', label: t('monitor.usage.distribution.dimensions.accessKey') },
])
const distributionMetricOptions = computed(() => [
  { value: 'requests', label: t('monitor.usage.distribution.metrics.requests') },
  { value: 'tokens', label: t('monitor.usage.distribution.metrics.tokens') },
  { value: 'cost', label: t('monitor.usage.distribution.metrics.cost') },
])
const costChartResolution = 1_000_000_000n
const trendMetricOptions = computed(() => [
  { value: 'tokens', label: t('monitor.usage.trend.metrics.tokens') },
  { value: 'cost', label: t('monitor.usage.trend.metrics.cost') },
])
const trendPresentation = computed(() => {
  if (routeState.value.metric === 'cost') {
    return {
      title: t('monitor.usage.trend.costTitle'),
      description: t('monitor.usage.trend.costDescription'),
      accessibleDescription: t('monitor.usage.trend.costAccessibleDescription'),
      valueLabel: t('monitor.usage.columns.estimatedCost'),
      secondaryLabel: undefined,
    }
  }
  return {
    title: t('monitor.usage.trend.tokensTitle'),
    description: t('monitor.usage.trend.tokensDescription'),
    accessibleDescription: t('monitor.usage.trend.tokensAccessibleDescription'),
    valueLabel: t('monitor.usage.columns.totalTokens'),
    secondaryLabel: t('monitor.usage.tokens.cacheRead'),
  }
})

function formatTrendCost(aggregate: UsageAggregateDto): string {
  return formatEstimatedCost(aggregate.estimated_cost_nano_usd, locale.value)
}

function formatTrendTokens(value: number): string {
  return formatTokens(value, locale.value)
}

function normalizeTrendCost(value: bigint, maximum: bigint): number {
  if (maximum === 0n) return 0
  return Number((value * costChartResolution + maximum / 2n) / maximum)
}

const barTrendSeries = computed<UsageBarDatum[]>(() => {
  const buckets = report.value?.series ?? []
  if (routeState.value.metric === 'tokens') {
    return buckets.map((bucket) => ({
      bucket_start_ms: bucket.bucket_start_ms,
      bucket_end_ms: bucket.bucket_end_ms,
      primary_value: bucket.total_tokens,
      secondary_value: bucket.cache_read_tokens,
      primary_display: formatTrendTokens(bucket.total_tokens),
      secondary_display: formatTrendTokens(bucket.cache_read_tokens),
      details: [
        {
          label: t('monitor.usage.trend.inputTokens'),
          display: formatTrendTokens(inputTokens(bucket)),
        },
        {
          label: t('monitor.usage.trend.outputTokens'),
          display: formatTrendTokens(bucket.output_tokens),
        },
      ],
    }))
  }
  const costs = buckets.map((bucket) => BigInt(bucket.estimated_cost_nano_usd))
  const maximum = costs.reduce((current, value) => (value > current ? value : current), 0n)
  return buckets.map((bucket, index) => ({
    bucket_start_ms: bucket.bucket_start_ms,
    bucket_end_ms: bucket.bucket_end_ms,
    primary_value: normalizeTrendCost(costs[index]!, maximum),
    secondary_value: 0,
    primary_display: formatTrendCost(bucket),
  }))
})

watch(
  [
    () => appliedFilters.value.range,
    () => appliedFilters.value.group_id,
    () => appliedFilters.value.channel_id,
    () => appliedFilters.value.credential_id,
    () => appliedFilters.value.upstream_model,
  ],
  () => {
    draft.value = createUsageFilterDraft(appliedFilters.value)
    filterErrors.value = {}
  },
)

watch(
  () => routeState.value.filtersOpen,
  () => {
    draft.value = createUsageFilterDraft(appliedFilters.value)
    filterErrors.value = {}
  },
)

function rangeLabel(range: UsageRange): string {
  return t(`monitor.usage.filters.ranges.${range}`)
}

function granularityLabel(): string {
  const bucketWidthMS = report.value?.bucket_width_ms
  if (bucketWidthMS === 60 * 60 * 1000) return t('monitor.usage.trend.hourly')
  if (bucketWidthMS === 24 * 60 * 60 * 1000) return t('monitor.usage.trend.daily')
  return t('monitor.usage.trend.everyHours', {
    count: (bucketWidthMS ?? 0) / (60 * 60 * 1000),
  })
}

function formatCost(aggregate: UsageAggregateDto): string {
  return formatEstimatedCost(aggregate.estimated_cost_nano_usd, locale.value)
}

function inputTokens(aggregate: UsageAggregateDto): number {
  return (
    aggregate.uncached_input_tokens +
    aggregate.cache_read_tokens +
    aggregate.cache_write_5m_tokens +
    aggregate.cache_write_1h_tokens +
    aggregate.cache_write_unknown_tokens
  )
}

function updateDraftField(field: keyof UsageFilterDraft, value: string): void {
  draft.value = { ...draft.value, [field]: value }
}

function setFilterOpen(open: boolean): void {
  if (!open) {
    draft.value = createUsageFilterDraft(appliedFilters.value)
    filterErrors.value = {}
  }
  void navigate(appliedFilters.value, { ...routeState.value, filtersOpen: open })
}

function openFilters(): void {
  draft.value = createUsageFilterDraft(appliedFilters.value)
  filterErrors.value = {}
  void navigate(appliedFilters.value, { ...routeState.value, filtersOpen: true })
}

async function applyFilters(): Promise<void> {
  const errors = validateUsageFilterDraft(draft.value)
  filterErrors.value = errors
  if (Object.keys(errors).length > 0) return
  await navigate({
    ...applyUsageFilterDraft(draft.value),
    breakdown_sort: breakdownSort.value,
    breakdown_sort_direction: breakdownSortDirection.value,
  })
}

async function resetFilters(): Promise<void> {
  await navigate({
    range: appliedFilters.value.range,
    breakdown_sort: breakdownSort.value,
    breakdown_sort_direction: breakdownSortDirection.value,
  })
}

async function setBreakdownPage(page: number): Promise<void> {
  await navigate({ ...appliedFilters.value, breakdown_page: page })
}

async function setBreakdownPageSize(pageSize: 20 | 50 | 100): Promise<void> {
  await navigate({ ...appliedFilters.value, breakdown_page: 1, breakdown_page_size: pageSize })
}
async function setBreakdownSort(
  sort: UsageBreakdownSort,
  direction: UsageBreakdownSortDirection,
): Promise<void> {
  await navigate({
    ...appliedFilters.value,
    breakdown_page: 1,
    breakdown_sort: sort,
    breakdown_sort_direction: direction,
  })
}

function updateDistributionDimension(value: string): void {
  if (value !== 'group' && value !== 'model' && value !== 'access_key') return
  if (
    isAccessKey.value ||
    (value === 'group' && report.value?.distributions.group === undefined) ||
    (value === 'access_key' && report.value?.distributions.access_key === undefined)
  )
    return
  distributionDimension.value = value as UsageDistributionDimension
}

function updateDistributionMetric(value: string): void {
  if (value !== 'requests' && value !== 'tokens' && value !== 'cost') return
  distributionMetric.value = value as UsageDistributionMetric
}

async function updateTrendMetric(value: string): Promise<void> {
  if (value !== 'tokens' && value !== 'cost') return
  await navigate(appliedFilters.value, {
    ...routeState.value,
    metric: value as UsageTrendMetric,
  })
}

async function navigate(
  filters: UsageFilters,
  state: UsageMonitorState = {
    filtersOpen: false,
    seriesExpanded: false,
    metric: routeState.value.metric,
  },
): Promise<void> {
  const scopedFilters = isAccessKey.value ? scopeAccessKeyUsageFilters(filters) : filters
  await router.push(monitorLocation(usageMonitorQuery(scopedFilters, state)))
}

function setSeriesExpanded(event: Event): void {
  const expanded = (event.currentTarget as HTMLDetailsElement).open
  if (expanded === routeState.value.seriesExpanded) return
  void navigate(appliedFilters.value, { ...routeState.value, seriesExpanded: expanded })
}

async function refresh(): Promise<void> {
  await Promise.all([
    usageQuery.refetch(),
    ...(!isAccessKey.value
      ? [groupsQuery.refetch(), channelsQuery.refetch(), accessKeysQuery.refetch()]
      : []),
  ])
}

defineExpose({ openFilters, refresh })
</script>

<template>
  <div class="usage-tab">
    <AsyncRefreshIndicator :active="usageRefreshing" :label="t('monitor.usage.loading')" />

    <SkeletonSurface
      v-if="usageQuery.isPending.value || initialLoading || reportTransition"
      variant="dashboard"
      :concealed="usageQuery.isPending.value && !initialLoading"
      :label="t('monitor.usage.loading')"
    />
    <QueryFeedback
      v-else-if="usageQuery.isError.value && !report"
      state="error"
      :message="t('monitor.usage.loadFailed')"
      :retry-label="t('common.retry')"
      @retry="usageQuery.refetch()"
    />

    <template v-else-if="report">
      <QueryFeedback
        v-if="usageQuery.isError.value"
        state="stale"
        :message="t('monitor.usage.stale')"
        :retry-label="t('common.retry')"
        @retry="usageQuery.refetch()"
      />

      <InlineFeedback
        v-if="
          !isAccessKey &&
          (groupsQuery.isError.value ||
            channelsQuery.isError.value ||
            accessKeysQuery.isError.value)
        "
        tone="warning"
      >
        {{ t('monitor.usage.options.partialFailed') }}
      </InlineFeedback>

      <UsageSummary :summary="report.summary" />

      <InlineFeedback
        v-if="
          !isAccessKey &&
          (report.collection_health.dropped_total > 0 ||
            report.collection_health.write_failure_total > 0)
        "
        tone="danger"
        appearance="ledger"
      >
        {{
          t('monitor.usage.process.warning', {
            dropped: formatInteger(report.collection_health.dropped_total, locale),
            failures: formatInteger(report.collection_health.write_failure_total, locale),
          })
        }}
      </InlineFeedback>

      <EmptyState
        v-if="!hasData"
        variant="ledger"
        :title="t('monitor.usage.empty.title')"
        :description="t('monitor.usage.empty.description')"
      >
        <template #icon><Database :size="20" aria-hidden="true" /></template>
      </EmptyState>

      <template v-else>
        <section class="usage-trend-panel" aria-labelledby="usage-trend-title">
          <MonitorSectionHeading
            id="usage-trend-title"
            :title="trendPresentation.title"
            :description="trendPresentation.description"
            :meta="`${rangeLabel(report.range)} · ${granularityLabel()}`"
          >
            <template #actions>
              <SegmentedControl
                :model-value="routeState.metric"
                :label="t('monitor.usage.trend.metrics.label')"
                :options="trendMetricOptions"
                size="compact"
                @update:model-value="updateTrendMetric"
              />
            </template>
          </MonitorSectionHeading>
          <div class="usage-trend-panel__chart">
            <UsageBarChart
              :series="barTrendSeries"
              :title="trendPresentation.title"
              :description="trendPresentation.accessibleDescription"
              :empty-label="t('monitor.usage.trend.empty')"
              :primary-label="trendPresentation.valueLabel"
              :secondary-label="trendPresentation.secondaryLabel"
              :primary-zero-display="
                routeState.metric === 'cost'
                  ? formatEstimatedCost('0', locale)
                  : formatTrendTokens(0)
              "
              :secondary-zero-display="formatTrendTokens(0)"
              :detail-zero-display="formatTrendTokens(0)"
              :range-start="report.from_ms"
              :range-end="report.to_ms"
              :locale="locale"
              :grouped="routeState.metric === 'tokens'"
            />
          </div>
        </section>

        <section class="usage-analysis-section">
          <MonitorSectionHeading
            :title="t('monitor.usage.quality.title')"
            :description="t('monitor.usage.quality.description')"
          />
          <dl class="usage-quality-grid">
            <div>
              <dt>{{ t('monitor.usage.quality.missing') }}</dt>
              <dd>{{ formatInteger(report.summary.usage_missing_count, locale) }}</dd>
            </div>
            <div>
              <dt>{{ t('monitor.usage.quality.partial') }}</dt>
              <dd>{{ formatInteger(report.summary.partial_count, locale) }}</dd>
            </div>
            <div class="usage-quality-grid__danger">
              <dt>{{ t('monitor.usage.quality.unpriced') }}</dt>
              <dd>{{ formatInteger(report.summary.unpriced_request_count, locale) }}</dd>
            </div>
            <div>
              <dt>{{ t('monitor.usage.quality.pricingPartial') }}</dt>
              <dd>{{ formatInteger(report.summary.pricing_partial_count, locale) }}</dd>
            </div>
          </dl>
        </section>

        <section class="usage-distribution-section" aria-labelledby="usage-distribution-title">
          <MonitorSectionHeading
            id="usage-distribution-title"
            :title="t('monitor.usage.distribution.title')"
            :description="t('monitor.usage.distribution.description')"
            :meta="t('monitor.usage.distribution.limit')"
          >
            <template #actions>
              <SegmentedControl
                v-if="!isAccessKey"
                :model-value="distributionDimension"
                :label="t('monitor.usage.distribution.dimensionLabel')"
                :options="distributionDimensionOptions"
                size="compact"
                @update:model-value="updateDistributionDimension"
              />
              <AppSelect
                class="usage-distribution-section__metric-select"
                :model-value="distributionMetric"
                :label="t('monitor.usage.distribution.metricLabel')"
                :options="distributionMetricOptions"
                size="compact"
                @update:model-value="updateDistributionMetric"
              />
            </template>
          </MonitorSectionHeading>

          <UsageDistribution
            v-if="distribution"
            :distribution="distribution"
            :summary="report.summary"
            :groups="groupsQuery.data.value ?? []"
            :channels="channelsQuery.data.value?.items ?? []"
            :access-keys="accessKeysQuery.data.value ?? []"
          />
        </section>

        <section class="usage-breakdown-section" aria-labelledby="usage-breakdown-title">
          <MonitorSectionHeading
            id="usage-breakdown-title"
            :title="t('monitor.usage.breakdown.title')"
            :description="t('monitor.usage.breakdown.description')"
            :meta="
              t('monitor.usage.breakdown.rowCount', {
                count: report.breakdown.pagination.total_items,
              })
            "
          />
          <UsageBreakdownTable
            :breakdown="report.breakdown"
            :groups="groupsQuery.data.value ?? []"
            :channels="channelsQuery.data.value?.items ?? []"
            :sort="breakdownSort"
            :sort-direction="breakdownSortDirection"
            @page="setBreakdownPage"
            @update:page-size="setBreakdownPageSize"
            @sort="setBreakdownSort"
          />
        </section>

        <details
          class="usage-buckets"
          :open="routeState.seriesExpanded"
          @toggle="setSeriesExpanded"
        >
          <summary>{{ t('monitor.usage.series.disclosure') }}</summary>
          <div class="usage-buckets__body">
            <DataTable :caption="t('monitor.usage.series.caption')" appearance="editorial" dense>
              <thead>
                <tr>
                  <th scope="col">{{ t('monitor.usage.columns.window') }}</th>
                  <th scope="col">{{ t('monitor.usage.columns.requests') }}</th>
                  <th scope="col">{{ t('monitor.usage.columns.success') }}</th>
                  <th scope="col">{{ t('monitor.usage.columns.failure') }}</th>
                  <th scope="col">{{ t('monitor.usage.columns.totalTokens') }}</th>
                  <th scope="col">{{ t('monitor.usage.columns.estimatedCost') }}</th>
                  <th scope="col">{{ t('monitor.usage.columns.quality') }}</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="bucket in report.series" :key="bucket.bucket_start_ms">
                  <td><AppDateTime :instant="bucket.bucket_start_ms" :locale="locale" /></td>
                  <td>{{ formatInteger(bucket.request_count, locale) }}</td>
                  <td>{{ formatInteger(bucket.success_count, locale) }}</td>
                  <td>{{ formatInteger(bucket.failure_count, locale) }}</td>
                  <td>{{ formatTokens(bucket.total_tokens, locale) }}</td>
                  <td>{{ formatCost(bucket) }}</td>
                  <td>
                    {{
                      t('monitor.usage.columns.qualityCompact', {
                        missing: formatInteger(bucket.usage_missing_count, locale),
                        partial: formatInteger(bucket.partial_count, locale),
                        unpriced: formatInteger(bucket.unpriced_request_count, locale),
                        pricingPartial: formatInteger(bucket.pricing_partial_count, locale),
                      })
                    }}
                  </td>
                </tr>
              </tbody>
            </DataTable>
          </div>
        </details>
      </template>
    </template>

    <UsageFilterForm
      :open="filterOpen"
      :draft="draft"
      :errors="filterErrors"
      :groups="groupsQuery.data.value ?? []"
      :channels="channelsQuery.data.value?.items ?? []"
      :groups-failed="groupsQuery.isError.value"
      :channels-failed="channelsQuery.isError.value"
      :self-scoped="isAccessKey"
      @update:open="setFilterOpen"
      @update-field="updateDraftField"
      @apply="applyFilters"
      @reset="resetFilters"
    />
  </div>
</template>

<style scoped>
.usage-tab,
.usage-analysis-section,
.usage-distribution-section,
.usage-breakdown-section {
  display: grid;
  min-width: 0;
}

.usage-tab {
  gap: 22px;
}

.usage-analysis-section,
.usage-distribution-section,
.usage-breakdown-section {
  gap: 12px;
}

.usage-distribution-section :deep(.monitor-section-heading) {
  flex-wrap: wrap;
}

.usage-distribution-section__metric-select {
  min-width: 104px;
}

@media (max-width: 680px) {
  .usage-distribution-section :deep(.monitor-section-heading__actions) {
    width: 100%;
    flex-wrap: wrap;
    justify-content: flex-start;
    margin-left: 0;
  }
}

.usage-trend-panel {
  display: grid;
  min-width: 0;
  gap: 12px;
}

.usage-trend-panel :deep(.monitor-section-heading) {
  flex-wrap: wrap;
}

.usage-trend-panel__chart {
  min-width: 0;
  overflow: hidden;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-card);
  background: var(--color-surface);
  padding: 18px 20px 14px;
}

@media (max-width: 620px) {
  .usage-trend-panel :deep(.monitor-section-heading__actions) {
    width: 100%;
    justify-content: flex-end;
    margin-left: 0;
  }
}

.usage-quality-grid {
  display: grid;
  overflow: hidden;
  margin: 0;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-card);
  background: var(--color-border-subtle);
  gap: 1px;
  grid-template-columns: repeat(2, minmax(0, 1fr));
}

.usage-quality-grid > div {
  min-width: 0;
  min-height: 78px;
  background: var(--color-surface);
  padding: 13px 15px;
}

.usage-quality-grid dt {
  display: flex;
  align-items: center;
  gap: 7px;
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
}

.usage-quality-grid dt::before {
  width: 6px;
  height: 6px;
  flex: 0 0 6px;
  border-radius: 50%;
  background: var(--color-warning);
  content: '';
}

.usage-quality-grid__danger dt::before {
  background: var(--color-danger);
}

.usage-quality-grid dd {
  margin: 7px 0 0;
  color: var(--color-text-muted);
  font-family: var(--font-mono);
  font-size: 1.1rem;
  font-variant-numeric: tabular-nums;
  font-weight: 560;
  letter-spacing: -0.035em;
}

.usage-buckets {
  overflow: hidden;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-card);
  background: var(--color-surface);
}

.usage-buckets > summary {
  display: flex;
  min-height: 48px;
  align-items: center;
  justify-content: space-between;
  padding: 0 16px;
  color: var(--color-text-muted);
  cursor: pointer;
  font-size: var(--text-sm);
  font-weight: 600;
  list-style: none;
}

.usage-buckets > summary::-webkit-details-marker {
  display: none;
}

.usage-buckets > summary::after {
  color: var(--color-text-faint);
  content: '＋';
}

.usage-buckets[open] > summary {
  border-bottom: 1px solid var(--color-border-subtle);
}

.usage-buckets[open] > summary::after {
  content: '−';
}

.usage-buckets__body {
  padding: 14px 16px;
}

@media (max-width: 620px) {
  .usage-quality-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .usage-trend-panel__chart {
    padding: 14px 12px 10px;
  }
}
</style>
