// web/src/frontends/classic/features/model-prices/ModelPriceMatrix.vue
<script setup lang="ts">
import { Plus, X } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import AppConfirmDialog from '@/components/ui/AppConfirmDialog.vue'
import AppTextInput from '@/components/ui/AppTextInput.vue'
import IconButton from '@/components/ui/IconButton.vue'
import InlineFeedback from '@/components/ui/InlineFeedback.vue'
import { formatInteger } from '@shared/lib/format'

import {
  modelPriceFields,
  tierDisplayOrder,
  type ModelPriceField,
  type ModelPriceScheduleErrors,
  type ModelPriceScheduleDraft,
} from './model-price-form'

const props = defineProps<{
  modelId: string
  errors: ModelPriceScheduleErrors
  pending: boolean
  failure: string
}>()
const emit = defineEmits<{
  'add-tier': []
  'remove-tier': [key: string]
  'confirm-unpriced': []
}>()
const draft = defineModel<ModelPriceScheduleDraft>('draft', { required: true })
const unpricedConfirmOpen = defineModel<boolean>('unpricedConfirmOpen', { required: true })
const { locale, t } = useI18n()

const tiered = computed(() => draft.value.tiers.length > 0)

/**
 * 新增档位固定追加到末尾，用户填入的阈值可能比上面已有档位更小，
 * 导致编辑区行序与下方按阈值排序的派生说明相互矛盾。失焦时才重排，
 * 避免每次按键都重排导致正在编辑的行跳动。
 */
function reorderTiers(): void {
  draft.value.tiers = [...draft.value.tiers].sort(
    (left, right) => tierDisplayOrder(left.threshold) - tierDisplayOrder(right.threshold),
  )
}

function baseFieldError(field: ModelPriceField): string | undefined {
  const code = props.errors.base[field]
  return code ? t(`modelPrices.matrix.errors.${code}`) : undefined
}

function tierThresholdError(key: string): string | undefined {
  const code = props.errors.tiers[key]?.threshold
  return code ? t(`modelPrices.matrix.errors.threshold_${code}`) : undefined
}

function tierSlotError(key: string, field: ModelPriceField): string | undefined {
  const code = props.errors.tiers[key]?.slots?.[field]
  return code ? t(`modelPrices.matrix.errors.${code}`) : undefined
}

/** 输入框组共享外框，逐格挂错误文案会撑破布局；改为按行汇总去重后展示。 */
function dedupe(messages: (string | undefined)[]): string[] {
  return [...new Set(messages.filter((message): message is string => Boolean(message)))]
}

const baseErrors = computed(() => dedupe(modelPriceFields.map((field) => baseFieldError(field))))

function tierErrors(key: string): string[] {
  const messages = [
    tierThresholdError(key),
    ...modelPriceFields.map((field) => tierSlotError(key, field)),
  ]
  if (props.errors.tiers[key]?.emptyTier === true) {
    messages.push(t('modelPrices.matrix.errors.tier_empty'))
  }
  return dedupe(messages)
}

interface TierRule {
  key: string
  description: string
}

function thresholdDescription(value: string): string {
  const threshold = tierDisplayOrder(value)
  if (Number.isFinite(threshold)) return formatInteger(threshold, locale.value)
  return value.trim() || t('modelPrices.matrix.thresholdNotSet')
}

const tierRules = computed<TierRule[]>(() => {
  return draft.value.tiers.map((tier, index) => ({
    key: tier.key,
    description: t('modelPrices.matrix.tierRule', {
      threshold: thresholdDescription(tier.threshold),
      tier: index + 1,
    }),
  }))
})
</script>

<template>
  <div class="model-price-matrix">
    <InlineFeedback v-if="failure" appearance="ledger" tone="danger">{{ failure }}</InlineFeedback>

    <div class="model-price-matrix__grid" :class="{ 'model-price-matrix__grid--tiered': tiered }">
      <!-- 纯视觉列标签；每个输入的可访问名称由 AppTextInput 自带的 sr-only label 承担。 -->
      <div class="model-price-matrix__row model-price-matrix__row--header" aria-hidden="true">
        <span v-if="tiered">{{ t('modelPrices.matrix.thresholdColumn') }}</span>
        <div class="model-price-matrix__header-cells">
          <span v-for="field in modelPriceFields" :key="field">
            {{ t(`modelPrices.fields.${field}`) }}
          </span>
        </div>
        <span v-if="tiered"></span>
      </div>

      <div class="model-price-matrix__row">
        <div v-if="tiered" class="model-price-group model-price-group--threshold">
          <AppTextInput
            id="model-price-default"
            :model-value="t('modelPrices.matrix.baseRow')"
            :label="t('modelPrices.matrix.baseRow')"
            appearance="surface"
            size="compact"
            readonly
          />
        </div>
        <!-- 一横排为一个输入框组：共享外框，内部竖线分隔，无间隙。 -->
        <div class="model-price-group" role="group" :aria-label="t('modelPrices.matrix.baseRow')">
          <AppTextInput
            v-for="field in modelPriceFields"
            :id="`model-price-base-${field}`"
            :key="field"
            v-model="draft.base[field]"
            :label="t(`modelPrices.fields.${field}`)"
            appearance="surface"
            size="compact"
            monospace
            inputmode="decimal"
            :disabled="pending"
            :invalid="Boolean(baseFieldError(field))"
          />
        </div>
        <!-- 增删都落在同一列：无档位时基础行就是最后一行，由它承载加号。 -->
        <div class="model-price-matrix__actions">
          <IconButton
            v-if="!tiered"
            class="model-price-matrix__add"
            variant="ghost"
            size="xs"
            :disabled="pending"
            :label="t('modelPrices.matrix.addTier')"
            @click="emit('add-tier')"
          >
            <Plus :size="14" aria-hidden="true" />
          </IconButton>
        </div>
      </div>
      <p v-if="baseErrors.length > 0" class="model-price-matrix__error" role="alert">
        {{ baseErrors.join(' · ') }}
      </p>

      <template v-for="(tier, index) in draft.tiers" :key="tier.key">
        <div class="model-price-matrix__row">
          <div class="model-price-group model-price-group--threshold">
            <AppTextInput
              :id="`model-price-tier-${tier.key}-threshold`"
              v-model="tier.threshold"
              :label="t('modelPrices.matrix.thresholdColumn')"
              appearance="surface"
              size="compact"
              monospace
              inputmode="numeric"
              :disabled="pending"
              :invalid="Boolean(tierThresholdError(tier.key))"
              @blur="reorderTiers"
            />
          </div>
          <div
            class="model-price-group"
            role="group"
            :aria-label="tier.threshold.trim() || t('modelPrices.matrix.thresholdColumn')"
          >
            <AppTextInput
              v-for="field in modelPriceFields"
              :id="`model-price-tier-${tier.key}-${field}`"
              :key="field"
              v-model="tier.slots[field]"
              :label="t(`modelPrices.fields.${field}`)"
              appearance="surface"
              size="compact"
              monospace
              inputmode="decimal"
              :disabled="pending"
              :invalid="Boolean(tierSlotError(tier.key, field))"
            />
          </div>
          <div class="model-price-matrix__actions">
            <IconButton
              class="model-price-matrix__remove"
              variant="ghost"
              size="xs"
              :disabled="pending"
              :label="t('modelPrices.matrix.removeTier')"
              @click="emit('remove-tier', tier.key)"
            >
              <X :size="14" aria-hidden="true" />
            </IconButton>
            <IconButton
              v-if="index === draft.tiers.length - 1"
              class="model-price-matrix__add"
              variant="ghost"
              size="xs"
              :disabled="pending"
              :label="t('modelPrices.matrix.addTier')"
              @click="emit('add-tier')"
            >
              <Plus :size="14" aria-hidden="true" />
            </IconButton>
          </div>
        </div>
        <p v-if="tierErrors(tier.key).length > 0" class="model-price-matrix__error" role="alert">
          {{ tierErrors(tier.key).join(' · ') }}
        </p>
      </template>
    </div>

    <div class="model-price-matrix__rules">
      <p class="model-price-matrix__cache-rule">{{ t('modelPrices.matrix.oneHourRule') }}</p>
      <ul v-if="tierRules.length > 0" class="model-price-matrix__tier-rules">
        <li v-for="rule in tierRules" :key="rule.key">{{ rule.description }}</li>
      </ul>
    </div>
  </div>

  <AppConfirmDialog
    appearance="ledger"
    tone="danger"
    :open="unpricedConfirmOpen"
    :title="t('modelPrices.matrix.unpricedConfirm.title')"
    :description="t('modelPrices.matrix.unpricedConfirm.description', { model: modelId })"
    :close-label="t('modelPrices.matrix.unpricedConfirm.close')"
    :cancel-label="t('common.cancel')"
    :confirm-label="t('modelPrices.matrix.unpricedConfirm.confirm')"
    :pending="pending"
    @update:open="unpricedConfirmOpen = $event"
    @confirm="emit('confirm-unpriced')"
  >
    <InlineFeedback appearance="ledger" tone="warning">
      {{ t('modelPrices.matrix.unpricedConfirm.warning') }}
    </InlineFeedback>
  </AppConfirmDialog>
</template>

<style scoped>
.model-price-matrix {
  display: grid;
  min-width: 0;
  gap: var(--space-2-5);
}

.model-price-matrix__grid {
  display: grid;
  min-width: 0;
  gap: var(--space-1-75) var(--space-2);
}

/*
 * 每行外层列结构统一为 [阈值/行标签] [价格组] [增删位]，
 * 表头复用同一套列定义，内部再等分 4 格，确保标签与组内单元格对齐。
 * 增删列常驻，让加号和叉号落在同一竖线上。
 */
.model-price-matrix__row {
  display: grid;
  min-width: 0;
  grid-template-columns: minmax(0, 1fr) var(--control-xs);
  align-items: center;
  gap: var(--space-1-75);
}

.model-price-matrix__grid--tiered .model-price-matrix__row {
  grid-template-columns: 76px minmax(0, 1fr) calc(var(--control-xs) * 2);
}

.model-price-matrix__header-cells {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  /* 对齐 AppTextInput 的 padding-left 与组边框 1px。 */
  padding-left: calc(var(--space-2) + 1px);
}

/* 固定两个槽位：删除永远占第一格，新增永远占第二格，各行按钮才能纵向对齐。 */
.model-price-matrix__actions {
  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: var(--control-xs);
  align-items: center;
  justify-content: start;
}

.model-price-matrix__row--header {
  align-items: end;
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
}

.model-price-group {
  display: grid;
  min-width: 0;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  border: 1px solid var(--color-border-control);
  border-radius: var(--radius-control);
  background: var(--color-surface);
}

.model-price-group:focus-within {
  border-color: var(--color-focus);
  outline: 0;
  box-shadow: var(--focus-ring);
}

.model-price-group--threshold {
  grid-template-columns: minmax(0, 1fr);
}

/* 组内单元格去掉自身边框，仅保留竖线分隔，形成一体化输入框组。 */
.model-price-group :deep(.app-text-input) {
  border: 0;
  border-left: 1px solid var(--color-border-subtle);
  border-radius: 0;
  background: none;
  /* 抽屉只有 480px，四格并排时收紧内边距换取数字可见宽度。 */
  padding-left: var(--space-2);
}

.model-price-group :deep(.app-text-input:first-child) {
  border-left: 0;
}

/* 组合控件统一由外框表达焦点，子输入仅保留单元格分隔线。 */
.model-price-group :deep(.app-text-input[data-input-shell]:focus-within) {
  border-color: var(--color-border-subtle);
  outline: 0;
  box-shadow: none;
}

.model-price-group :deep(.app-text-input--invalid) {
  background: var(--color-danger-bg);
}

.model-price-matrix__error {
  margin: 0;
  color: var(--color-danger);
  font-size: var(--text-label-xs);
}

.model-price-matrix__remove,
.model-price-matrix__add {
  color: var(--color-text-faint);
}

.model-price-matrix__remove:hover:not(:disabled) {
  color: var(--color-danger);
}

.model-price-matrix__add:hover:not(:disabled) {
  color: var(--color-action);
}

.model-price-matrix__rules {
  display: grid;
  gap: var(--space-1);
  font-size: var(--text-label-xs);
}

.model-price-matrix__cache-rule {
  margin: 0;
  color: var(--color-text-muted);
}

.model-price-matrix__tier-rules {
  display: grid;
  gap: var(--space-0-75);
  margin: 0;
  padding: 0;
  color: var(--color-text-faint);
  list-style: none;
}

.model-price-matrix__tier-rules li {
  line-height: 1.55;
}

/* 抽屉在小屏铺满视口，四格并排放不下：阈值与增删占第一行，价格组换到第二行。 */
@media (max-width: 560px) {
  .model-price-matrix__row,
  .model-price-matrix__grid--tiered .model-price-matrix__row {
    grid-template-columns: minmax(0, 1fr) auto;
  }

  .model-price-matrix__row--header {
    display: none;
  }

  .model-price-group {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .model-price-group--threshold {
    grid-template-columns: minmax(0, 1fr);
  }

  .model-price-matrix__grid--tiered
    .model-price-matrix__row
    > .model-price-group:not(.model-price-group--threshold) {
    grid-column: 1 / -1;
    grid-row: 2;
  }

  .model-price-matrix__grid--tiered .model-price-matrix__row > .model-price-group--threshold {
    grid-column: 1;
    grid-row: 1;
  }

  .model-price-matrix__grid--tiered .model-price-matrix__row > .model-price-matrix__actions {
    grid-column: 2;
    grid-row: 1;
  }
}
</style>

// web/src/frontends/astryx/features/models/ModelPriceMatrix.tsx
import * as stylex from '@stylexjs/stylex'
import {
  Button,
  Dialog,
  DialogHeader,
  IconButton,
  Layout,
  LayoutContent,
  LayoutFooter,
  TextInput,
} from '@astryxdesign/core'
import { Plus, TriangleAlert, X } from 'lucide-react'
import { useState } from 'react'
import { useIntl } from 'react-intl'

import {
  modelPriceFields,
  tierDisplayOrder,
  type ModelPriceField,
  type ModelPriceScheduleDraft,
  type ModelPriceScheduleErrors,
} from '@shared/domain/model-prices/model-price-form'
import { formatInteger } from '@shared/lib/format'

import { useT } from '../../app/i18n'
import { decimalInputAttrs, numericInputAttrs } from '../../components/input-attrs'

const MATRIX_NARROW = '@media (max-width: 560px)'

const styles = stylex.create({
  matrix: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-2-5)',
  },
  grid: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-1-75) var(--space-2)',
  },
  row: {
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: {
      default: 'minmax(0, 1fr) var(--control-xs, 32px)',
      [MATRIX_NARROW]: 'minmax(0, 1fr) auto',
    },
    alignItems: 'center',
    gap: 'var(--space-1-75)',
  },
  rowTiered: {
    gridTemplateColumns: {
      default: '76px minmax(0, 1fr) calc(var(--control-xs, 32px) * 2)',
      [MATRIX_NARROW]: 'minmax(0, 1fr) auto',
    },
  },
  headerRow: {
    display: { default: 'grid', [MATRIX_NARROW]: 'none' },
    alignItems: 'end',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
  },
  headerCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    paddingInlineStart: 'calc(var(--space-2) + 1px)',
  },
  group: {
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: {
      default: 'repeat(4, minmax(0, 1fr))',
      [MATRIX_NARROW]: 'repeat(2, minmax(0, 1fr))',
    },
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border-control)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-surface)',
  },
  groupFocused: {
    borderColor: 'var(--color-focus)',
    boxShadow: 'var(--focus-ring)',
  },
  groupThreshold: {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  groupCell: {
    gridColumn: { default: 'auto', [MATRIX_NARROW]: '1 / -1' },
    gridRow: { default: 'auto', [MATRIX_NARROW]: '2' },
  },
  thresholdCell: {
    gridColumn: { default: 'auto', [MATRIX_NARROW]: '1' },
    gridRow: { default: 'auto', [MATRIX_NARROW]: '1' },
  },
  actionsCell: {
    gridColumn: { default: 'auto', [MATRIX_NARROW]: '2' },
    gridRow: { default: 'auto', [MATRIX_NARROW]: '1' },
  },
  actions: {
    display: 'grid',
    gridAutoFlow: 'column',
    gridAutoColumns: 'var(--control-xs, 32px)',
    alignItems: 'center',
    justifyContent: 'start',
  },
  cellInput: {
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  cellInputInvalid: {
    backgroundColor: 'var(--color-danger-bg)',
  },
  cellInputDivider: {
    borderInlineStartWidth: 1,
    borderInlineStartStyle: 'solid',
    borderInlineStartColor: 'var(--color-border-subtle)',
  },
  error: {
    margin: 0,
    color: 'var(--color-danger)',
    fontSize: 'var(--text-label-xs)',
  },
  rules: {
    display: 'grid',
    gap: 'var(--space-1)',
    fontSize: 'var(--text-label-xs)',
  },
  cacheRule: {
    margin: 0,
    color: 'var(--color-text-muted)',
  },
  tierRules: {
    display: 'grid',
    gap: 'var(--space-0-75)',
    margin: 0,
    padding: 0,
    color: 'var(--color-text-faint)',
    listStyle: 'none',
    lineHeight: 1.55,
  },
  failureBanner: {
    borderRadius: 'var(--radius-control, 6px)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-danger)',
    backgroundColor:
      'var(--color-danger-bg, color-mix(in srgb, var(--color-danger) 10%, transparent))',
    padding: '9px 12px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: 'var(--text-meta)',
  },
  dialogWarning: {
    borderRadius: 'var(--radius-control, 6px)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-warning)',
    backgroundColor:
      'var(--color-warning-bg, color-mix(in srgb, var(--color-warning) 12%, transparent))',
    padding: '9px 12px',
    fontSize: 'var(--text-meta)',
  },
})

function dedupe(messages: (string | undefined)[]): string[] {
  return [...new Set(messages.filter((message): message is string => Boolean(message)))]
}

/** 组合控件统一由外框表达焦点,子输入仅保留单元格分隔线(focus-within 等价)。 */
function PriceInputGroup({
  children,
  label,
  xstyles,
}: {
  children: React.ReactNode
  label: string
  xstyles?: (stylex.StyleXStyles | null | undefined | false)[]
}) {
  const [focused, setFocused] = useState(false)
  return (
    <div
      {...stylex.props(styles.group, focused && styles.groupFocused, ...(xstyles ?? []))}
      role="group"
      aria-label={label}
      onFocusCapture={() => setFocused(true)}
      onBlurCapture={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget as Node | null)) {
          setFocused(false)
        }
      }}
    >
      {children}
    </div>
  )
}

export function ModelPriceMatrix({
  modelId,
  draft,
  onDraftChange,
  errors,
  pending,
  failure,
  unpricedConfirmOpen,
  onUnpricedConfirmOpenChange,
  onAddTier,
  onRemoveTier,
  onConfirmUnpriced,
}: {
  modelId: string
  draft: ModelPriceScheduleDraft
  onDraftChange: (next: ModelPriceScheduleDraft) => void
  errors: ModelPriceScheduleErrors
  pending: boolean
  failure: string
  unpricedConfirmOpen: boolean
  onUnpricedConfirmOpenChange: (open: boolean) => void
  onAddTier: () => void
  onRemoveTier: (key: string) => void
  onConfirmUnpriced: () => void
}) {
  const t = useT()
  const intl = useIntl()
  const tiered = draft.tiers.length > 0

  /**
   * 新增档位固定追加到末尾,用户填入的阈值可能比上面已有档位更小,
   * 导致编辑区行序与下方按阈值排序的派生说明相互矛盾。失焦时才重排,
   * 避免每次按键都重排导致正在编辑的行跳动。
   */
  function reorderTiers(): void {
    onDraftChange({
      ...draft,
      tiers: [...draft.tiers].sort(
        (left, right) => tierDisplayOrder(left.threshold) - tierDisplayOrder(right.threshold),
      ),
    })
  }

  const baseFieldError = (field: ModelPriceField): string | undefined => {
    const code = errors.base[field]
    return code ? t(`modelPrices.matrix.errors.${code}`) : undefined
  }
  const tierThresholdError = (key: string): string | undefined => {
    const code = errors.tiers[key]?.threshold
    return code ? t(`modelPrices.matrix.errors.threshold_${code}`) : undefined
  }
  const tierSlotError = (key: string, field: ModelPriceField): string | undefined => {
    const code = errors.tiers[key]?.slots?.[field]
    return code ? t(`modelPrices.matrix.errors.${code}`) : undefined
  }

  const baseErrors = dedupe(modelPriceFields.map((field) => baseFieldError(field)))

  const tierErrors = (key: string): string[] => {
    const messages = [
      tierThresholdError(key),
      ...modelPriceFields.map((field) => tierSlotError(key, field)),
    ]
    if (errors.tiers[key]?.emptyTier === true) {
      messages.push(t('modelPrices.matrix.errors.tier_empty'))
    }
    return dedupe(messages)
  }

  const thresholdDescription = (value: string): string => {
    const threshold = tierDisplayOrder(value)
    if (Number.isFinite(threshold)) return formatInteger(threshold, intl.locale)
    return value.trim() || t('modelPrices.matrix.thresholdNotSet')
  }

  const tierRules = draft.tiers.map((tier, index) => ({
    key: tier.key,
    description: t('modelPrices.matrix.tierRule', {
      threshold: thresholdDescription(tier.threshold),
      tier: index + 1,
    }),
  }))

  return (
    <div {...stylex.props(styles.matrix)}>
      {failure && (
        <div {...stylex.props(styles.failureBanner)} role="alert">
          <TriangleAlert size={13} aria-hidden />
          <span>{failure}</span>
        </div>
      )}

      <div {...stylex.props(styles.grid)}>
        {/* 纯视觉列标签;每个输入的可访问名称由输入自身的 label 承担。 */}
        <div
          {...stylex.props(styles.row, tiered && styles.rowTiered, styles.headerRow)}
          aria-hidden
        >
          {tiered && <span>{t('modelPrices.matrix.thresholdColumn')}</span>}
          <div {...stylex.props(styles.headerCells)}>
            {modelPriceFields.map((field) => (
              <span key={field}>{t(`modelPrices.fields.${field}`)}</span>
            ))}
          </div>
          {tiered && <span />}
        </div>

        <div {...stylex.props(styles.row, tiered && styles.rowTiered)}>
          {tiered && (
            <PriceInputGroup
              label={t('modelPrices.matrix.baseRow')}
              xstyles={[styles.groupThreshold, styles.thresholdCell]}
            >
              <TextInput
                id="model-price-default"
                label={t('modelPrices.matrix.baseRow')}
                isLabelHidden
                size="sm"
                value={t('modelPrices.matrix.baseRow')}
                isReadOnly
                xstyle={styles.cellInput}
              />
            </PriceInputGroup>
          )}
          {/* 一横排为一个输入框组:共享外框,内部竖线分隔,无间隙。 */}
          <PriceInputGroup
            label={t('modelPrices.matrix.baseRow')}
            xstyles={[tiered && styles.groupCell]}
          >
            {modelPriceFields.map((field, index) => (
              <TextInput
                key={field}
                id={`model-price-base-${field}`}
                label={t(`modelPrices.fields.${field}`)}
                isLabelHidden
                size="sm"
                value={draft.base[field]}
                isDisabled={pending}
                status={baseFieldError(field) ? { type: 'error' } : undefined}
                xstyle={[
                  styles.cellInput,
                  index > 0 && styles.cellInputDivider,
                  !!baseFieldError(field) && styles.cellInputInvalid,
                ]}
                {...decimalInputAttrs}
                onChange={(value) =>
                  onDraftChange({ ...draft, base: { ...draft.base, [field]: value } })
                }
              />
            ))}
          </PriceInputGroup>
          {/* 增删都落在同一列:无档位时基础行就是最后一行,由它承载加号。 */}
          <div {...stylex.props(styles.actions, styles.actionsCell)}>
            {!tiered && (
              <IconButton
                variant="ghost"
                size="sm"
                isDisabled={pending}
                label={t('modelPrices.matrix.addTier')}
                icon={<Plus size={14} aria-hidden />}
                onClick={onAddTier}
              />
            )}
          </div>
        </div>
        {baseErrors.length > 0 && (
          <p {...stylex.props(styles.error)} role="alert">
            {baseErrors.join(' · ')}
          </p>
        )}

        {draft.tiers.map((tier, index) => (
          <div key={tier.key}>
            <div {...stylex.props(styles.row, styles.rowTiered)}>
              <PriceInputGroup
                label={t('modelPrices.matrix.thresholdColumn')}
                xstyles={[styles.groupThreshold, styles.thresholdCell]}
              >
                <TextInput
                  id={`model-price-tier-${tier.key}-threshold`}
                  label={t('modelPrices.matrix.thresholdColumn')}
                  isLabelHidden
                  size="sm"
                  value={tier.threshold}
                  isDisabled={pending}
                  status={tierThresholdError(tier.key) ? { type: 'error' } : undefined}
                  xstyle={[
                    styles.cellInput,
                    !!tierThresholdError(tier.key) && styles.cellInputInvalid,
                  ]}
                  {...numericInputAttrs}
                  onChange={(value) =>
                    onDraftChange({
                      ...draft,
                      tiers: draft.tiers.map((item) =>
                        item.key === tier.key ? { ...item, threshold: value } : item,
                      ),
                    })
                  }
                  onBlur={reorderTiers}
                />
              </PriceInputGroup>
              <PriceInputGroup
                label={tier.threshold.trim() || t('modelPrices.matrix.thresholdColumn')}
                xstyles={[styles.groupCell]}
              >
                {modelPriceFields.map((field, fieldIndex) => (
                  <TextInput
                    key={field}
                    id={`model-price-tier-${tier.key}-${field}`}
                    label={t(`modelPrices.fields.${field}`)}
                    isLabelHidden
                    size="sm"
                    value={tier.slots[field]}
                    isDisabled={pending}
                    status={tierSlotError(tier.key, field) ? { type: 'error' } : undefined}
                    xstyle={[
                      styles.cellInput,
                      fieldIndex > 0 && styles.cellInputDivider,
                      !!tierSlotError(tier.key, field) && styles.cellInputInvalid,
                    ]}
                    {...decimalInputAttrs}
                    onChange={(value) =>
                      onDraftChange({
                        ...draft,
                        tiers: draft.tiers.map((item) =>
                          item.key === tier.key
                            ? { ...item, slots: { ...item.slots, [field]: value } }
                            : item,
                        ),
                      })
                    }
                  />
                ))}
              </PriceInputGroup>
              <div {...stylex.props(styles.actions, styles.actionsCell)}>
                <IconButton
                  variant="ghost"
                  size="sm"
                  isDisabled={pending}
                  label={t('modelPrices.matrix.removeTier')}
                  icon={<X size={14} aria-hidden />}
                  onClick={() => onRemoveTier(tier.key)}
                />
                {index === draft.tiers.length - 1 && (
                  <IconButton
                    variant="ghost"
                    size="sm"
                    isDisabled={pending}
                    label={t('modelPrices.matrix.addTier')}
                    icon={<Plus size={14} aria-hidden />}
                    onClick={onAddTier}
                  />
                )}
              </div>
            </div>
            {tierErrors(tier.key).length > 0 && (
              <p {...stylex.props(styles.error)} role="alert">
                {tierErrors(tier.key).join(' · ')}
              </p>
            )}
          </div>
        ))}
      </div>

      <div {...stylex.props(styles.rules)}>
        <p {...stylex.props(styles.cacheRule)}>{t('modelPrices.matrix.oneHourRule')}</p>
        {tierRules.length > 0 && (
          <ul {...stylex.props(styles.tierRules)}>
            {tierRules.map((rule) => (
              <li key={rule.key}>{rule.description}</li>
            ))}
          </ul>
        )}
      </div>

      <Dialog isOpen={unpricedConfirmOpen} onOpenChange={onUnpricedConfirmOpenChange} width={440}>
        <Layout
          header={
            <DialogHeader
              title={t('modelPrices.matrix.unpricedConfirm.title')}
              subtitle={t('modelPrices.matrix.unpricedConfirm.description', { model: modelId })}
              onOpenChange={onUnpricedConfirmOpenChange}
              hasDivider
            />
          }
          content={
            <LayoutContent>
              <div {...stylex.props(styles.dialogWarning)} role="status">
                {t('modelPrices.matrix.unpricedConfirm.warning')}
              </div>
            </LayoutContent>
          }
          footer={
            <LayoutFooter hasDivider>
              <Button
                variant="secondary"
                size="sm"
                label={t('common.cancel')}
                onClick={() => onUnpricedConfirmOpenChange(false)}
              />
              <Button
                variant="destructive"
                size="sm"
                isLoading={pending}
                label={t('modelPrices.matrix.unpricedConfirm.confirm')}
                onClick={onConfirmUnpriced}
              />
            </LayoutFooter>
          }
        />
      </Dialog>
    </div>
  )
}
