// web/src/features/monitor/LogsFilterForm.vue
<script setup lang="ts">
import { ListFilter, X } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { AccessKeyOptionDto, GroupOptionDto } from '@/api/control/types'
import type { ChannelDto } from '@/app/resources/channels'
import AppDateTimeRangePicker from '@/components/ui/AppDateTimeRangePicker.vue'
import AppButton from '@/components/ui/AppButton.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import AppTextInput from '@/components/ui/AppTextInput.vue'

import type { LogFilterDraft, LogFilterErrors } from './log-filters'
import LogsAdvancedFilterDrawer from './LogsAdvancedFilterDrawer.vue'

interface AppliedChip {
  key: string
  label: string
}

const props = defineProps<{
  draft: LogFilterDraft
  errors: LogFilterErrors
  groups: GroupOptionDto[]
  channels: ChannelDto[]
  accessKeys: AccessKeyOptionDto[]
  groupsFailed: boolean
  channelsFailed: boolean
  accessKeysFailed: boolean
  appliedChips: AppliedChip[]
  advancedCount: number
  advancedOpen: boolean
  selfScoped?: boolean
}>()
const emit = defineEmits<{
  'update:advancedOpen': [open: boolean]
  updateField: [field: keyof LogFilterDraft, value: string]
  removeFilter: [key: string]
  apply: []
  reset: []
}>()
const { t } = useI18n()

const groupOptions = computed(() => [
  { value: '', label: t('monitor.logs.filters.anyGroup') },
  ...props.groups.map((group) => ({
    value: String(group.id),
    label: group.name,
  })),
])
const statusOptions = computed(() => [
  { value: '', label: t('monitor.logs.filters.anyStatus') },
  ...(['success', 'error', 'incomplete', 'canceled'] as const).map((value) => ({
    value,
    label: t(`monitor.logs.status.${value}`),
  })),
])
const firstError = computed(() => {
  const key = Object.values(props.errors)[0]
  return key ? t(key) : ''
})

function update(field: keyof LogFilterDraft, value: string): void {
  emit('updateField', field, value)
}

function submit(): void {
  emit('apply')
}

function reset(): void {
  emit('reset')
}

function applyAdvanced(): void {
  emit('apply')
}
</script>

<template>
  <form class="logs-filter" :aria-label="t('monitor.logs.filters.label')" @submit.prevent="submit">
    <div v-if="appliedChips.length" class="logs-filter__chips">
      <span class="logs-filter__chips-label">{{ t('monitor.logs.filters.applied') }}</span>
      <template v-for="chip in appliedChips" :key="chip.key">
        <span v-if="chip.key === 'time'" class="logs-filter__chip logs-filter__chip--fixed">
          {{ chip.label }}
        </span>
        <button
          v-else
          type="button"
          class="logs-filter__chip"
          :aria-label="t('monitor.logs.filters.remove', { value: chip.label })"
          @click="emit('removeFilter', chip.key)"
        >
          <span>{{ chip.label }}</span>
          <X :size="12" aria-hidden="true" />
        </button>
      </template>
    </div>

    <div class="logs-filter__row">
      <AppDateTimeRangePicker
        :from="draft.from"
        :to="draft.to"
        :label="t('monitor.logs.filters.timeRange')"
        :from-label="t('monitor.logs.filters.from')"
        :to-label="t('monitor.logs.filters.to')"
        :timezone-label="t('monitor.logs.filters.timezone')"
        :apply-label="t('monitor.logs.filters.apply')"
        :from-error="errors.from ? t(errors.from) : undefined"
        :to-error="errors.to ? t(errors.to) : undefined"
        @update:from="update('from', $event)"
        @update:to="update('to', $event)"
        @apply="submit"
      />

      <AppSelect
        v-if="!selfScoped"
        class="logs-filter__group"
        :model-value="draft.group_id"
        :label="t('monitor.logs.filters.group')"
        :options="groupOptions"
        size="compact"
        :disabled="groupsFailed"
        @update:model-value="update('group_id', $event)"
      />
      <span class="logs-filter__model">
        <AppTextInput
          :model-value="draft.client_model"
          :label="t('monitor.logs.filters.clientModel')"
          :placeholder="t('monitor.logs.filters.clientModel')"
          :invalid="Boolean(errors.client_model)"
          :described-by="errors.client_model ? 'logs-filter-error' : undefined"
          size="compact"
          data-1p-ignore="true"
          data-lpignore="true"
          @update:model-value="update('client_model', $event)"
        />
      </span>
      <AppSelect
        class="logs-filter__status"
        :model-value="draft.status"
        :label="t('monitor.logs.filters.status')"
        :options="statusOptions"
        size="compact"
        @update:model-value="update('status', $event)"
      />
      <AppButton variant="secondary" size="compact" @click="emit('update:advancedOpen', true)">
        <ListFilter :size="14" aria-hidden="true" />
        {{ t('monitor.logs.filters.more') }}
        <span v-if="advancedCount" class="logs-filter__count">{{ advancedCount }}</span>
      </AppButton>
      <AppButton type="submit" size="compact">{{ t('monitor.logs.filters.apply') }}</AppButton>
      <AppButton variant="secondary" size="compact" @click="reset">
        {{ t('monitor.logs.filters.reset') }}
      </AppButton>
    </div>

    <p v-if="firstError" id="logs-filter-error" class="logs-filter__error" role="alert">
      {{ firstError }}
    </p>
  </form>

  <LogsAdvancedFilterDrawer
    :open="advancedOpen"
    :draft="draft"
    :errors="errors"
    :access-keys="accessKeys"
    :channels="channels"
    :access-keys-failed="accessKeysFailed"
    :channels-failed="channelsFailed"
    :self-scoped="selfScoped"
    @update-field="update"
    @update:open="emit('update:advancedOpen', $event)"
    @apply="applyAdvanced"
    @reset="reset"
  />
</template>

<style scoped>
.logs-filter {
  display: grid;
  min-width: 0;
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-card);
  background: var(--color-surface-sunken);
}

.logs-filter__chips,
.logs-filter__row {
  display: flex;
  min-width: 0;
  align-items: center;
  gap: 8px;
}

.logs-filter__chips {
  flex-wrap: wrap;
  border-bottom: 1px solid var(--color-border-subtle);
  padding: 8px 10px;
}

.logs-filter__chips-label {
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
}

.logs-filter__chip {
  display: inline-flex;
  min-height: 24px;
  align-items: center;
  gap: 5px;
  border: 1px solid var(--color-border-control);
  border-radius: 999px;
  background: var(--color-surface);
  color: var(--color-text-muted);
  padding: 2px 8px;
  font: inherit;
  font-size: var(--text-label-xs);
  cursor: pointer;
}

.logs-filter__chip:hover {
  border-color: var(--color-text-faint);
  color: var(--color-text);
}

.logs-filter__chip--fixed {
  cursor: default;
}

.logs-filter__chip--fixed:hover {
  border-color: var(--color-border-control);
  color: var(--color-text-muted);
}

.logs-filter__row {
  padding: 10px;
}

.logs-filter__group {
  width: 150px;
}

.logs-filter__model {
  display: block;
  width: auto;
  min-width: 130px;
  flex: 1 1 180px;
}

.logs-filter__model :deep(.app-text-input) {
  width: 100%;
}

.logs-filter__status {
  width: 108px;
}

.logs-filter__group :deep(.app-select__trigger),
.logs-filter__status :deep(.app-select__trigger) {
  width: 100%;
}

.logs-filter__count {
  display: inline-flex;
  min-width: 18px;
  height: 18px;
  align-items: center;
  justify-content: center;
  border-radius: 999px;
  background: var(--color-action-soft);
  color: var(--color-action);
  font-size: 11px;
}

.logs-filter__error {
  margin: -2px 10px 8px;
  color: var(--color-danger);
  font-size: var(--text-label-xs);
}

@media (max-width: 1120px) {
  .logs-filter__row {
    flex-wrap: wrap;
  }
}

@media (max-width: 860px) {
  .logs-filter__row > :deep(.app-button),
  .logs-filter__row > :deep(.app-select__trigger) {
    min-height: var(--touch-target);
  }
}

@media (max-width: 560px) {
  .logs-filter__row {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }

  .logs-filter__row > :deep(.app-popover),
  .logs-filter__group,
  .logs-filter__model,
  .logs-filter__status {
    width: 100%;
    grid-column: 1 / -1;
  }
}
</style>

// web/src/frontends/astryx/features/monitor/LogsFilterForm.tsx
import * as stylex from '@stylexjs/stylex'
import { Button, Selector, TextInput } from '@astryxdesign/core'
import { ListFilter, X } from 'lucide-react'
import { useMemo, type FormEvent, type JSX } from 'react'

import type { ChannelDto } from '@shared/control/resources/channels'
import type { AccessKeyOptionDto, GroupOptionDto } from '@shared/control/types'
import {
  requestLogStatuses,
  type LogFilterDraft,
  type LogFilterErrors,
} from '@shared/domain/monitor/log-filters'
import type { MessageId } from '@shared/i18n/message-ids'
import {
  currentTimeZone,
  timeRanges,
  localDateTimeInput,
  resolveDateTimePreset,
  type TimeRange,
} from '@shared/lib/time'

import { useT } from '../../app/i18n'
import { plainTextInputAttrs } from '../../components/input-attrs'
import { LogsAdvancedFilterDrawer } from './LogsAdvancedFilterDrawer'

// The control row wraps when needed and drops to a two-column grid
// (controls span full width) at 560px. The <=860px touch-target bump on buttons is covered theme-wide by
// the gptload theme adaptation (width below md=861).

const NARROW = '@media (max-width: 560px)'

const styles = stylex.create({
  // Classic .logs-filter — sunken card shell around the bar.
  form: {
    display: 'grid',
    minWidth: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border-subtle)',
    borderRadius: 'var(--radius-card)',
    backgroundColor: 'var(--color-surface-sunken)',
  },
  chips: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 'var(--space-2)',
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    paddingBlock: 'var(--space-2)',
    paddingInline: 'var(--space-2-5)',
  },
  chipsLabel: {
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
  },
  // Classic .logs-filter__chip — pill button with a trailing remove icon.
  chip: {
    display: 'inline-flex',
    minHeight: 24,
    alignItems: 'center',
    gap: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: 'var(--color-border-control)',
      ':hover': 'var(--color-text-faint)',
    },
    borderRadius: 999,
    backgroundColor: 'var(--color-surface)',
    color: {
      default: 'var(--color-text-muted)',
      ':hover': 'var(--color-text)',
    },
    paddingBlock: 2,
    paddingInline: 'var(--space-2)',
    fontSize: 'var(--text-label-xs)',
    cursor: 'pointer',
  },
  row: {
    display: {
      default: 'flex',
      [NARROW]: 'grid',
    },
    gridTemplateColumns: {
      default: 'none',
      [NARROW]: 'repeat(2, minmax(0, 1fr))',
    },
    minWidth: 0,
    alignItems: {
      default: 'center',
      [NARROW]: 'stretch',
    },
    flexWrap: 'wrap',
    gap: 'var(--space-2)',
    padding: 'var(--space-2-5)',
  },

  // Field wrappers carry the classic fixed/flex widths; controls fill them
  // via width="100%". At <=560px each spans the full two-column grid row.
  fieldGroup: {
    display: 'block',
    minWidth: 0,
    width: {
      default: 150,
      [NARROW]: '100%',
    },
    gridColumn: {
      default: 'auto',
      [NARROW]: '1 / -1',
    },
  },
  fieldModel: {
    display: 'block',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 180,
    minWidth: {
      default: 130,
      [NARROW]: 0,
    },
    width: {
      default: 'auto',
      [NARROW]: '100%',
    },
    gridColumn: {
      default: 'auto',
      [NARROW]: '1 / -1',
    },
  },
  fieldStatus: {
    display: 'block',
    minWidth: 0,
    width: {
      default: 108,
      [NARROW]: '100%',
    },
    gridColumn: {
      default: 'auto',
      [NARROW]: '1 / -1',
    },
  },
  // Classic .logs-filter__count — the badge inside the "More filters" button.
  count: {
    display: 'inline-flex',
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: 'var(--color-action-soft)',
    color: 'var(--color-action)',
    fontSize: 11,
  },
  // Presets keep their intrinsic labels and wrap instead of shrinking.
  presets: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 2,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingBlock: 'var(--space-1-75)',
    paddingInline: 'var(--space-2-5)',
  },
  preset: {
    flexShrink: 0,
  },
  timezone: {
    marginInlineStart: 'auto',
    paddingInlineStart: 'var(--space-2)',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
    whiteSpace: 'nowrap',
  },
  error: {
    marginTop: -2,
    marginBottom: 'var(--space-2)',
    marginInline: 'var(--space-2-5)',
    color: 'var(--color-danger)',
    fontSize: 'var(--text-label-xs)',
  },
})

// Classic picker shortcut behaviour: presets only update the draft — Apply
// still validates and commits. Two field writes mirror the classic
// `update:from`/`update:to` emit pair (the parent applies them through
// functional state updates). Module scope keeps the `Date.now()` read out of
// render scope (react-hooks/purity).
function selectPreset(
  preset: TimeRange,
  updateField: (field: keyof LogFilterDraft, value: string) => void,
): void {
  const range = resolveDateTimePreset(preset, Math.floor(Date.now() / 1000) * 1000)
  updateField('from', localDateTimeInput(range.from_ms))
  updateField('to', localDateTimeInput(range.to_ms))
}

export interface AppliedChip {
  key: string
  label: string
}

export interface LogsFilterFormProps {
  draft: LogFilterDraft
  errors: LogFilterErrors
  groups: GroupOptionDto[]
  channels: ChannelDto[]
  accessKeys: AccessKeyOptionDto[]
  groupsFailed: boolean
  channelsFailed: boolean
  accessKeysFailed: boolean
  appliedChips: AppliedChip[]
  advancedCount: number
  advancedOpen: boolean
  onAdvancedOpenChange: (open: boolean) => void
  onUpdateField: (field: keyof LogFilterDraft, value: string) => void
  onRemoveFilter: (key: string) => void
  onApply: () => void
  onReset: () => void
  /**
   * Classic `selfScoped` (access-key session view): hides the Group selector
   * and swaps the client-model Selector for a free-text input; also forwarded
   * to the advanced drawer, which drops the fields a scoped principal cannot
   * filter on.
   */
  selfScoped?: boolean
}

/**
 * Quick request-log filter bar — classic LogsFilterForm.vue. The
 * Time presets update the draft and Apply commits the range. SearchableSelect maps
 * to Selector hasSearch; AppSelect to Selector; compact size to `sm`. DS
 * field labels stay hidden (`isLabelHidden`) to keep the classic single-bar
 * density — each `label` still supplies the accessible name. Failure flags
 * only disable their inputs (the single host-level InlineFeedback carries the
 * notice, same as classic) and the first draft error keeps the classic
 * `role="alert"` summary line.
 */
export function LogsFilterForm({
  draft,
  errors,
  groups,
  channels,
  accessKeys,
  groupsFailed,
  channelsFailed,
  accessKeysFailed,
  appliedChips,
  advancedCount,
  advancedOpen,
  onAdvancedOpenChange,
  onUpdateField,
  onRemoveFilter,
  onApply,
  onReset,
  selfScoped,
}: LogsFilterFormProps): JSX.Element {
  const t = useT()
  const timezone = useMemo(() => currentTimeZone(), [])

  function groupOptions() {
    return [
      { value: '', label: t('monitor.logs.filters.anyGroup') },
      ...groups.map((group) => ({
        value: String(group.id),
        label: group.name,
      })),
    ]
  }

  // Client-model filtering keeps the classic semantics: options come from the
  // declared models of the group catalog, exact match; a draft value absent
  // from the catalog is appended so it stays selectable.
  function clientModelOptions() {
    const models = [...new Set(groups.flatMap((group) => group.models))].sort((a, b) =>
      a.localeCompare(b),
    )
    const options = [
      { value: '', label: t('monitor.logs.filters.anyClientModel') },
      ...models.map((model) => ({ value: model, label: model })),
    ]
    const pending = draft.client_model
    if (pending !== '' && !models.includes(pending)) {
      options.push({ value: pending, label: pending })
    }
    return options
  }

  function statusOptions() {
    return [
      { value: '', label: t('monitor.logs.filters.anyStatus') },
      ...requestLogStatuses.map((value) => ({
        value,
        label: t(`monitor.logs.status.${value}` as MessageId),
      })),
    ]
  }

  const firstErrorKey = Object.values(errors)[0]

  function submit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault()
    onApply()
  }

  return (
    <>
      <form
        {...stylex.props(styles.form)}
        aria-label={t('monitor.logs.filters.label')}
        onSubmit={submit}
      >
        {appliedChips.length > 0 && (
          <div {...stylex.props(styles.chips)}>
            <span {...stylex.props(styles.chipsLabel)}>{t('monitor.logs.filters.applied')}</span>
            {appliedChips.map((chip) => (
              <button
                key={chip.key}
                type="button"
                {...stylex.props(styles.chip)}
                aria-label={t('monitor.logs.filters.remove', { value: chip.label })}
                onClick={() => onRemoveFilter(chip.key)}
              >
                <span>{chip.label}</span>
                <X size={12} aria-hidden="true" />
              </button>
            ))}
          </div>
        )}

        <div {...stylex.props(styles.row)}>
          {selfScoped !== true && (
            <span {...stylex.props(styles.fieldGroup)}>
              <Selector
                label={t('monitor.logs.filters.group')}
                isLabelHidden
                size="sm"
                width="100%"
                hasSearch
                searchPlaceholder={t('monitor.logs.filters.searchGroups')}
                emptyText={t('monitor.logs.filters.noMatches')}
                emptySearchText={t('monitor.logs.filters.noMatches')}
                options={groupOptions()}
                value={draft.group_id}
                onChange={(value) => onUpdateField('group_id', value)}
                isDisabled={groupsFailed}
              />
            </span>
          )}
          <span {...stylex.props(styles.fieldModel)}>
            {selfScoped === true ? (
              <TextInput
                label={t('monitor.logs.filters.clientModel')}
                isLabelHidden
                size="sm"
                width="100%"
                value={draft.client_model}
                onChange={(value) => onUpdateField('client_model', value)}
                placeholder={t('monitor.logs.filters.clientModel')}
                status={
                  errors.client_model !== undefined && errors.client_model !== ''
                    ? { type: 'error' }
                    : undefined
                }
                aria-describedby={
                  errors.client_model !== undefined && errors.client_model !== ''
                    ? 'logs-filter-error'
                    : undefined
                }
                data-1p-ignore="true"
                data-lpignore="true"
                {...plainTextInputAttrs}
              />
            ) : (
              <Selector
                label={t('monitor.logs.filters.clientModel')}
                isLabelHidden
                size="sm"
                width="100%"
                hasSearch
                searchPlaceholder={t('monitor.logs.filters.searchClientModels')}
                emptyText={t('monitor.logs.filters.noMatches')}
                emptySearchText={t('monitor.logs.filters.noMatches')}
                options={clientModelOptions()}
                value={draft.client_model}
                onChange={(value) => onUpdateField('client_model', value)}
                isDisabled={groupsFailed}
                status={
                  errors.client_model !== undefined && errors.client_model !== ''
                    ? { type: 'error' }
                    : undefined
                }
              />
            )}
          </span>
          <span {...stylex.props(styles.fieldStatus)}>
            <Selector
              label={t('monitor.logs.filters.status')}
              isLabelHidden
              size="sm"
              width="100%"
              options={statusOptions()}
              value={draft.status}
              onChange={(value) => onUpdateField('status', value)}
            />
          </span>
          <Button
            variant="secondary"
            size="sm"
            icon={<ListFilter size={14} aria-hidden="true" />}
            label={t('monitor.logs.filters.more')}
            onClick={() => onAdvancedOpenChange(true)}
            endContent={
              advancedCount > 0 ? (
                <span {...stylex.props(styles.count)}>{advancedCount}</span>
              ) : undefined
            }
          />
          <Button
            type="submit"
            variant="primary"
            size="sm"
            label={t('monitor.logs.filters.apply')}
          />
          <Button
            variant="secondary"
            size="sm"
            label={t('monitor.logs.filters.reset')}
            onClick={onReset}
          />
        </div>

        <div
          {...stylex.props(styles.presets)}
          role="group"
          aria-label={t('monitor.logs.filters.quickRanges')}
        >
          {timeRanges.map((preset) => (
            <Button
              key={preset}
              type="button"
              variant="ghost"
              size="sm"
              label={t(`monitor.logs.filters.quick.${preset}` as MessageId)}
              xstyle={styles.preset}
              onClick={() => selectPreset(preset, onUpdateField)}
            />
          ))}
          <span {...stylex.props(styles.timezone)}>
            {t('monitor.logs.filters.timezone')} · {timezone}
          </span>
        </div>

        {firstErrorKey !== undefined && firstErrorKey !== '' && (
          <p id="logs-filter-error" {...stylex.props(styles.error)} role="alert">
            {t(firstErrorKey as MessageId)}
          </p>
        )}
      </form>

      <LogsAdvancedFilterDrawer
        open={advancedOpen}
        draft={draft}
        errors={errors}
        accessKeys={accessKeys}
        channels={channels}
        accessKeysFailed={accessKeysFailed}
        channelsFailed={channelsFailed}
        onOpenChange={onAdvancedOpenChange}
        onUpdateField={onUpdateField}
        onApply={onApply}
        onReset={onReset}
        selfScoped={selfScoped}
      />
    </>
  )
}
