// web/src/frontends/classic/features/monitor/SchedulePanel.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'

import { useApiClient } from '@shared/http/client-context'
import type { ModelProbeTargetDto } from '@/app/resources/model-probe'
import { logsLocation } from '@/app/route-locations'
import {
  modelRouteScheduleDetailQueryOptions,
  modelRouteScheduleIndexQueryOptions,
  type ModelRouteScheduleIndexItemDto,
} from '@/app/resources/model-route-schedule'
import AppSelect from '@/components/ui/AppSelect.vue'
import QueryFeedback from '@/components/ui/QueryFeedback.vue'
import ModelProbeDialog from '@/features/models/ModelProbeDialog.vue'
import { useModelProbe } from '@/features/models/use-model-probe'

import { type ScheduleDrafts, type ScheduleMode } from './monitor-route'
import SchedulePanelDetail, { type SchedulePanelDetailLabels } from './SchedulePanelDetail.vue'

export interface SchedulePanelLabels {
  model: string
  mode: string
  selectModel: string
  loadingOptions: string
  contextRequired: string
  kicker?: string
  contextReady?: string
  context?: string
  retry?: string
  indexFailed?: string
  detailFailed?: string
  modeLabels?: Partial<Record<ScheduleMode, string>>
  detail?: Partial<SchedulePanelDetailLabels>
}

const props = withDefaults(
  defineProps<{
    externalModel?: string
    mode?: ScheduleMode
    selectedRow?: string
    sourceGroupId?: number
    drafts?: ScheduleDrafts
    labels?: Partial<SchedulePanelLabels>
    locale?: string
  }>(),
  {
    externalModel: '',
    mode: 'all',
    selectedRow: undefined,
    sourceGroupId: undefined,
    drafts: () => ({}),
    labels: () => ({}),
    locale: 'en-US',
  },
)
const emit = defineEmits<{
  'change-context': [context: { externalModel?: string; mode: ScheduleMode }]
  'draft-change': [drafts: ScheduleDrafts]
  'row-change': [row: string | undefined]
  refresh: []
  saved: [snapshotRevision: number]
  recovered: [groupId: number, entryId: string]
}>()

const client = useApiClient()
const selectedModel = ref(props.externalModel)
const selectedMode = ref<ScheduleMode>(props.mode)
const indexQuery = useQuery(modelRouteScheduleIndexQueryOptions(client))
const indexItems = computed<ModelRouteScheduleIndexItemDto[]>(
  () => indexQuery.data.value?.items ?? [],
)
const selectedIndexItem = computed(() =>
  indexItems.value.find(({ external_model }) => external_model === selectedModel.value),
)
const detailRequest = computed(() => {
  const indexItem = selectedIndexItem.value
  if (!indexItem) return undefined
  return {
    protocol: indexItem.protocol,
    external_model: selectedModel.value,
    operation: indexItem.operation,
  }
})
const detailQuery = useQuery(modelRouteScheduleDetailQueryOptions(client, detailRequest))
const modelOptions = computed(() => [
  { value: '', label: text('selectModel') },
  ...indexItems.value.map((item) => ({ value: item.external_model, label: item.external_model })),
])
const modeOptions = computed(() =>
  (['all', 'primary', 'fallback'] as const).map((mode) => ({
    value: mode,
    label: props.labels.modeLabels?.[mode] ?? mode,
  })),
)
const indexError = computed(() =>
  indexQuery.error.value ? errorMessage(indexQuery.error.value, text('indexFailed')) : '',
)
const detailError = computed(() =>
  detailQuery.error.value ? errorMessage(detailQuery.error.value, text('detailFailed')) : '',
)

const text = (key: keyof SchedulePanelLabels): string => {
  const value = props.labels[key]
  return typeof value === 'string' ? value : ''
}

watch(
  () => props.externalModel,
  (value) => {
    selectedModel.value = value ?? ''
  },
)
watch(
  () => props.mode,
  (value) => {
    selectedMode.value = value
  },
)
function errorMessage(error: unknown, fallback: string): string {
  return error instanceof Error && error.message ? error.message : fallback
}

function commitContext(): void {
  emit('change-context', {
    externalModel: selectedModel.value || undefined,
    mode: selectedMode.value,
  })
}

function setModel(value: string): void {
  selectedModel.value = value
  commitContext()
}

function setMode(value: string): void {
  if (value !== 'all' && value !== 'primary' && value !== 'fallback') return
  selectedMode.value = value
  commitContext()
}

async function refreshIndex(): Promise<void> {
  await indexQuery.refetch()
  emit('refresh')
}

async function refreshDetail(): Promise<void> {
  if (detailRequest.value) await detailQuery.refetch()
  await indexQuery.refetch()
  emit('refresh')
}

async function refreshAll(): Promise<void> {
  await Promise.all([indexQuery.refetch(), detailQuery.refetch()])
  emit('refresh')
}

async function onSaved(revision: number): Promise<void> {
  emit('saved', revision)
  await refreshAll()
}

async function onRecovered(groupID: number, entryID: string): Promise<void> {
  emit('recovered', groupID, entryID)
  await refreshAll()
}

const router = useRouter()
const {
  open: probeOpen,
  pending: probePending,
  failed: probeFailed,
  stopped: probeStopped,
  results: probeResults,
  disabledGroupIds: probeDisabledGroupIds,
  total: probeTotal,
  completed: probeCompleted,
  start: startProbe,
  stop: stopProbe,
  close: closeProbe,
} = useModelProbe()

function probeRow(groupID: number, modelID: string, disabled: boolean): void {
  void startProbe([{ group_id: groupID, model: modelID }], {
    disabledGroupIds: disabled ? [groupID] : [],
  })
}

function probeRows(targets: ModelProbeTargetDto[], disabledGroupIds: number[]): void {
  void startProbe(targets, { disabledGroupIds })
}

function handleProbeOpen(value: boolean): void {
  if (!value) closeProbe()
}

function viewProbeLog(logID: string): void {
  void router.push(logsLocation({ selected_request_id: logID }))
}
</script>

<template>
  <section class="schedule-panel" :aria-label="text('model')">
    <div class="schedule-panel__filters" :aria-label="text('context')">
      <label>
        <span>{{ text('mode') }}</span>
        <AppSelect
          :model-value="selectedMode"
          :label="text('mode')"
          :options="modeOptions"
          size="compact"
          @update:model-value="setMode"
        />
      </label>
      <label>
        <span>{{ text('model') }}</span>
        <AppSelect
          :model-value="selectedModel"
          :label="text('model')"
          :options="modelOptions"
          :disabled="indexQuery.isPending.value || indexQuery.isError.value"
          size="compact"
          @update:model-value="setModel"
        />
      </label>
    </div>

    <QueryFeedback
      v-if="indexQuery.isPending.value"
      state="loading"
      :message="text('loadingOptions')"
    />
    <QueryFeedback
      v-else-if="indexError"
      state="error"
      :message="indexError"
      :retry-label="text('retry')"
      @retry="refreshIndex"
    />

    <SchedulePanelDetail
      :detail="detailQuery.data.value"
      :loading="
        detailQuery.isPending.value &&
        detailQuery.data.value === undefined &&
        Boolean(detailRequest)
      "
      :error="detailRequest && detailQuery.data.value === undefined ? detailError : ''"
      :stale="detailQuery.isRefetchError.value"
      :locale="locale"
      :mode="selectedMode"
      :selected-row="selectedRow"
      :source-group-id="sourceGroupId"
      :drafts="drafts"
      :labels="labels?.detail"
      @refresh="refreshDetail"
      @saved="onSaved"
      @recovered="onRecovered"
      @probe="probeRow"
      @probe-all="probeRows"
      @draft-change="emit('draft-change', $event)"
      @row-change="emit('row-change', $event)"
    />
    <ModelProbeDialog
      :open="probeOpen"
      :pending="probePending"
      :failed="probeFailed"
      :stopped="probeStopped"
      :results="probeResults"
      :disabled-group-ids="probeDisabledGroupIds"
      :total="probeTotal"
      :completed="probeCompleted"
      :applying="true"
      :hide-group-controls="true"
      @update:open="handleProbeOpen"
      @stop="stopProbe"
      @view-log="viewProbeLog"
    />
  </section>
</template>

<style scoped>
.schedule-panel {
  display: grid;
  min-width: 0;
  gap: var(--space-4);
}
/* 由独立页面壳控制满宽卡片，不再依赖 MonitorView 的 tab 页面 class。 */
:global(.schedule-page.ledger-sheet--padded) {
  width: min(calc(100% + var(--stage-padding-inline) * 2), var(--content-max));
  margin-inline: calc(0px - var(--stage-padding-inline));
}
.schedule-panel__filters {
  display: grid;
  grid-template-columns: minmax(150px, 0.5fr) minmax(220px, 1fr);
  gap: var(--space-3);
  max-width: 620px;
}
.schedule-panel__filters label {
  display: grid;
  min-width: 0;
  gap: 5px;
  color: var(--color-text-muted);
  font-size: var(--text-meta);
  font-weight: 650;
}
.schedule-panel__filters label :deep(.app-select__trigger) {
  width: 100%;
}
@media (max-width: 860px) {
  :global(.schedule-page.ledger-sheet--padded) {
    width: calc(100% + var(--stage-padding-inline-compact) * 2);
    margin-inline: calc(0px - var(--stage-padding-inline-compact));
  }
}
@media (max-width: 620px) {
  .schedule-panel__filters {
    grid-template-columns: 1fr;
  }
}
</style>

// web/src/frontends/astryx/features/monitor/SchedulePanel.tsx
import * as stylex from '@stylexjs/stylex'
import { Banner, Button, Selector, Skeleton } from '@astryxdesign/core'
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'
import { useState } from 'react'

import type { ModelProbeTargetDto } from '@shared/control/resources/model-probe'
import {
  modelRouteScheduleDetailQueryOptions,
  modelRouteScheduleIndexQueryOptions,
  type ModelRouteScheduleIndexItemDto,
} from '@shared/control/resources/model-route-schedule'
import { pagePath } from '@shared/routing/page-routes'
import type { ScheduleDrafts } from '@shared/routing/monitor-route'

import { useAppServices } from '../../app/services'
import { ModelProbeDialog } from '../models/ModelProbeDialog'
import { useModelProbe } from '../models/use-model-probe'
import {
  SchedulePanelDetail,
  type SchedulePanelDetailLabels,
} from './SchedulePanelDetail'

export interface SchedulePanelLabels {
  model: string
  selectModel: string
  loadingOptions: string
  contextRequired: string
  kicker?: string
  contextReady?: string
  context?: string
  retry?: string
  indexFailed?: string
  detailFailed?: string
  detail?: Partial<SchedulePanelDetailLabels>
}

const styles = stylex.create({
  panel: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-4)',
  },
  filters: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(150px, 0.5fr) minmax(220px, 1fr)',
      '@media (max-width: 620px)': '1fr',
    },
    gap: 'var(--space-3)',
    maxWidth: '620px',
  },
  field: {
    display: 'grid',
    minWidth: 0,
    gap: '5px',
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-meta)',
    fontWeight: 650,
  },
})

export interface SchedulePanelProps {
  externalModel?: string
  selectedRow?: string
  sourceGroupId?: number
  drafts?: ScheduleDrafts
  labels?: Partial<SchedulePanelLabels>
  locale?: string
  onChangeContext(context: { externalModel?: string }): void
  onDraftChange(drafts: ScheduleDrafts): void
  onRowChange(row: string | undefined): void
  onRefresh(): void
  onSaved(snapshotRevision: number): void
  onRecovered(groupId: number, entryId: string): void
}

export function SchedulePanel({
  externalModel = '',
  selectedRow,
  sourceGroupId,
  drafts = {},
  labels = {},
  locale = 'en-US',
  onChangeContext,
  onDraftChange,
  onRowChange,
  onRefresh,
  onSaved,
  onRecovered,
}: SchedulePanelProps) {
  const { apiClient } = useAppServices()
  const navigate = useNavigate()

  const [selectedModel, setSelectedModel] = useState(externalModel)
  // Classic watch(props.externalModel): URL-driven context changes re-seed the
  // selector draft (render-time adjustment, not an effect).
  const [syncedModel, setSyncedModel] = useState(externalModel)
  if (syncedModel !== externalModel) {
    setSyncedModel(externalModel)
    setSelectedModel(externalModel)
  }

  const indexQuery = useQuery(modelRouteScheduleIndexQueryOptions(apiClient))
  const indexItems: ModelRouteScheduleIndexItemDto[] = indexQuery.data?.items ?? []
  const selectedIndexItem = indexItems.find(
    (item) => item.external_model === selectedModel,
  )
  const detailRequest = selectedIndexItem
    ? {
        protocol: selectedIndexItem.protocol,
        external_model: selectedModel,
        operation: selectedIndexItem.operation,
      }
    : undefined
  const detailQuery = useQuery(
    modelRouteScheduleDetailQueryOptions(apiClient, detailRequest),
  )

  const modelOptions = [
    { value: '', label: labels.selectModel ?? '' },
    ...indexItems.map((item) => ({ value: item.external_model, label: item.external_model })),
  ]
  const indexError = indexQuery.error
    ? indexQuery.error instanceof Error && indexQuery.error.message
      ? indexQuery.error.message
      : (labels.indexFailed ?? '')
    : ''
  const detailError = detailQuery.error
    ? detailQuery.error instanceof Error && detailQuery.error.message
      ? detailQuery.error.message
      : (labels.detailFailed ?? '')
    : ''

  function setModel(value: string): void {
    setSelectedModel(value)
    onChangeContext({ externalModel: value || undefined })
  }

  async function refreshIndex(): Promise<void> {
    await indexQuery.refetch()
    onRefresh()
  }

  async function refreshDetail(): Promise<void> {
    if (detailRequest) await detailQuery.refetch()
    await indexQuery.refetch()
    onRefresh()
  }

  async function refreshAll(): Promise<void> {
    await Promise.all([indexQuery.refetch(), detailQuery.refetch()])
    onRefresh()
  }

  async function handleSaved(revision: number): Promise<void> {
    onSaved(revision)
    await refreshAll()
  }

  async function handleRecovered(groupID: number, entryID: string): Promise<void> {
    onRecovered(groupID, entryID)
    await refreshAll()
  }

  const probe = useModelProbe()

  function probeRow(groupID: number, modelID: string, disabled: boolean): void {
    void probe.start([{ group_id: groupID, model: modelID }], {
      disabledGroupIds: disabled ? [groupID] : [],
    })
  }

  function probeRows(
    targets: ModelProbeTargetDto[],
    disabledGroupIds: number[],
  ): void {
    void probe.start(targets, { disabledGroupIds })
  }

  function viewProbeLog(logID: string): void {
    void navigate({
      to: pagePath('logs'),
      search: { selected_request_id: logID },
    })
  }

  return (
    <section
      {...stylex.props(styles.panel)}
      data-testid="schedule-panel"
      aria-label={labels.model ?? ''}
    >
      <div {...stylex.props(styles.filters)} aria-label={labels.context ?? ''}>
        <label {...stylex.props(styles.field)}>
          <span>{labels.model}</span>
          <Selector
            label={labels.model ?? ''}
            isLabelHidden
            size="sm"
            value={selectedModel}
            options={modelOptions}
            isDisabled={indexQuery.isPending || indexQuery.isError}
            onChange={setModel}
          />
        </label>
      </div>

      {indexQuery.isPending ? (
        <div role="status" aria-label={labels.loadingOptions ?? ''}>
          <Skeleton height={44} radius={2} />
        </div>
      ) : indexError ? (
        <Banner
          status="error"
          title={indexError}
          endContent={
            <Button
              variant="secondary"
              size="sm"
              label={labels.retry ?? ''}
              onClick={() => void refreshIndex()}
            />
          }
        />
      ) : null}

      <SchedulePanelDetail
        detail={detailQuery.data}
        loading={
          detailQuery.isPending &&
          detailQuery.data === undefined &&
          Boolean(detailRequest)
        }
        error={detailRequest && detailQuery.data === undefined ? detailError : ''}
        stale={detailQuery.isRefetchError}
        locale={locale}
        selectedRow={selectedRow}
        sourceGroupId={sourceGroupId}
        drafts={drafts}
        labels={labels.detail}
        onRefresh={() => void refreshDetail()}
        onSaved={(revision) => void handleSaved(revision)}
        onRecovered={(groupId, entryId) => void handleRecovered(groupId, entryId)}
        onProbe={probeRow}
        onProbeAll={probeRows}
        onDraftChange={onDraftChange}
        onRowChange={onRowChange}
      />
      <ModelProbeDialog
        open={probe.open}
        pending={probe.pending}
        failed={probe.failed}
        stopped={probe.stopped}
        results={probe.results}
        disabledGroupIds={probe.disabledGroupIds}
        total={probe.total}
        completed={probe.completed}
        applying={true}
        hideGroupControls={true}
        onOpenChange={(open) => {
          if (!open) probe.close()
        }}
        onStop={probe.stop}
        onViewLog={viewProbeLog}
      />
    </section>
  )
}
