// web/src/frontends/astryx/components/ProxyOverrideControl.tsx
import { SegmentedControl, SegmentedControlItem, TextInput } from '@astryxdesign/core'
import * as stylex from '@stylexjs/stylex'
import { useId } from 'react'

import { useT } from '../app/i18n'
import { plainTextInputAttrs } from './input-attrs'
import type { ProxyConfiguredMode, ProxyViewDto } from '@shared/control/types'
import { proxyDraftState, proxyPlaceholderURL } from '@shared/control/resources/proxy'

const styles = stylex.create({
  root: {
    display: 'flex',
    minWidth: 0,
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 'var(--space-2)',
  },
  input: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: '190px',
    minWidth: 0,
  },
})

export function ProxyOverrideControl({
  base,
  mode,
  endpoint,
  disabled = false,
  onModeChange,
  onEndpointChange,
}: {
  /** Saved baseline — derives the placeholder URL and validity state. */
  base: ProxyViewDto
  mode: ProxyConfiguredMode
  endpoint: string
  disabled?: boolean
  onModeChange: (value: ProxyConfiguredMode) => void
  onEndpointChange: (value: string) => void
}) {
  const t = useT()
  const inputId = `${useId()}-proxy-url`

  // `inherit` is expressed by the outer override/restore toggle; only the two
  // explicit override modes appear here.
  const error = proxyDraftState(base, mode, endpoint).invalid
    ? t('common.proxy.invalid')
    : undefined
  const placeholder = proxyPlaceholderURL(base) ?? t('common.proxy.placeholder')

  return (
    <div {...stylex.props(styles.root)}>
      <SegmentedControl
        value={mode === 'custom' ? 'custom' : 'direct'}
        label={t('common.proxy.modeLabel')}
        size="sm"
        isDisabled={disabled}
        onChange={(value) => {
          if (!disabled && (value === 'direct' || value === 'custom')) onModeChange(value)
        }}
      >
        <SegmentedControlItem value="direct" label={t('common.proxy.mode.direct')} />
        <SegmentedControlItem value="custom" label={t('common.proxy.mode.custom')} />
      </SegmentedControl>

      {mode === 'custom' && (
        <TextInput
          id={inputId}
          xstyle={styles.input}
          data-gptload-mono
          value={endpoint}
          label={t('common.proxy.urlLabel')}
          isLabelHidden
          placeholder={placeholder}
          size="sm"
          autoComplete="off"
          {...plainTextInputAttrs}
          isDisabled={disabled}
          status={error === undefined ? undefined : { type: 'error', message: error }}
          statusVariant="tooltip"
          onChange={onEndpointChange}
        />
      )}
    </div>
  )
}

// web/src/frontends/classic/components/config/ProxyOverrideControl.vue
<script setup lang="ts">
import { computed, useId } from 'vue'
import { useI18n } from 'vue-i18n'

import type { ProxyConfiguredMode, ProxyViewDto } from '@shared/control/types'
import { proxyDraftState, proxyPlaceholderURL } from '@/app/resources/proxy'
import AppTextInput from '@/components/ui/AppTextInput.vue'
import CompactFieldError from '@/components/ui/CompactFieldError.vue'
import SegmentedControl, { type SegmentedControlOption } from '@/components/ui/SegmentedControl.vue'

const props = withDefaults(
  defineProps<{
    /** 已保存的基线，用于推导占位地址与校验状态。 */
    base: ProxyViewDto
    mode: ProxyConfiguredMode
    endpoint: string
    disabled?: boolean
  }>(),
  { disabled: false },
)
const emit = defineEmits<{
  'update:mode': [value: ProxyConfiguredMode]
  'update:endpoint': [value: string]
}>()

const { t } = useI18n()
const inputId = `${useId()}-proxy-url`

// inherit 由外层「覆盖 / 恢复默认」开关表达，这里只给出显式覆盖的两种取值。
const modeOptions = computed<SegmentedControlOption[]>(() => [
  { value: 'direct', label: t('common.proxy.mode.direct'), disabled: props.disabled },
  { value: 'custom', label: t('common.proxy.mode.custom'), disabled: props.disabled },
])
const error = computed(() =>
  proxyDraftState(props.base, props.mode, props.endpoint).invalid
    ? t('common.proxy.invalid')
    : undefined,
)
const placeholder = computed(() => proxyPlaceholderURL(props.base) ?? t('common.proxy.placeholder'))

function setMode(value: string): void {
  if (props.disabled || (value !== 'direct' && value !== 'custom')) return
  emit('update:mode', value)
}
</script>

<template>
  <div class="proxy-override-control">
    <SegmentedControl
      :model-value="mode === 'custom' ? 'custom' : 'direct'"
      :label="t('common.proxy.modeLabel')"
      :options="modeOptions"
      size="compact"
      @update:model-value="setMode"
    />

    <CompactFieldError v-if="mode === 'custom'" :id="inputId" :error="error">
      <template #default="{ invalid, describedBy }">
        <AppTextInput
          :id="inputId"
          :model-value="endpoint"
          :label="t('common.proxy.urlLabel')"
          :placeholder="placeholder"
          appearance="surface"
          size="compact"
          autocomplete="off"
          :spellcheck="false"
          monospace
          :disabled="disabled"
          :invalid="invalid"
          :described-by="describedBy"
          @update:model-value="emit('update:endpoint', $event)"
        />
      </template>
    </CompactFieldError>
  </div>
</template>

<style scoped>
.proxy-override-control {
  display: flex;
  min-width: 0;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
}

.proxy-override-control > :deep(.compact-field-error) {
  flex: 1 1 190px;
  min-width: 0;
}
</style>
