// web/src/frontends/astryx/features/home/HomeAttention.tsx
import * as stylex from '@stylexjs/stylex'
import { CircleAlert, TriangleAlert } from 'lucide-react'
import { useIntl } from 'react-intl'

import type { RuntimeHealthDto } from '@shared/control/resources/health'
import {
  attentionRowLimit,
  attentionTotal,
  collectAttentionItems,
  type AttentionItem,
} from '@shared/domain/home/attention'
import { pagePath } from '@shared/routing/page-routes'

import { useT } from '../../app/i18n'
import { RouteLink } from '../../app/route-link'
import { RelativeInstant } from '../../components/RelativeInstant'

const styles = stylex.create({
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    paddingTop: 14,
  },
  srOnly: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    whiteSpace: 'nowrap',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'transparent',
    borderRadius: 'var(--radius-control)',
    paddingTop: 8,
    paddingBottom: 8,
    paddingInline: 11,
    fontSize: 'var(--text-meta)',
    color: 'inherit',
    textDecoration: 'none',
    transitionProperty: 'border-color, background-color',
    transitionDuration: 'var(--duration-fast)',
    transitionTimingFunction: 'var(--easing-standard)',
  },
  rowWarning: {
    borderColor: {
      default: 'color-mix(in srgb, var(--color-warning) 30%, var(--color-border-subtle))',
      ':hover': 'var(--color-warning)',
    },
    backgroundColor: 'var(--color-warning-bg)',
    color: 'var(--color-warning)',
  },
  rowDanger: {
    borderColor: {
      default: 'color-mix(in srgb, var(--color-danger) 30%, var(--color-border-subtle))',
      ':hover': 'var(--color-danger)',
    },
    backgroundColor: 'var(--color-danger-bg)',
    color: 'var(--color-danger)',
  },
  icon: {
    flex: 'none',
  },
  detail: {
    display: 'inline-flex',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: 5,
    minWidth: 0,
  },
  go: {
    marginLeft: 'auto',
    fontWeight: 650,
    whiteSpace: 'nowrap',
  },
})

function itemHref(item: AttentionItem): string {
  if (item.kind === 'blacklisted') {
    return `${pagePath('groups')}/${item.groupID}?tab=credentials&credential_status=blacklisted`
  }
  if (item.kind === 'billing') {
    return `${pagePath('groups')}/${item.groupID}?tab=credentials&credential_status=cooldown`
  }
  return `${pagePath('groups')}/${item.groupID}?tab=credentials`
}

function itemTone(item: AttentionItem, health: RuntimeHealthDto | null): 'danger' | 'warning' {
  if (item.kind === 'blacklisted' || item.kind === 'billing') return 'danger'
  if (
    item.kind === 'expiringResetCredit' &&
    item.expiresAtMS !== undefined &&
    health !== null &&
    item.expiresAtMS - health.observed_at_ms <= 24 * 60 * 60 * 1_000
  ) {
    return 'danger'
  }
  return 'warning'
}

// Conditional block: nothing actionable means no section at all — no heading,
// no border, no "all good" strip (classic HomeAttention).
export function HomeAttention({ health }: { health: RuntimeHealthDto | null }) {
  const intl = useIntl()
  const t = useT()

  const items =
    health === null
      ? []
      : collectAttentionItems(
          health.blacklisted_credentials,
          health.expiring_reset_credits,
          health.low_quota_credentials,
          health.cooldown_credentials,
        )
  if (items.length === 0) return null

  const overflowing = items.length > attentionRowLimit
  const total = attentionTotal(items)

  const quotaPercent = (remaining: number): string =>
    new Intl.NumberFormat(intl.locale, {
      style: 'percent',
      maximumFractionDigits: 0,
    }).format(remaining)

  if (overflowing) {
    return (
      <section {...stylex.props(styles.section)} aria-labelledby="home-attention-title">
        <h2 id="home-attention-title" {...stylex.props(styles.srOnly)}>
          {t('home.ledger.attention.title')}
        </h2>
        <RouteLink
          to={`${pagePath('monitor')}?tab=health`}
          {...stylex.props(styles.row, styles.rowDanger)}
        >
          <CircleAlert {...stylex.props(styles.icon)} size={14} aria-hidden="true" />
          <span>{t('home.ledger.attention.summary', { count: total })}</span>
          <span {...stylex.props(styles.go)} aria-hidden="true">
            {t('home.ledger.attention.action')} →
          </span>
        </RouteLink>
      </section>
    )
  }

  return (
    <section {...stylex.props(styles.section)} aria-labelledby="home-attention-title">
      <h2 id="home-attention-title" {...stylex.props(styles.srOnly)}>
        {t('home.ledger.attention.title')}
      </h2>
      {items.map((item) => {
        const tone = itemTone(item, health)
        return (
          <RouteLink
            key={`${item.kind}-${item.groupID}`}
            to={itemHref(item)}
            {...stylex.props(styles.row, tone === 'danger' ? styles.rowDanger : styles.rowWarning)}
          >
            {item.kind === 'blacklisted' || item.kind === 'billing' ? (
              <CircleAlert {...stylex.props(styles.icon)} size={14} aria-hidden="true" />
            ) : (
              <TriangleAlert {...stylex.props(styles.icon)} size={14} aria-hidden="true" />
            )}
            {item.kind === 'blacklisted' && (
              <span>
                {t('home.ledger.attention.blacklisted', {
                  group: item.groupName,
                  count: item.value,
                })}
              </span>
            )}
            {item.kind === 'billing' && (
              <span {...stylex.props(styles.detail)}>
                {t('home.ledger.attention.billing', {
                  group: item.groupName,
                  count: item.value,
                })}
                {item.cooldownUntilMS !== undefined && (
                  <RelativeInstant instant={item.cooldownUntilMS} emptyLabel="" />
                )}
              </span>
            )}
            {item.kind === 'expiringResetCredit' && (
              <span {...stylex.props(styles.detail)}>
                {t('home.ledger.attention.resetCreditExpiring', {
                  group: item.groupName,
                  count: item.value,
                })}
                <RelativeInstant instant={item.expiresAtMS ?? null} emptyLabel="" />
              </span>
            )}
            {item.kind === 'lowQuota' && (
              <span {...stylex.props(styles.detail)}>
                {t('home.ledger.attention.lowQuota', {
                  group: item.groupName,
                  remaining: quotaPercent(item.value),
                })}
                {item.resetAtMS !== undefined && (
                  <RelativeInstant instant={item.resetAtMS} emptyLabel="" />
                )}
              </span>
            )}
            <span {...stylex.props(styles.go)} aria-hidden="true">
              {t('home.ledger.attention.action')} →
            </span>
          </RouteLink>
        )
      })}
    </section>
  )
}

// web/src/frontends/classic/features/home/HomeAttention.vue
<script setup lang="ts">
import { CircleAlert, TriangleAlert } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { RouterLink } from 'vue-router'

import type { RuntimeHealthDto } from '@/app/resources/health'
import { groupDetailLocation, monitorLocation } from '@/app/route-locations'
import AppRelativeTime from '@/components/ui/AppRelativeTime.vue'

import { attentionRowLimit, attentionTotal, collectAttentionItems } from './attention'

const props = defineProps<{ health: RuntimeHealthDto | null }>()

const { locale, t } = useI18n()

const items = computed(() =>
  props.health === null
    ? []
    : collectAttentionItems(
        props.health.blacklisted_credentials,
        props.health.expiring_reset_credits,
        props.health.low_quota_credentials,
        props.health.cooldown_credentials,
      ),
)
const overflowing = computed(() => items.value.length > attentionRowLimit)
const visibleItems = computed(() => items.value.slice(0, attentionRowLimit))
const total = computed(() => attentionTotal(items.value))

function itemLocation(groupID: number, kind: string) {
  if (kind === 'blacklisted') {
    return groupDetailLocation(groupID, { tab: 'credentials', credential_status: 'blacklisted' })
  }
  if (kind === 'billing') {
    return groupDetailLocation(groupID, { tab: 'credentials', credential_status: 'cooldown' })
  }
  return groupDetailLocation(groupID, { tab: 'credentials' })
}

function quotaPercent(remaining: number): string {
  return new Intl.NumberFormat(locale.value, {
    style: 'percent',
    maximumFractionDigits: 0,
  }).format(remaining)
}

function itemTone(item: (typeof items.value)[number]): 'danger' | 'warning' {
  if (item.kind === 'blacklisted' || item.kind === 'billing') return 'danger'
  if (
    item.kind === 'expiringResetCredit' &&
    item.expiresAtMS !== undefined &&
    props.health !== null &&
    item.expiresAtMS - props.health.observed_at_ms <= 24 * 60 * 60 * 1_000
  ) {
    return 'danger'
  }
  return 'warning'
}
</script>

<template>
  <!-- 条件区：没有要处理的事就整块不渲染——不留标题、不留边框、不留「一切正常」的绿条。 -->
  <section v-if="items.length > 0" class="home-attention" aria-labelledby="home-attention-title">
    <h2 id="home-attention-title" class="sr-only">{{ t('home.ledger.attention.title') }}</h2>

    <RouterLink
      v-if="overflowing"
      class="home-attention__row home-attention__row--danger"
      :to="monitorLocation({ tab: 'health' })"
    >
      <CircleAlert :size="14" aria-hidden="true" />
      <span>{{ t('home.ledger.attention.summary', { count: total }) }}</span>
      <span class="home-attention__go" aria-hidden="true">
        {{ t('home.ledger.attention.action') }} →
      </span>
    </RouterLink>

    <template v-else>
      <RouterLink
        v-for="item in visibleItems"
        :key="`${item.kind}-${item.groupID}`"
        class="home-attention__row"
        :class="`home-attention__row--${itemTone(item)}`"
        :to="itemLocation(item.groupID, item.kind)"
      >
        <CircleAlert
          v-if="item.kind === 'blacklisted' || item.kind === 'billing'"
          :size="14"
          aria-hidden="true"
        />
        <TriangleAlert v-else :size="14" aria-hidden="true" />
        <span v-if="item.kind === 'blacklisted'">
          {{ t('home.ledger.attention.blacklisted', { group: item.groupName, count: item.value }) }}
        </span>
        <span v-else-if="item.kind === 'billing'" class="home-attention__detail">
          {{ t('home.ledger.attention.billing', { group: item.groupName, count: item.value }) }}
          <AppRelativeTime
            v-if="item.cooldownUntilMS !== undefined"
            :instant="item.cooldownUntilMS"
            :locale="locale"
            :empty-label="''"
          />
        </span>
        <span v-else-if="item.kind === 'expiringResetCredit'" class="home-attention__detail">
          {{
            t('home.ledger.attention.resetCreditExpiring', {
              group: item.groupName,
              count: item.value,
            })
          }}
          <AppRelativeTime :instant="item.expiresAtMS ?? null" :locale="locale" :empty-label="''" />
        </span>
        <span v-else class="home-attention__detail">
          {{
            t('home.ledger.attention.lowQuota', {
              group: item.groupName,
              remaining: quotaPercent(item.value),
            })
          }}
          <AppRelativeTime
            v-if="item.resetAtMS !== undefined"
            :instant="item.resetAtMS"
            :locale="locale"
            :empty-label="''"
          />
        </span>
        <span class="home-attention__go" aria-hidden="true">
          {{ t('home.ledger.attention.action') }} →
        </span>
      </RouterLink>
    </template>
  </section>
</template>

<style scoped>
.home-attention {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding-top: 14px;
}

/*
 * 告警要一眼认出来：按 tone 上底色与描边，配警示图标，回到仓库
 * 「图标 + 文字 + 颜色」的三重编码。原来只有一个 6px 圆点承载严重度。
 */
.home-attention__row {
  display: flex;
  align-items: center;
  gap: 9px;
  border: 1px solid transparent;
  border-radius: var(--radius-control);
  padding: 8px 11px;
  font-size: var(--text-meta);
  transition:
    border-color var(--duration-fast) var(--easing-standard),
    background-color var(--duration-fast) var(--easing-standard);
}

.home-attention__row svg {
  flex: none;
}

.home-attention__row--warning {
  border-color: color-mix(in srgb, var(--color-warning) 30%, var(--color-border-subtle));
  background: var(--color-warning-bg);
  color: var(--color-warning);
}

.home-attention__row--danger {
  border-color: color-mix(in srgb, var(--color-danger) 30%, var(--color-border-subtle));
  background: var(--color-danger-bg);
  color: var(--color-danger);
}

.home-attention__row--warning:hover {
  border-color: var(--color-warning);
}

.home-attention__row--danger:hover {
  border-color: var(--color-danger);
}

.home-attention__detail {
  display: inline-flex;
  align-items: baseline;
  flex-wrap: wrap;
  gap: 5px;
  min-width: 0;
}

.home-attention__go {
  margin-left: auto;
  font-weight: 650;
  white-space: nowrap;
}
</style>
