// web/src/frontends/astryx/features/home/HomeSummary.tsx
import * as stylex from '@stylexjs/stylex'
import { useIntl } from 'react-intl'

import type { HomeBaseDto } from '@shared/control/resources/home'
import type { ReleaseUpdateDto } from '@shared/control/resources/system-update'
import {
  formatDuration,
  formatInteger,
  formatLocalInstant,
  formatLocalTime,
} from '@shared/lib/format'

import { useT } from '../../app/i18n'
import { HomeReleaseUpdateLink } from './home-chrome'

const NARROW = '@media (max-width: 860px)'

const styles = stylex.create({
  header: {
    display: 'flex',
    alignItems: {
      default: 'center',
      [NARROW]: 'start',
    },
    justifyContent: 'space-between',
    gap: 22,
    flexWrap: 'wrap',
    // No bottom border: separators are always owned by the next section's
    // top border, and spacing comes from that section's margin — otherwise a
    // quiet page would show a double rule here.
  },
  facts: {
    maxWidth: 'none',
    margin: 0,
    color: 'var(--color-text-muted)',
    fontFamily: 'var(--font-serif)',
    fontSize: 'var(--title-lede)',
    fontWeight: 500,
    lineHeight: 'var(--line-compact)',
    letterSpacing: '-0.015em',
  },
  factStrong: {
    color: 'var(--color-text)',
    fontWeight: 650,
  },
  factLabel: {
    color: 'var(--color-text-muted)',
    fontWeight: 500,
  },
  separator: {
    color: 'var(--color-text-muted)',
    fontWeight: 500,
  },
  stamp: {
    display: 'grid',
    gridTemplateColumns: 'max-content max-content',
    gap: '5px 1ch',
    margin: 0,
    color: 'var(--color-text-faint)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)',
    lineHeight: 'var(--line-compact)',
    whiteSpace: 'nowrap',
    justifyContent: {
      default: 'end',
      [NARROW]: 'start',
    },
  },
  stampRow: {
    display: 'grid',
    gridColumn: '1 / -1',
    gridTemplateColumns: 'subgrid',
    alignItems: 'baseline',
  },
  stampTerm: {
    margin: 0,
    textAlign: 'right',
  },
  stampValue: {
    margin: 0,
    color: 'var(--color-text-muted)',
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 500,
    textAlign: 'left',
  },
  version: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--space-1)',
  },
})

export function HomeSummary({
  base,
  update,
  observedAtMs,
  uptimeNowMs,
}: {
  base: HomeBaseDto
  update: ReleaseUpdateDto | null
  observedAtMs: number | null
  uptimeNowMs: number
}) {
  const intl = useIntl()
  const t = useT()
  const updated =
    observedAtMs === null ? '—' : formatLocalTime(observedAtMs, intl.locale)
  const updatedTitle =
    observedAtMs === null ? undefined : formatLocalInstant(observedAtMs, intl.locale)

  return (
    <header {...stylex.props(styles.header)}>
      <div>
        <h1 id="home-title" {...stylex.props(styles.facts)}>
          <span>
            <strong {...stylex.props(styles.factStrong)}>
              {formatInteger(base.inventory.group_count, intl.locale)}
            </strong>{' '}
            <span {...stylex.props(styles.factLabel)}>{t('home.ledger.factGroups')}</span>
          </span>
          <span {...stylex.props(styles.separator)} aria-hidden="true">
            {' '}
            ·{' '}
          </span>
          <span>
            <strong {...stylex.props(styles.factStrong)}>
              {formatInteger(base.inventory.available_credential_count, intl.locale)}/
              {formatInteger(base.inventory.credential_count, intl.locale)}
            </strong>{' '}
            <span {...stylex.props(styles.factLabel)}>
              {t('home.ledger.factAvailableCredentials')}
            </span>
          </span>
          <span {...stylex.props(styles.separator)} aria-hidden="true">
            {' '}
            ·{' '}
          </span>
          <span>
            <strong {...stylex.props(styles.factStrong)}>
              {formatInteger(base.inventory.model_count, intl.locale)}
            </strong>{' '}
            <span {...stylex.props(styles.factLabel)}>{t('home.ledger.factModels')}</span>
          </span>
        </h1>
      </div>
      <dl {...stylex.props(styles.stamp)}>
        <div {...stylex.props(styles.stampRow)}>
          <dt {...stylex.props(styles.stampTerm)}>{t('home.ledger.updated')}</dt>
          <dd {...stylex.props(styles.stampValue)} title={updatedTitle}>
            {updated}
          </dd>
        </div>
        <div {...stylex.props(styles.stampRow)}>
          <dt {...stylex.props(styles.stampTerm)}>{t('home.ledger.version')}</dt>
          <dd {...stylex.props(styles.stampValue)}>
            <span {...stylex.props(styles.version)}>
              <span>{base.version}</span>
              {update !== null && (
                <HomeReleaseUpdateLink currentVersion={base.version} update={update} />
              )}
            </span>
          </dd>
        </div>
        <div {...stylex.props(styles.stampRow)}>
          <dt {...stylex.props(styles.stampTerm)}>{t('home.ledger.uptime')}</dt>
          <dd {...stylex.props(styles.stampValue)}>
            {formatDuration(base.started_at_ms, uptimeNowMs, intl.locale)}
          </dd>
        </div>
      </dl>
    </header>
  )
}

// web/src/frontends/classic/features/home/HomeSummary.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { HomeBaseDto } from '@/app/resources/home'
import type { ReleaseUpdateDto } from '@/app/resources/system-update'
import { formatDuration, formatInteger, formatLocalInstant, formatLocalTime } from '@shared/lib/format'

import HomeReleaseUpdateLink from './HomeReleaseUpdateLink.vue'

const props = defineProps<{
  base: HomeBaseDto
  update: ReleaseUpdateDto | null
  observedAtMs: number | null
  uptimeNowMs: number
}>()

const { locale, t } = useI18n()

const updated = computed(() =>
  props.observedAtMs === null ? '—' : formatLocalTime(props.observedAtMs, locale.value),
)
const updatedTitle = computed(() =>
  props.observedAtMs === null ? undefined : formatLocalInstant(props.observedAtMs, locale.value),
)
</script>

<template>
  <header class="home-summary__header">
    <div>
      <h1 id="home-title" class="home-summary__facts">
        <span class="home-summary__fact">
          <strong>{{ formatInteger(base.inventory.group_count, locale) }}</strong>
          <span>{{ t('home.ledger.factGroups') }}</span>
        </span>
        <span class="home-summary__separator" aria-hidden="true"> · </span>
        <span class="home-summary__fact">
          <strong>
            {{ formatInteger(base.inventory.available_credential_count, locale) }}/{{
              formatInteger(base.inventory.credential_count, locale)
            }}
          </strong>
          <span>{{ t('home.ledger.factAvailableCredentials') }}</span>
        </span>
        <span class="home-summary__separator" aria-hidden="true"> · </span>
        <span class="home-summary__fact">
          <strong>{{ formatInteger(base.inventory.model_count, locale) }}</strong>
          <span>{{ t('home.ledger.factModels') }}</span>
        </span>
      </h1>
    </div>
    <dl class="home-summary__stamp">
      <div>
        <dt>{{ t('home.ledger.updated') }}</dt>
        <dd :title="updatedTitle">{{ updated }}</dd>
      </div>
      <div>
        <dt>{{ t('home.ledger.version') }}</dt>
        <dd class="home-summary__version">
          <span>{{ base.version }}</span>
          <HomeReleaseUpdateLink v-if="update" :current-version="base.version" :update="update" />
        </dd>
      </div>
      <div>
        <dt>{{ t('home.ledger.uptime') }}</dt>
        <dd>{{ formatDuration(base.started_at_ms, uptimeNowMs, locale) }}</dd>
      </div>
    </dl>
  </header>
</template>

<style scoped>
.home-summary__header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 22px;
  flex-wrap: wrap;
  /*
   * 不画下边线：分隔线一律由「开启新板块」的元素自己的 border-top 承担。
   * 否则没有告警时，这条线会和下一个板块的上边线并排出现两条。
   * 下方间距同样交给板块的 margin-top，这里不再重复留白。
   */
}

.home-summary__facts {
  max-width: none;
  margin: 0;
  color: var(--color-text-muted);
  font-family: var(--font-serif);
  font-size: var(--title-lede);
  font-weight: 500;
  line-height: var(--line-compact);
  letter-spacing: -0.015em;
}

.home-summary__fact {
  color: var(--color-text-muted);
}

.home-summary__fact strong {
  color: var(--color-text);
  font-weight: 650;
}

.home-summary__fact > span,
.home-summary__separator {
  color: var(--color-text-muted);
  font-weight: 500;
}

.home-summary__stamp {
  display: grid;
  grid-template-columns: max-content max-content;
  gap: 5px 1ch;
  margin: 0;
  color: var(--color-text-faint);
  font-family: var(--font-mono);
  font-size: var(--text-sm);
  line-height: var(--line-compact);
  white-space: nowrap;
}

.home-summary__stamp div {
  display: grid;
  grid-column: 1 / -1;
  grid-template-columns: subgrid;
  align-items: baseline;
}
.home-summary__stamp dt,
.home-summary__stamp dd {
  margin: 0;
}

.home-summary__version {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
}

.home-summary__stamp dt {
  text-align: right;
}
.home-summary__stamp dd {
  color: var(--color-text-muted);
  font-variant-numeric: tabular-nums;
  font-weight: 500;
  text-align: left;
}

@media (max-width: 860px) {
  .home-summary__header {
    align-items: start;
  }
  .home-summary__stamp {
    justify-content: start;
  }
}
</style>
