// web/src/frontends/classic/features/groups/GroupHeader.vue
<script setup lang="ts">
import { ArrowLeft, ExternalLink } from '@lucide/vue'
import { useQuery } from '@tanstack/vue-query'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { GroupSummaryDto } from '@/app/resources/groups'
import { useApiClient } from '@shared/http/client-context'
import { channelsQueryOptions } from '@/app/resources/channels'
import { groupsLocation } from '@/app/route-locations'
import ChannelIcon from '@/components/brand/ChannelIcon.vue'
import CopyChip from '@/components/ui/CopyChip.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'

const props = defineProps<{ group: GroupSummaryDto }>()
const { t } = useI18n()
const client = useApiClient()
const channelsQuery = useQuery(channelsQueryOptions(client, ''))
const channel = computed(() =>
  channelsQuery.data.value?.items.find(({ channel_id }) => channel_id === props.group.channel_id),
)
const channelName = computed(() => channel.value?.name.trim() || props.group.channel_id)
</script>

<template>
  <header class="group-header">
    <RouterLink class="group-header__back" :to="groupsLocation()">
      <ArrowLeft :size="16" aria-hidden="true" />{{ t('group.backToGroups') }}
    </RouterLink>
    <div class="group-header__body">
      <div class="group-header__topline">
        <div class="group-header__title">
          <h1 id="group-detail-title">{{ group.name }}</h1>
          <StatusBadge :status="group.service_status" size="compact">
            {{ t(`groups.collection.status.${group.service_status}`) }}
          </StatusBadge>
          <span
            v-if="group.service_status === 'unavailable' && group.service_status_reason"
            class="group-header__status-reason"
          >
            {{ t(`groups.collection.statusReason.${group.service_status_reason}`) }}
          </span>
        </div>
      </div>
      <div class="group-header__details">
        <span v-if="group.price_multiplier !== '1'" class="meta-tag">
          {{ t('common.priceMultiplier.value', { value: group.price_multiplier }) }}
        </span>
        <span class="meta-tag">
          <ChannelIcon
            v-if="channel"
            class="group-header__channel-icon"
            :icon="channel.icon"
            :mark="channel.mark"
          />
          <span>{{ channelName }}</span>
        </span>
        <div id="group-header-actions" class="group-header__actions-target" />
        <a
          v-if="group.provider_url"
          class="group-header__provider-link"
          :href="group.provider_url"
          target="_blank"
          rel="noopener noreferrer"
          :aria-label="t('group.openProviderUrl', { url: group.provider_url })"
        >
          <ExternalLink :size="13" aria-hidden="true" />
          <span>{{ t('group.settings.base.providerUrl') }}</span>
        </a>
        <CopyChip
          v-if="group.params.base_url"
          :value="group.params.base_url"
          :label="t('group.copyUpstreamUrl', { url: group.params.base_url })"
          :success-label="t('group.copySuccess')"
          :failure-label="t('group.copyFailure')"
        />
      </div>
    </div>
  </header>
</template>

<style scoped>
.group-header {
  display: grid;
}
.group-header__back {
  display: inline-flex;
  width: fit-content;
  min-height: 38px;
  align-items: center;
  gap: 6px;
  color: var(--color-text-faint);
  font-size: var(--text-meta);
}
.group-header__back:hover {
  color: var(--color-action);
}
.group-header__body {
  display: grid;
  min-width: 0;
  grid-template-columns: minmax(0, 1fr) auto;
  align-items: center;
  column-gap: var(--space-5);
  padding: var(--space-2) 0 16px;
}
.group-header__topline {
  display: flex;
  min-width: 0;
  grid-column: 1;
  align-items: center;
}
.group-header__title {
  display: flex;
  min-width: 0;
  flex-wrap: wrap;
  align-items: center;
  gap: 10px;
}
.group-header__status-reason {
  color: var(--color-text-muted);
  font-size: var(--text-meta);
}
.group-header h1 {
  max-width: none;
  margin: 0;
  font-size: clamp(26px, 4vw, 34px);
  font-weight: 650;
  letter-spacing: 0;
  line-height: 1.15;
  overflow-wrap: anywhere;
}
.group-header__details {
  display: flex;
  min-width: 0;
  grid-column: 2;
  grid-row: 1;
  flex-wrap: wrap;
  align-items: center;
  justify-content: flex-end;
  gap: 7px 12px;
  margin-top: 0;
}
.group-header__actions-target {
  display: inline-flex;
  min-height: 24px;
  align-items: center;
}
.group-header__actions-target :deep(.group-settings__switch-row) {
  min-height: 20px;
  gap: 0;
  padding: 0;
}
.group-header__actions-target :deep(.group-settings__switch-copy) {
  display: none;
}
.group-header .meta-tag {
  display: inline-flex;
  min-height: 24px;
  background: var(--color-surface-sunken);
  padding: 3px 7px;
  font-size: var(--text-label-xs);
}
.group-header__channel-icon {
  flex: none;
  font-size: 15px;
}
.group-header__provider-link {
  display: inline-flex;
  min-height: var(--control-compact);
  align-items: center;
  gap: 4px;
  border-radius: var(--radius-tag);
  color: var(--color-text-muted);
  padding: 3px 7px;
  font-size: var(--text-label-xs);
  font-weight: 560;
  transition:
    color var(--duration-fast) var(--easing-standard),
    background-color var(--duration-fast) var(--easing-standard);
}
.group-header__provider-link:hover {
  background: var(--color-surface-sunken);
  color: var(--color-action);
}
.group-header__provider-link svg {
  flex: none;
}
.group-header__details :deep(.copy-chip) {
  max-width: 20rem;
  min-height: var(--control-compact);
  padding: 3px 5px;
  font-size: var(--text-sm);
}
@media (max-width: 860px) {
  .group-header__body {
    display: block;
  }

  .group-header__details {
    justify-content: flex-start;
    margin-top: 10px;
  }

  .group-header__provider-link {
    min-height: var(--touch-target);
  }

  .group-header h1 {
    font-size: 27px;
  }
}
@media (max-width: 520px) {
  .group-header__back {
    min-height: var(--touch-target);
  }
  .group-header__body {
    padding-top: 6px;
    padding-bottom: 18px;
  }
  .group-header__title {
    align-items: flex-start;
    flex-direction: column;
    gap: 7px;
  }
  .group-header h1 {
    font-size: 25px;
  }
  .group-header__details {
    align-items: center;
    flex-direction: row;
    row-gap: 8px;
  }
  .group-header__details :deep(.copy-chip-wrap) {
    width: 100%;
  }
  .group-header__details :deep(.copy-chip) {
    width: 100%;
    max-width: 100%;
  }
}
</style>

// web/src/frontends/astryx/features/groups/GroupHeader.tsx
import * as stylex from '@stylexjs/stylex'
import { Badge } from '@astryxdesign/core'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, ExternalLink } from 'lucide-react'

import type { GroupSummaryDto } from '@shared/control/resources/groups'
import { channelsQueryOptions } from '@shared/control/resources/channels'
import { pagePath } from '@shared/routing/page-routes'

import { useT } from '../../app/i18n'
import { RouteLink } from '../../app/route-link'
import { useAppServices } from '../../app/services'
import { ChannelIcon } from '../../components/ChannelIcon'
import { CopyChip } from '../access-keys/AccessKeyCopyChip'

const styles = stylex.create({
  header: {
    display: 'grid',
  },
  back: {
    display: 'inline-flex',
    width: 'fit-content',
    minHeight: { default: '38px', '@media (max-width: 520px)': 'var(--touch-target)' },
    alignItems: 'center',
    gap: 6,
    color: {
      default: 'var(--color-text-faint)',
      ':hover': 'var(--color-action)',
    },
    fontSize: 'var(--text-meta)',
  },
  body: {
    display: { default: 'grid', '@media (max-width: 860px)': 'block' },
    minWidth: 0,
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    columnGap: 'var(--space-5)',
    paddingTop: 'var(--space-2)',
    paddingBottom: { default: '16px', '@media (max-width: 520px)': '18px' },
  },
  topline: {
    display: 'flex',
    minWidth: 0,
    gridColumn: '1',
    alignItems: 'center',
  },
  title: {
    display: 'flex',
    minWidth: 0,
    flexWrap: 'wrap',
    alignItems: { default: 'center', '@media (max-width: 520px)': 'flex-start' },
    flexDirection: { default: 'row', '@media (max-width: 520px)': 'column' },
    gap: { default: '10px', '@media (max-width: 520px)': '7px' },
  },
  h1: {
    maxWidth: 'none',
    margin: 0,
    fontSize: {
      default: 'clamp(26px, 4vw, 34px)',
      '@media (max-width: 860px)': '27px',
      '@media (max-width: 520px)': '25px',
    },
    fontWeight: 650,
    letterSpacing: 0,
    lineHeight: 1.15,
    overflowWrap: 'anywhere',
  },
  statusReason: {
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-meta)',
  },
  details: {
    display: 'flex',
    minWidth: 0,
    gridColumn: '2',
    gridRow: '1',
    flexWrap: 'wrap',
    flexDirection: { default: 'row', '@media (max-width: 520px)': 'row' },
    alignItems: 'center',
    justifyContent: { default: 'flex-end', '@media (max-width: 860px)': 'flex-start' },
    gap: { default: '7px 12px', '@media (max-width: 520px)': '8px 12px' },
    marginTop: { default: 0, '@media (max-width: 860px)': '10px' },
  },
  metaTag: {
    display: 'inline-flex',
    minHeight: '24px',
    alignItems: 'center',
    backgroundColor: 'var(--color-surface-sunken)',
    paddingBlock: '3px',
    paddingInline: '7px',
    fontSize: 'var(--text-label-xs)',
  },
  channelIcon: {
    flexShrink: 0,
    fontSize: '15px',
  },
  actionsTarget: {
    display: 'inline-flex',
    minHeight: '24px',
    alignItems: 'center',
  },
  providerLink: {
    display: 'inline-flex',
    minHeight: {
      default: 'var(--control-compact)',
      '@media (max-width: 860px)': 'var(--touch-target)',
    },
    alignItems: 'center',
    gap: 4,
    borderRadius: 'var(--radius-tag)',
    color: { default: 'var(--color-text-muted)', ':hover': 'var(--color-action)' },
    backgroundColor: { default: 'transparent', ':hover': 'var(--color-surface-sunken)' },
    paddingBlock: '3px',
    paddingInline: '7px',
    fontSize: 'var(--text-label-xs)',
    fontWeight: 560,
    transitionProperty: 'color, background-color',
    transitionDuration: 'var(--duration-fast)',
    transitionTimingFunction: 'var(--easing-standard)',
  },
})

function serviceBadgeVariant(
  status: GroupSummaryDto['service_status'],
): 'success' | 'error' | 'neutral' {
  return status === 'available' ? 'success' : status === 'unavailable' ? 'error' : 'neutral'
}

export function GroupHeader({ group }: { group: GroupSummaryDto }) {
  const t = useT()
  const { apiClient } = useAppServices()
  const channelsQuery = useQuery(channelsQueryOptions(apiClient, ''))
  const channel = channelsQuery.data?.items.find(
    ({ channel_id }) => channel_id === group.channel_id,
  )
  const channelName = channel?.name.trim() || group.channel_id

  return (
    <header {...stylex.props(styles.header)}>
      <RouteLink to={pagePath('groups')} {...stylex.props(styles.back)}>
        <ArrowLeft size={16} aria-hidden="true" />
        {t('group.backToGroups')}
      </RouteLink>
      <div {...stylex.props(styles.body)}>
        <div {...stylex.props(styles.topline)}>
          <div {...stylex.props(styles.title)}>
            <h1 id="group-detail-title" {...stylex.props(styles.h1)}>
              {group.name}
            </h1>
            <Badge
              variant={serviceBadgeVariant(group.service_status)}
              label={t(`groups.collection.status.${group.service_status}`)}
            />
            {group.service_status === 'unavailable' && group.service_status_reason && (
              <span {...stylex.props(styles.statusReason)}>
                {t(`groups.collection.statusReason.${group.service_status_reason}`)}
              </span>
            )}
          </div>
        </div>
        <div {...stylex.props(styles.details)}>
          {group.price_multiplier !== '1' && (
            <span {...stylex.props(styles.metaTag)}>
              {t('common.priceMultiplier.value', { value: group.price_multiplier })}
            </span>
          )}
          <span {...stylex.props(styles.metaTag)}>
            {channel && (
              <ChannelIcon
                icon={channel.icon}
                mark={channel.mark}
              />
            )}
            <span>{channelName}</span>
          </span>
          {/* Unified-mode portal target: GroupSettingsBaseForm teleports its
              enable switch here via createPortal. The id is contractual. */}
          <div id="group-header-actions" {...stylex.props(styles.actionsTarget)} />
          {group.provider_url && (
            <a
              {...stylex.props(styles.providerLink)}
              href={group.provider_url}
              target="_blank"
              rel="noopener noreferrer"
              aria-label={t('group.openProviderUrl', { url: group.provider_url })}
            >
              <ExternalLink size={13} aria-hidden="true" />
              <span>{t('group.settings.base.providerUrl')}</span>
            </a>
          )}
          {group.params.base_url && (
            <CopyChip
              value={group.params.base_url}
              label={t('group.copyUpstreamUrl', { url: group.params.base_url })}
              successLabel={t('group.copySuccess')}
              failureLabel={t('group.copyFailure')}
            />
          )}
        </div>
      </div>
    </header>
  )
}
