// web/src/frontends/classic/features/groups/credentials/GroupCredentialBatchBar.vue
<script setup lang="ts">
import { ListChecks, RefreshCw, Trash2 } from '@lucide/vue'
import { useI18n } from 'vue-i18n'
import AppButton from '@/components/ui/AppButton.vue'

defineProps<{
  selectedCount: number
  allVisibleSelected: boolean
  canSelectAll: boolean
  pending?: boolean
  canSync?: boolean
  canDownload?: boolean
}>()
const emit = defineEmits<{ 'toggle-select': []; sync: []; download: []; remove: [] }>()
const { n, t } = useI18n()
</script>
<template>
  <div class="group-credential-batch">
    <AppButton
      variant="secondary"
      size="compact"
      :busy="pending"
      :disabled="!canSelectAll"
      @click="emit('toggle-select')"
      ><ListChecks :size="15" aria-hidden="true" />{{
        allVisibleSelected
          ? t('group.credentials.batch.clearAll')
          : t('group.credentials.batch.selectAll')
      }}<span v-if="selectedCount > 0">{{ n(selectedCount) }}</span></AppButton
    >
    <AppButton
      v-if="canSync"
      variant="secondary"
      size="compact"
      :busy="pending"
      :disabled="selectedCount === 0"
      @click="emit('sync')"
      ><RefreshCw :size="15" aria-hidden="true" />{{ t('group.credentials.batch.sync') }}</AppButton
    >
    <AppButton
      v-if="canDownload"
      variant="secondary"
      size="compact"
      :busy="pending"
      :disabled="selectedCount === 0"
      @click="emit('download')"
      >{{ t('group.credentials.batch.download') }}</AppButton
    >
    <AppButton
      variant="secondary"
      tone="danger"
      size="compact"
      :busy="pending"
      :disabled="selectedCount === 0"
      @click="emit('remove')"
      ><Trash2 :size="15" aria-hidden="true" />{{ t('group.credentials.batch.delete') }}</AppButton
    >
  </div>
</template>
<style scoped>
.group-credential-batch {
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-end;
  gap: 6px;
}
</style>

// web/src/frontends/astryx/features/groups/credentials/GroupCredentialBatchBar.tsx
import * as stylex from '@stylexjs/stylex'
import { Button } from '@astryxdesign/core'
import { ListChecks, RefreshCw, Trash2 } from 'lucide-react'

import { useT } from '../../../app/i18n'

const styles = stylex.create({
  root: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: '6px',
  },
})

export function GroupCredentialBatchBar({
  selectedCount,
  allVisibleSelected,
  canSelectAll,
  pending = false,
  canSync = false,
  canDownload = false,
  onToggleSelect,
  onSync,
  onDownload,
  onRemove,
}: {
  selectedCount: number
  allVisibleSelected: boolean
  canSelectAll: boolean
  pending?: boolean
  canSync?: boolean
  canDownload?: boolean
  onToggleSelect(): void
  onSync(): void
  onDownload(): void
  onRemove(): void
}) {
  const t = useT()
  return (
    <div {...stylex.props(styles.root)}>
      <Button
        variant="secondary"
        size="sm"
        isLoading={pending}
        isDisabled={!canSelectAll}
        icon={<ListChecks size={15} aria-hidden="true" />}
        label={
          allVisibleSelected
            ? `${t('group.credentials.batch.clearAll')}${selectedCount > 0 ? ` ${selectedCount}` : ''}`
            : `${t('group.credentials.batch.selectAll')}${selectedCount > 0 ? ` ${selectedCount}` : ''}`
        }
        onClick={onToggleSelect}
      />
      {canSync && (
        <Button
          variant="secondary"
          size="sm"
          isLoading={pending}
          isDisabled={selectedCount === 0}
          icon={<RefreshCw size={15} aria-hidden="true" />}
          label={t('group.credentials.batch.sync')}
          onClick={onSync}
        />
      )}
      {canDownload && (
        <Button
          variant="secondary"
          size="sm"
          isLoading={pending}
          isDisabled={selectedCount === 0}
          label={t('group.credentials.batch.download')}
          onClick={onDownload}
        />
      )}
      <Button
        variant="secondary"
        size="sm"
        isLoading={pending}
        isDisabled={selectedCount === 0}
        icon={<Trash2 size={15} aria-hidden="true" />}
        label={t('group.credentials.batch.delete')}
        onClick={onRemove}
      />
    </div>
  )
}
