// web/src/frontends/astryx/features/groups/settings/GroupSettingsBaseForm.tsx
import { Button, Switch, TextInput } from '@astryxdesign/core'
import * as stylex from '@stylexjs/stylex'
import { useState } from 'react'
import { createPortal } from 'react-dom'

import type { ChannelParamsDto } from '@shared/control/types'
import type { ChannelDto, ChannelFieldDto } from '@shared/control/resources/channels'
import { isValidPriceMultiplier } from '@shared/lib/price-multiplier'
import { useT } from '../../../app/i18n'
import { ChannelPresetPicker } from '../../import/ChannelPresetPicker'

export function GroupSettingsBaseForm({
  section,
  channelId,
  channels,
  selectedChannel,
  channelsLoading,
  channelsError,
  paramFields,
  params,
  name,
  providerUrl,
  priceMultiplier,
  enabled,
  enabledPending = false,
  pending,
  paramsDisabled = false,
  nameError,
  paramErrors,
  showTitle = true,
  showDescription = true,
  unified = false,
  headerActionsTarget,
  onParamChange,
  onChannelSelect,
  onChannelsRetry,
  onNameChange,
  onProviderUrlChange,
  onPriceMultiplierChange,
  onSetEnabled,
}: {
  section: 'general' | 'routing'
  channelId: string
  channels: readonly ChannelDto[]
  selectedChannel: ChannelDto | null
  channelsLoading: boolean
  channelsError: boolean
  paramFields: ChannelFieldDto[]
  params: ChannelParamsDto
  name: string
  providerUrl: string | null
  priceMultiplier: string
  enabled: boolean
  enabledPending?: boolean
  pending: boolean
  paramsDisabled?: boolean
  nameError: string
  paramErrors: Record<string, string>
  showTitle?: boolean
  showDescription?: boolean
  unified?: boolean
  headerActionsTarget?: HTMLElement | null
  onParamChange(key: string, value: string | null): void
  onChannelSelect(channel: ChannelDto): void
  onChannelsRetry(): void
  onNameChange(value: string): void
  onProviderUrlChange(value: string): void
  onPriceMultiplierChange(value: string): void
  onSetEnabled(value: boolean): void
}) {
  const t = useT()
  const [baseUrlOverrideEnabled, setBaseUrlOverrideEnabled] = useState(true)
  const [lastChannelId, setLastChannelId] = useState(channelId)
  if (lastChannelId !== channelId) {
    setLastChannelId(channelId)
    setBaseUrlOverrideEnabled(true)
  }

  const baseUrlParam = params.base_url
  const [lastBaseUrl, setLastBaseUrl] = useState(baseUrlParam)
  if (baseUrlParam !== lastBaseUrl) {
    setLastBaseUrl(baseUrlParam)
    if (baseUrlParam?.trim()) setBaseUrlOverrideEnabled(true)
  }

  function isOptionalBaseURL(field: ChannelFieldDto): boolean {
    return field.key === 'base_url' && !field.required
  }

  function setBaseURLOverride(enabled: boolean): void {
    setBaseUrlOverrideEnabled(enabled)
    if (!enabled) onParamChange('base_url', null)
  }

  function updateParam(field: ChannelFieldDto, value: string): void {
    if (isOptionalBaseURL(field) && !value.trim()) {
      setBaseUrlOverrideEnabled(false)
      onParamChange(field.key, null)
      return
    }
    onParamChange(field.key, value)
  }

  function parameterHelp(field: ChannelFieldDto): string {
    if (field.key === 'base_url') {
      if (channelId === 'gpt_load') return t('group.settings.base.gptLoadUrlDescription')
      if (channelId === 'newapi') return t('group.settings.base.newApiUrlDescription')
      if (channelId === 'cliproxyapi') return t('group.settings.base.cpaUrlDescription')
      if (channelId === 'sub2api') return t('group.settings.base.sub2ApiUrlDescription')
    }
    return t('group.settings.base.urlWarning')
  }

  if (section !== 'general') return null

  const switchRow = (
    <div {...stylex.props(styles.switchRow)}>
      <span {...stylex.props(styles.switchCopy)}>
        <strong {...stylex.props(styles.switchTitle)}>{t('group.settings.base.enabled')}</strong>
        <small {...stylex.props(styles.switchHint)}>{t('group.settings.base.enabledHelp')}</small>
      </span>
      <div {...stylex.props(styles.enabledActions)}>
        <Button
          variant="secondary"
          size="sm"
          isDisabled={pending || enabledPending || enabled}
          onClick={() => onSetEnabled(true)}
          label={t('group.settings.base.enableAll')}
        />
        <Button
          variant="secondary"
          size="sm"
          isDisabled={pending || enabledPending || !enabled}
          onClick={() => onSetEnabled(false)}
          label={t('group.settings.base.disableAll')}
        />
      </div>
    </div>
  )

  return (
    <section id="settings-general" {...stylex.props(styles.section)}>
      {(showTitle || showDescription) && (
        <header>
          {showTitle && (
            <h3 {...stylex.props(styles.sectionHeading)}>{t('group.settings.sections.general')}</h3>
          )}
          {showDescription && (
            <p {...stylex.props(styles.sectionDescription)}>
              {t('group.settings.base.description')}
            </p>
          )}
        </header>
      )}
      <div {...stylex.props(styles.channelField)}>
        <span {...stylex.props(styles.fieldLabel)}>{t('group.settings.base.channel')}</span>
        <small {...stylex.props(styles.fieldHint)}>{t('group.settings.base.channelHelp')}</small>
        <div {...stylex.props(styles.channelPicker)}>
          <ChannelPresetPicker
            value={channelId}
            channels={channels}
            selectedChannel={selectedChannel}
            loading={channelsLoading}
            error={channelsError}
            disabled={pending}
            hideHeader
            compact
            onSelect={onChannelSelect}
            onRetry={onChannelsRetry}
          />
        </div>
      </div>
      <div {...stylex.props(styles.grid)}>
        <label {...stylex.props(styles.field)}>
          <span {...stylex.props(styles.fieldLabel)}>{t('group.settings.base.name')}</span>
          <TextInput
            label={t('group.settings.base.name')}
            isLabelHidden
            value={name}
            isDisabled={pending}
            status={nameError !== '' ? { type: 'error', message: nameError } : undefined}
            onChange={onNameChange}
          />
        </label>
        <label {...stylex.props(styles.field)}>
          <span {...stylex.props(styles.fieldLabel)}>{t('common.priceMultiplier.label')}</span>
          <TextInput
            label={t('common.priceMultiplier.label')}
            isLabelHidden
            value={priceMultiplier}
            isDisabled={pending}
            status={
              !isValidPriceMultiplier(priceMultiplier)
                ? { type: 'error', message: t('common.priceMultiplier.invalid') }
                : undefined
            }
            description={
              isValidPriceMultiplier(priceMultiplier)
                ? t('common.priceMultiplier.groupHelp')
                : undefined
            }
            onChange={onPriceMultiplierChange}
            xstyle={styles.mono}
          />
        </label>
        {paramFields.map((field) => {
          const optionalBaseURL = isOptionalBaseURL(field)
          const error = paramErrors[field.key]
          return (
            <div key={field.key} style={{ display: 'contents' }}>
              {optionalBaseURL && (
                <div {...stylex.props(styles.field, styles.baseUrlToggle)}>
                  <span {...stylex.props(styles.fieldLabel)}>
                    {t('group.settings.base.customUrl')}
                  </span>
                  <div {...stylex.props(styles.baseUrlSwitch)}>
                    <small {...stylex.props(styles.fieldHint)}>
                      {t('group.settings.base.customUrlHelp')}
                    </small>
                    <Switch
                      value={baseUrlOverrideEnabled}
                      isDisabled={pending || paramsDisabled}
                      label={t('group.settings.base.customUrl')}
                      isLabelHidden
                      onChange={setBaseURLOverride}
                    />
                  </div>
                </div>
              )}
              {(!optionalBaseURL || baseUrlOverrideEnabled) && (
                <label
                  {...stylex.props(
                    styles.field,
                    optionalBaseURL ? styles.baseUrlInput : styles.wide,
                  )}
                >
                  <span {...stylex.props(styles.fieldLabel)}>
                    {field.key === 'base_url' ? t('group.settings.base.upstreamUrl') : field.label}
                  </span>
                  <TextInput
                    label={
                      field.key === 'base_url'
                        ? t('group.settings.base.upstreamUrl')
                        : field.label
                    }
                    isLabelHidden
                    type="text"
                    value={params[field.key] ?? ''}
                    isDisabled={pending || paramsDisabled}
                    isRequired={
                      field.required || (field.key === 'base_url' && baseUrlOverrideEnabled)
                    }
                    status={error ? { type: 'error', message: error } : undefined}
                    description={
                      error === undefined && field.input_kind === 'url'
                        ? parameterHelp(field)
                        : undefined
                    }
                    onChange={(value) => updateParam(field, value)}
                    xstyle={styles.mono}
                  />
                </label>
              )}
            </div>
          )
        })}
        <label {...stylex.props(styles.field, styles.wide)}>
          <span {...stylex.props(styles.fieldLabel)}>{t('group.settings.base.providerUrl')}</span>
          <TextInput
            label={t('group.settings.base.providerUrl')}
            isLabelHidden
            type="text"
            value={providerUrl ?? ''}
            isDisabled={pending}
            description={t('group.settings.base.providerUrlHelp')}
            onChange={onProviderUrlChange}
            xstyle={styles.mono}
          />
        </label>
        {unified && headerActionsTarget
          ? createPortal(switchRow, headerActionsTarget)
          : switchRow}
      </div>
    </section>
  )
}

const styles = stylex.create({
  section: {
    display: 'grid',
    gap: '15px',
    scrollMarginTop: '76px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingTop: '17px',
  },
  sectionHeading: {
    margin: 0,
    fontSize: 'var(--text-body)',
    fontWeight: 650,
  },
  sectionDescription: {
    maxWidth: '580px',
    marginTop: '3px',
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-sm)',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 800px)': '1fr',
    },
    gap: '15px 18px',
  },
  wide: {
    gridColumn: {
      default: '1 / -1',
      '@media (max-width: 800px)': 'auto',
    },
  },
  baseUrlInput: {
    gridColumn: 'auto',
  },
  field: {
    display: 'grid',
    alignContent: 'start',
    gap: '6px',
  },
  fieldLabel: {
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-sm)',
    fontWeight: 560,
  },
  fieldHint: {
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
    lineHeight: 'var(--line-normal)',
  },
  channelField: {
    display: 'grid',
    minWidth: 0,
    gap: '4px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--color-border-subtle)',
    paddingBottom: 'var(--space-3)',
  },
  channelPicker: {
    marginTop: '3px',
  },
  mono: {
    fontFamily: 'var(--font-mono)',
  },
  baseUrlToggle: {},
  baseUrlSwitch: {
    display: 'flex',
    minHeight: 'var(--control-xs)',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--space-3)',
  },
  switchRow: {
    display: 'flex',
    minHeight: '48px',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '18px',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '2px',
    paddingRight: '2px',
  },
  switchCopy: {
    display: 'grid',
  },
  switchTitle: {
    fontSize: '12.5px',
  },
  switchHint: {
    color: 'var(--color-text-faint)',
    fontSize: '11px',
  },
  enabledActions: {
    display: 'flex',
    flexShrink: 0,
    alignItems: 'center',
    gap: '8px',
  },
})

// web/src/frontends/classic/features/groups/settings/GroupSettingsBaseForm.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import type { ChannelParamsDto } from '@shared/control/types'
import type { ChannelDto, ChannelFieldDto } from '@/app/resources/channels'
import AppButton from '@/components/ui/AppButton.vue'
import AppSwitch from '@/components/ui/AppSwitch.vue'
import ChannelPresetPicker from '@/features/import/ChannelPresetPicker.vue'
import { isValidPriceMultiplier } from '@shared/lib/price-multiplier'

const props = withDefaults(
  defineProps<{
    section: 'general' | 'routing'
    channelId: string
    channels: readonly ChannelDto[]
    selectedChannel: ChannelDto | null
    channelsLoading: boolean
    channelsError: boolean
    paramFields: ChannelFieldDto[]
    params: ChannelParamsDto
    name: string
    providerUrl: string | null
    priceMultiplier: string
    enabled: boolean
    enabledPending?: boolean
    pending: boolean
    paramsDisabled?: boolean
    nameError: string
    paramErrors: Record<string, string>
    showTitle?: boolean
    showDescription?: boolean
    unified?: boolean
  }>(),
  { showTitle: true, showDescription: true, unified: false, enabledPending: false },
)
const emit = defineEmits<{
  'update:param': [key: string, value: string | null]
  'update:channel': [channel: ChannelDto]
  'retry:channels': []
  'update:name': [value: string]
  'update:providerUrl': [value: string]
  'update:priceMultiplier': [value: string]
  'set-enabled': [value: boolean]
}>()
const { t } = useI18n()
const baseUrlOverrideEnabled = ref(true)

watch(
  () => props.channelId,
  () => {
    baseUrlOverrideEnabled.value = true
  },
  { immediate: true },
)

watch(
  () => props.params.base_url,
  (value) => {
    if (value?.trim()) baseUrlOverrideEnabled.value = true
  },
)

function isOptionalBaseURL(field: ChannelFieldDto): boolean {
  return field.key === 'base_url' && !field.required
}

function setBaseURLOverride(enabled: boolean): void {
  baseUrlOverrideEnabled.value = enabled
  if (!enabled) emit('update:param', 'base_url', null)
}

function updateParam(field: ChannelFieldDto, value: string): void {
  if (isOptionalBaseURL(field) && !value.trim()) {
    baseUrlOverrideEnabled.value = false
    emit('update:param', field.key, null)
    return
  }
  emit('update:param', field.key, value)
}

function parameterHelp(field: ChannelFieldDto): string {
  if (field.key === 'base_url' && props.channelId === 'gpt_load') {
    return t('group.settings.base.gptLoadUrlDescription')
  }
  if (field.key === 'base_url' && props.channelId === 'newapi') {
    return t('group.settings.base.newApiUrlDescription')
  }
  if (field.key === 'base_url' && props.channelId === 'cliproxyapi') {
    return t('group.settings.base.cpaUrlDescription')
  }
  if (field.key === 'base_url' && props.channelId === 'sub2api') {
    return t('group.settings.base.sub2ApiUrlDescription')
  }
  return t('group.settings.base.urlWarning')
}
</script>

<template>
  <section v-if="section === 'general'" id="settings-general" class="group-settings__section">
    <header v-if="showTitle || showDescription" class="group-settings__section-heading">
      <h3 v-if="showTitle">{{ t('group.settings.sections.general') }}</h3>
      <p v-if="showDescription">{{ t('group.settings.base.description') }}</p>
    </header>
    <div class="group-settings__channel-field">
      <span class="group-settings__field-label">{{ t('group.settings.base.channel') }}</span>
      <small>{{ t('group.settings.base.channelHelp') }}</small>
      <ChannelPresetPicker
        :model-value="channelId"
        :channels="channels"
        :selected-channel="selectedChannel"
        :loading="channelsLoading"
        :error="channelsError"
        :disabled="pending"
        hide-header
        compact
        @select="emit('update:channel', $event)"
        @retry="emit('retry:channels')"
      />
    </div>
    <div class="group-settings__grid">
      <label class="group-settings__field">
        <span>{{ t('group.settings.base.name') }}</span>
        <input
          :value="name"
          :disabled="pending"
          :aria-invalid="nameError ? 'true' : undefined"
          @input="emit('update:name', ($event.target as HTMLInputElement).value)"
        />
        <small v-if="nameError" role="alert">{{ nameError }}</small>
      </label>
      <label class="group-settings__field">
        <span>{{ t('common.priceMultiplier.label') }}</span>
        <input
          class="group-settings__mono"
          :value="priceMultiplier"
          inputmode="decimal"
          :disabled="pending"
          :aria-invalid="!isValidPriceMultiplier(priceMultiplier) || undefined"
          @input="emit('update:priceMultiplier', ($event.target as HTMLInputElement).value)"
        />
        <small v-if="!isValidPriceMultiplier(priceMultiplier)" role="alert">
          {{ t('common.priceMultiplier.invalid') }}
        </small>
        <small v-else>{{ t('common.priceMultiplier.groupHelp') }}</small>
      </label>
      <template v-for="field in paramFields" :key="field.key">
        <div
          v-if="isOptionalBaseURL(field)"
          class="group-settings__field group-settings__base-url-toggle"
        >
          <span>{{ t('group.settings.base.customUrl') }}</span>
          <div class="group-settings__base-url-switch">
            <small>{{ t('group.settings.base.customUrlHelp') }}</small>
            <AppSwitch
              :model-value="baseUrlOverrideEnabled"
              :disabled="pending || paramsDisabled"
              :label="t('group.settings.base.customUrl')"
              @update:model-value="setBaseURLOverride"
            />
          </div>
        </div>
        <label
          v-if="!isOptionalBaseURL(field) || baseUrlOverrideEnabled"
          class="group-settings__field"
          :class="
            isOptionalBaseURL(field) ? 'group-settings__base-url-input' : 'group-settings__wide'
          "
        >
          <span>{{
            field.key === 'base_url' ? t('group.settings.base.upstreamUrl') : field.label
          }}</span>
          <input
            class="group-settings__mono"
            :type="field.input_kind === 'url' ? 'url' : 'text'"
            :value="params[field.key] ?? ''"
            :disabled="pending || paramsDisabled"
            :required="field.required || (field.key === 'base_url' && baseUrlOverrideEnabled)"
            :aria-invalid="paramErrors[field.key] ? 'true' : undefined"
            @input="updateParam(field, ($event.target as HTMLInputElement).value)"
          />
          <small v-if="paramErrors[field.key]" role="alert">{{ paramErrors[field.key] }}</small>
          <small v-else-if="field.input_kind === 'url'">{{ parameterHelp(field) }}</small>
        </label>
      </template>
      <label class="group-settings__field group-settings__wide">
        <span>{{ t('group.settings.base.providerUrl') }}</span>
        <input
          class="group-settings__mono"
          type="url"
          :value="providerUrl ?? ''"
          :aria-label="t('group.settings.base.providerUrl')"
          :disabled="pending"
          @input="emit('update:providerUrl', ($event.target as HTMLInputElement).value)"
        />
        <small>{{ t('group.settings.base.providerUrlHelp') }}</small>
      </label>
      <Teleport :disabled="!unified" defer to="#group-header-actions">
        <div class="group-settings__switch-row">
          <span class="group-settings__switch-copy">
            <strong>{{ t('group.settings.base.enabled') }}</strong>
            <small>{{ t('group.settings.base.enabledHelp') }}</small>
          </span>
          <div class="group-settings__enabled-actions">
            <AppButton
              variant="secondary"
              size="compact"
              :disabled="pending || enabledPending || enabled"
              @click="emit('set-enabled', true)"
            >
              {{ t('group.settings.base.enableAll') }}
            </AppButton>
            <AppButton
              variant="secondary"
              size="compact"
              :disabled="pending || enabledPending || !enabled"
              @click="emit('set-enabled', false)"
            >
              {{ t('group.settings.base.disableAll') }}
            </AppButton>
          </div>
        </div>
      </Teleport>
    </div>
  </section>
</template>

<style scoped>
.group-settings__section {
  display: grid;
  gap: 15px;
  scroll-margin-top: 76px;
  border-top: 1px solid var(--color-border-subtle);
  padding-top: 17px;
}

.group-settings__section:first-child {
  border-top: 0;
  padding-top: 0;
}

.group-settings__section-heading h3,
.group-settings__section-heading p {
  margin: 0;
}

.group-settings__section-heading h3 {
  font-size: var(--text-body);
  font-weight: 650;
}

.group-settings__section-heading p {
  max-width: 580px;
  margin-top: 3px;
  color: var(--color-text-faint);
  font-size: var(--text-sm);
}

.group-settings__grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 15px 18px;
}

.group-settings__wide {
  grid-column: 1 / -1;
}

.group-settings__base-url-input {
  grid-column: auto;
}

.group-settings__field {
  display: grid;
  align-content: start;
  gap: 6px;
}

.group-settings__field > span,
.group-settings__field > legend,
.group-settings__field-label {
  color: var(--color-text-muted);
  font-size: var(--text-sm);
  font-weight: 560;
}
.group-settings__channel-field {
  display: grid;
  min-width: 0;
  gap: 4px;
  border-bottom: 1px solid var(--color-border-subtle);
  padding-bottom: var(--space-3);
}
.group-settings__channel-field > small {
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
  line-height: var(--line-normal);
}
.group-settings__channel-field :deep(.channel-picker) {
  margin-top: 3px;
}
.group-settings__channel-field :deep(.channel-picker__selector) {
  align-items: flex-start;
}

.group-settings__field small {
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
  line-height: var(--line-normal);
}

.group-settings__field small[role='alert'] {
  color: var(--color-danger);
}

.group-settings__field input:not([type='checkbox']) {
  width: 100%;
  min-height: var(--control-md);
  border: 1px solid var(--color-border-control);
  border-radius: var(--radius-control);
  background: var(--color-surface);
  color: var(--color-text);
  padding: 0 var(--space-3);
  font: inherit;
}

.group-settings__mono,
.group-settings__field code {
  font-family: var(--font-mono);
}

.group-settings__base-url-switch {
  display: flex;
  min-height: var(--control-xs);
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
}

.group-settings__base-url-switch small {
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
  line-height: 1.55;
}

fieldset {
  margin: 0;
  border: 0;
  padding: 0;
}

.group-settings__switch-row {
  display: flex;
  min-height: 48px;
  align-items: center;
  justify-content: space-between;
  gap: 18px;
  padding: 8px 2px;
}

.group-settings__switch-copy {
  display: grid;
}

.group-settings__switch-copy strong {
  font-size: 12.5px;
}

.group-settings__switch-copy small {
  color: var(--color-text-faint);
  font-size: 11px;
}

.group-settings__enabled-actions {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  gap: 8px;
}

@media (max-width: 800px) {
  .group-settings__grid {
    grid-template-columns: 1fr;
  }

  .group-settings__wide {
    grid-column: auto;
  }

  .group-settings__field input:not([type='checkbox']) {
    font-size: 16px;
  }

  .group-settings__weight-editor :deep(.segmented-control__trigger) {
    min-height: var(--touch-target);
  }

  .group-settings__field .group-settings__weight-editor > input {
    min-height: var(--touch-target);
  }
}
</style>
