// web/src/frontends/astryx/features/access-keys/AccessKeyCollection.tsx
import * as stylex from '@stylexjs/stylex'
import { Badge, Button, IconButton, Table, pixel, proportional, type TableColumn } from '@astryxdesign/core'
import { ArrowRight, RotateCcw, Trash2 } from 'lucide-react'
import {
  useCallback,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
  type ReactNode,
  type Ref,
} from 'react'
import { useIntl } from 'react-intl'

import { revealAccessKey } from '@shared/control/resources/access-keys'
import type {
  AccessKeyCollectionItemDto,
  AccessKeyDto,
  GroupOptionDto,
} from '@shared/control/types'
import {
  presentAccessKeyCollection,
  type AccessKeyPresentation,
} from '@shared/domain/access-keys/access-key-presenter'
import type { MessageId } from '@shared/i18n/message-ids'

import { useT } from '../../app/i18n'
import { useAppServices } from '../../app/services'
import { RelativeInstant } from '../../components/RelativeInstant'
import { CopyChip } from './AccessKeyCopyChip'
import { AccessKeyCostLimitResetDialog } from './AccessKeyCostLimitResetDialog'
import { AccessKeyDeleteDialog } from './AccessKeyDeleteDialog'

const styles = stylex.create({
  nameCell: {
    minWidth: 0,
    color: 'var(--color-text)',
    fontWeight: 600,
    overflowWrap: 'anywhere',
  },
  statusCell: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 5,
  },
  scopeCell: {
    display: 'grid',
    gap: 3,
    margin: 0,
  },
  scopeRow: {
    display: 'grid',
    minWidth: 0,
    gridTemplateColumns: '46px minmax(0, 1fr)',
    alignItems: 'baseline',
    gap: 6,
  },
  scopeTerm: {
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
    textAlign: 'right',
  },
  scopeValue: {
    minWidth: 0,
    margin: 0,
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-label-xs)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  limitsCell: {
    display: 'grid',
    gap: 2,
    color: 'var(--color-text-muted)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)',
  },
  timeCell: {
    color: 'var(--color-text-muted)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-sm)',
  },
  actionsCell: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
})

// Table requires rows to satisfy Record<string, unknown>.
type AccessKeyRow = AccessKeyPresentation & Record<string, unknown>

/** Imperative handle mirroring the classic defineExpose({ conceal }). */
export interface AccessKeyCollectionHandle {
  /**
   * Abort every in-flight key reveal and remount the copy chips so transient
   * copy feedback/fallback state is cleared (classic conceal()).
   */
  conceal(): void
}

export function AccessKeyCollection({
  accessKeys,
  groups,
  total,
  filteredTotal,
  page,
  pageSize,
  busyIds,
  lockedIds,
  onOpen,
  onToggle,
  onDeleted,
  onReset,
  ref,
}: {
  accessKeys: readonly AccessKeyCollectionItemDto[]
  groups: readonly GroupOptionDto[]
  total: number
  filteredTotal: number
  page: number
  pageSize: number
  busyIds: ReadonlySet<number>
  lockedIds: ReadonlySet<number>
  onOpen(accessKey: AccessKeyCollectionItemDto, trigger: HTMLElement): void
  onToggle(accessKey: AccessKeyCollectionItemDto): void
  onDeleted(name: string): void
  onReset(name: string): void
  ref?: Ref<AccessKeyCollectionHandle>
}) {
  const t = useT()
  const intl = useIntl()
  const { apiClient } = useAppServices()
  const sources = useMemo(
    () => new Map(accessKeys.map((accessKey) => [accessKey.id, accessKey])),
    [accessKeys],
  )
  // Classic conceals whenever page or the visible id set changes — a bump in
  // copyGeneration remounts the chips (clearing transient copy state), and the
  // effect below aborts the in-flight reveal requests themselves.
  const ids = accessKeys.map(({ id }) => id).join(',')
  const [copyGeneration, setCopyGeneration] = useState(0)
  const [concealed, setConcealed] = useState({ page, ids })
  if (concealed.page !== page || concealed.ids !== ids) {
    setConcealed({ page, ids })
    setCopyGeneration((generation) => generation + 1)
  }
  const revealControllersRef = useRef(new Map<number, AbortController>())

  const abortReveals = useCallback(() => {
    for (const controller of revealControllersRef.current.values()) controller.abort()
    revealControllersRef.current.clear()
  }, [])

  const conceal = useCallback(() => {
    abortReveals()
    setCopyGeneration((generation) => generation + 1)
  }, [abortReveals])
  useImperativeHandle(ref, () => ({ conceal }), [conceal])

  useEffect(() => {
    abortReveals()
  }, [page, ids, abortReveals])
  useEffect(() => abortReveals, [abortReveals])

  const source = (id: number): AccessKeyCollectionItemDto => {
    const accessKey = sources.get(id)
    if (!accessKey) throw new Error(`ACCESS_KEY_SOURCE_MISSING:${id}`)
    return accessKey
  }

  const presentations = useMemo(
    () =>
      presentAccessKeyCollection(accessKeys, groups, {
        locale: intl.locale,
        labels: {
          groups: t('accessKeys.filterGroups'),
          protocols: t('accessKeys.filterProtocols'),
          models: t('accessKeys.filterModels'),
          allGroups: t('accessKeys.allGroups'),
          allProtocols: t('accessKeys.allProtocols'),
          allModels: t('accessKeys.allModels'),
          unlimited: t('accessKeys.unlimited'),
          costRules: (count) => t('accessKeys.costLimits.ruleCount', { count }),
          priceMultiplier: (value) => t('common.priceMultiplier.value', { value }),
        },
        protocolLabel: (protocol) => protocol,
      }),
    [accessKeys, groups, intl.locale, t],
  )

  const resolveCopyValue = async (id: number): Promise<string> => {
    const controller = new AbortController()
    revealControllersRef.current.set(id, controller)
    try {
      const result = await revealAccessKey(apiClient, id, controller.signal)
      return result.key
    } finally {
      if (revealControllersRef.current.get(id) === controller) {
        revealControllersRef.current.delete(id)
      }
    }
  }

  // Rebuilt per render so cell callbacks never close over stale props.
  const columns: TableColumn<AccessKeyRow>[] = [
      {
        key: 'name',
        header: t('accessKeys.columns.name'),
        width: proportional(1.05),
        renderCell: (record): ReactNode => (
          <span {...stylex.props(styles.nameCell)}>{record.name}</span>
        ),
      },
      {
        key: 'key',
        header: t('accessKeys.columns.key'),
        width: proportional(1.3),
        renderCell: (record): ReactNode => (
          <CopyChip
            key={`${copyGeneration}:${source(record.id).updated_at_ms}`}
            value={record.maskedKey}
            label={t('accessKeys.copy')}
            successLabel={t('common.copied')}
            failureLabel={t('common.copyFailed')}
            resolveValue={() => resolveCopyValue(record.id)}
          />
        ),
      },
      {
        key: 'status',
        header: t('accessKeys.columns.status'),
        width: pixel(120),
        renderCell: (record): ReactNode => (
          <span {...stylex.props(styles.statusCell)}>
            <Badge
              variant={record.status === 'active' ? 'success' : 'neutral'}
              label={t(`accessKeys.status.${record.status}` as MessageId)}
            />
            {record.expired && (
              <Badge variant="error" label={t('accessKeys.status.expired')} />
            )}
            {record.ipRestricted && (
              <Badge variant="neutral" label={t('accessKeys.status.ipRestricted')} />
            )}
            {record.quotaExhausted && (
              <Badge variant="error" label={t('accessKeys.costLimits.exhausted')} />
            )}
          </span>
        ),
      },
      {
        key: 'scope',
        header: t('accessKeys.columns.scope'),
        width: proportional(1.35),
        renderCell: (record): ReactNode => (
          <dl {...stylex.props(styles.scopeCell)}>
            {record.scopeRows.map((scope) => (
              <div key={scope.label} {...stylex.props(styles.scopeRow)}>
                <dt {...stylex.props(styles.scopeTerm)}>{scope.label}</dt>
                <dd {...stylex.props(styles.scopeValue)} title={scope.value}>
                  {scope.value}
                </dd>
              </div>
            ))}
          </dl>
        ),
      },
      {
        key: 'limits',
        header: t('accessKeys.columns.limits'),
        width: pixel(110),
        renderCell: (record): ReactNode => (
          <span {...stylex.props(styles.limitsCell)}>
            {record.limits.map((limit) => (
              <span key={limit}>{limit}</span>
            ))}
          </span>
        ),
      },
      {
        key: 'lastRequest',
        header: t('accessKeys.columns.lastRequest'),
        width: pixel(120),
        renderCell: (record): ReactNode => (
          <span {...stylex.props(styles.timeCell)}>
            <RelativeInstant
              instant={record.lastRequestAt}
              emptyLabel={t('accessKeys.collection.neverRequested')}
            />
          </span>
        ),
      },
      {
        key: 'actions',
        header: t('accessKeys.columns.actions'),
        width: pixel(170),
        renderCell: (record): ReactNode => (
          <AccessKeyRowActions
            item={source(record.id)}
            status={record.status}
            name={record.name}
            costLimitRuleCount={record.costLimitRuleCount}
            total={total}
            busy={busyIds.has(record.id)}
            locked={lockedIds.has(record.id)}
            onToggle={onToggle}
            onReset={onReset}
            onDeleted={onDeleted}
            onOpen={onOpen}
          />
        ),
      },
  ]

  return (
    <Table
      data={presentations as AccessKeyRow[]}
      columns={columns}
      density="compact"
      dividers="rows"
      hasHover
      aria-label={t('accessKeys.collection.tableLabel')}
      rowIndexStart={(page - 1) * pageSize + 1}
      rowCount={filteredTotal}
    />
  )
}

/** Per-row action cluster — owns the open state for its dialogs (renderCell
 * itself is a plain function, so state lives in this leaf component). */
function AccessKeyRowActions({
  item,
  status,
  name,
  costLimitRuleCount,
  total,
  busy,
  locked,
  onToggle,
  onReset,
  onDeleted,
  onOpen,
}: {
  item: AccessKeyCollectionItemDto
  status: AccessKeyDto['status']
  name: string
  costLimitRuleCount: number
  total: number
  busy: boolean
  locked: boolean
  onToggle(accessKey: AccessKeyCollectionItemDto): void
  onReset(name: string): void
  onDeleted(name: string): void
  onOpen(accessKey: AccessKeyCollectionItemDto, trigger: HTMLElement): void
}) {
  const t = useT()
  const [resetOpen, setResetOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)

  return (
    <span {...stylex.props(styles.actionsCell)}>
      <Button
        variant="secondary"
        size="sm"
        isLoading={busy}
        isDisabled={locked}
        label={status === 'active' ? t('accessKeys.actions.disable') : t('accessKeys.actions.enable')}
        onClick={() => onToggle(item)}
      />
      {costLimitRuleCount > 0 && (
        <>
          <IconButton
            variant="ghost"
            size="sm"
            label={t('accessKeys.reset.open')}
            icon={<RotateCcw size={15} />}
            isDisabled={busy || locked}
            onClick={() => setResetOpen(true)}
          />
          <AccessKeyCostLimitResetDialog
            accessKey={item}
            open={resetOpen}
            onOpenChange={setResetOpen}
            onReset={() => onReset(name)}
          />
        </>
      )}
      <IconButton
        variant="ghost"
        size="sm"
        label={t('accessKeys.delete.open')}
        icon={<Trash2 size={15} />}
        isDisabled={busy || locked}
        onClick={() => setDeleteOpen(true)}
      />
      <AccessKeyDeleteDialog
        accessKey={item}
        total={total}
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        onDeleted={onDeleted}
      />
      <IconButton
        variant="ghost"
        size="sm"
        label={t('accessKeys.collection.openDetailsFor', { name })}
        icon={<ArrowRight size={15} />}
        isDisabled={busy || locked}
        onClick={(event) => onOpen(item, event.currentTarget)}
      />
    </span>
  )
}

// web/src/frontends/classic/features/access-keys/AccessKeyCollection.vue
<script setup lang="ts">
import { ArrowRight, RotateCcw, Trash2 } from '@lucide/vue'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import { useApiClient } from '@/app/api-client-context'
import type { AccessKeyCollectionItemDto, GroupOptionDto } from '@shared/control/types'
import { revealAccessKey } from '@/app/resources/access-keys'
import { useAbortControllerPool } from '@/app/use-abort-controller-pool'
import LedgerRecordList from '@/components/collection/LedgerRecordList.vue'
import AppButton from '@/components/ui/AppButton.vue'
import AppRelativeTime from '@/components/ui/AppRelativeTime.vue'
import CopyChip from '@/components/ui/CopyChip.vue'
import IconButton from '@/components/ui/IconButton.vue'
import OverflowTooltip from '@/components/ui/OverflowTooltip.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'

import AccessKeyDeleteDialog from './AccessKeyDeleteDialog.vue'
import AccessKeyCostLimitResetDialog from './AccessKeyCostLimitResetDialog.vue'
import { presentAccessKeyCollection } from './access-key-presenter'

const props = defineProps<{
  accessKeys: readonly AccessKeyCollectionItemDto[]
  groups: readonly GroupOptionDto[]
  total: number
  filteredTotal: number
  page: number
  pageSize: number
  busyIds: ReadonlySet<number>
  lockedIds: ReadonlySet<number>
}>()
const emit = defineEmits<{
  open: [accessKey: AccessKeyCollectionItemDto, trigger: HTMLElement]
  toggle: [accessKey: AccessKeyCollectionItemDto]
  deleted: [name: string]
  reset: [name: string]
}>()
const client = useApiClient()
const { locale, t } = useI18n()
const copyControllers = useAbortControllerPool()
const copyGeneration = ref(0)
const sources = computed(
  () => new Map(props.accessKeys.map((accessKey) => [accessKey.id, accessKey])),
)

const presentations = computed(() =>
  presentAccessKeyCollection(props.accessKeys, props.groups, {
    locale: locale.value,
    labels: {
      groups: t('accessKeys.filterGroups'),
      protocols: t('accessKeys.filterProtocols'),
      models: t('accessKeys.filterModels'),
      allGroups: t('accessKeys.allGroups'),
      allProtocols: t('accessKeys.allProtocols'),
      allModels: t('accessKeys.allModels'),
      unlimited: t('accessKeys.unlimited'),
      costRules: (count) => t('accessKeys.costLimits.ruleCount', { count }),
      priceMultiplier: (value) => t('common.priceMultiplier.value', { value }),
    },
    protocolLabel: (protocol) => protocol,
  }),
)
function source(id: number): AccessKeyCollectionItemDto {
  const accessKey = sources.value.get(id)
  if (!accessKey) throw new Error(`ACCESS_KEY_SOURCE_MISSING:${id}`)
  return accessKey
}

async function resolveCopyValue(id: number): Promise<string> {
  const controller = copyControllers.create()
  try {
    const result = await revealAccessKey(client, id, controller.signal)
    return result.key
  } finally {
    copyControllers.release(controller)
  }
}

function conceal(): void {
  copyGeneration.value++
  copyControllers.abortAll()
}

defineExpose({ conceal })

watch(
  () => [props.page, props.accessKeys.map(({ id }) => id).join(',')],
  () => conceal(),
)
</script>

<template>
  <LedgerRecordList
    :label="t('accessKeys.collection.tableLabel')"
    :row-count="filteredTotal + 1"
    grid-class="access-keys-record-grid"
  >
    <template #header>
      <span role="columnheader">{{ t('accessKeys.columns.name') }}</span>
      <span role="columnheader">{{ t('accessKeys.columns.key') }}</span>
      <span role="columnheader">{{ t('accessKeys.columns.status') }}</span>
      <span role="columnheader">{{ t('accessKeys.columns.scope') }}</span>
      <span role="columnheader">{{ t('accessKeys.columns.limits') }}</span>
      <span role="columnheader">{{ t('accessKeys.columns.lastRequest') }}</span>
      <span role="columnheader">{{ t('accessKeys.columns.actions') }}</span>
    </template>

    <article
      v-for="(record, index) in presentations"
      :key="record.id"
      class="ledger-record-list__record access-key-record"
      role="row"
      :aria-rowindex="(page - 1) * pageSize + index + 2"
    >
      <div class="ledger-record-list__cell access-key-name" role="cell">
        <span>{{ record.name }}</span>
      </div>

      <div class="ledger-record-list__cell access-key-secret-cell" role="cell">
        <span class="mobile-label">{{ t('accessKeys.columns.key') }}</span>
        <CopyChip
          :key="`${copyGeneration}:${source(record.id).updated_at_ms}`"
          layout="trailing"
          :value="record.maskedKey"
          :label="t('accessKeys.copy')"
          :success-label="t('common.copied')"
          :failure-label="t('common.copyFailed')"
          :resolve-value="() => resolveCopyValue(record.id)"
        />
      </div>

      <div class="ledger-record-list__cell access-key-status" role="cell">
        <span class="mobile-label">{{ t('accessKeys.columns.status') }}</span>
        <StatusBadge :tone="record.status === 'active' ? 'success' : 'neutral'">
          {{ t(`accessKeys.status.${record.status}`) }}
        </StatusBadge>
        <StatusBadge v-if="record.expired" tone="danger" size="compact">
          {{ t('accessKeys.status.expired') }}
        </StatusBadge>
        <StatusBadge v-if="record.ipRestricted" tone="neutral" size="compact">
          {{ t('accessKeys.status.ipRestricted') }}
        </StatusBadge>
        <StatusBadge v-if="record.quotaExhausted" tone="danger" size="compact">
          {{ t('accessKeys.costLimits.exhausted') }}
        </StatusBadge>
      </div>

      <div class="ledger-record-list__cell access-key-scope" role="cell">
        <span class="mobile-label">{{ t('accessKeys.columns.scope') }}</span>
        <dl>
          <div v-for="scope in record.scopeRows" :key="scope.label">
            <dt>{{ scope.label }}</dt>
            <OverflowTooltip as="dd" :content="scope.value">{{ scope.value }}</OverflowTooltip>
          </div>
        </dl>
      </div>

      <div class="ledger-record-list__cell access-key-rpm" role="cell">
        <span class="mobile-label">{{ t('accessKeys.columns.limits') }}</span>
        <span v-for="limit in record.limits" :key="limit">{{ limit }}</span>
      </div>

      <div class="ledger-record-list__cell access-key-last-request" role="cell">
        <span class="mobile-label">{{ t('accessKeys.columns.lastRequest') }}</span>
        <AppRelativeTime
          :instant="record.lastRequestAt"
          :locale="locale"
          :empty-label="t('accessKeys.collection.neverRequested')"
        />
      </div>

      <div class="ledger-record-list__cell record-actions" role="cell">
        <AppButton
          variant="secondary"
          :tone="record.status === 'active' ? 'warning' : 'success'"
          size="compact"
          :busy="busyIds.has(record.id)"
          :disabled="lockedIds.has(record.id)"
          @click="emit('toggle', source(record.id))"
        >
          {{
            record.status === 'active'
              ? t('accessKeys.actions.disable')
              : t('accessKeys.actions.enable')
          }}
        </AppButton>
        <AccessKeyCostLimitResetDialog
          v-if="record.costLimitRuleCount > 0"
          :access-key="source(record.id)"
          @reset="emit('reset', $event)"
        >
          <template #trigger="{ open }">
            <IconButton
              variant="ghost"
              size="compact"
              :label="t('accessKeys.reset.open')"
              :disabled="busyIds.has(record.id) || lockedIds.has(record.id)"
              @click="open"
            >
              <RotateCcw :size="15" aria-hidden="true" />
            </IconButton>
          </template>
        </AccessKeyCostLimitResetDialog>
        <AccessKeyDeleteDialog
          :access-key="source(record.id)"
          :total="total"
          @deleted="emit('deleted', $event)"
        >
          <template #trigger="{ open }">
            <IconButton
              variant="ghost"
              tone="danger"
              size="compact"
              :label="t('accessKeys.delete.open')"
              :disabled="busyIds.has(record.id) || lockedIds.has(record.id)"
              @click="open"
            >
              <Trash2 :size="15" aria-hidden="true" />
            </IconButton>
          </template>
        </AccessKeyDeleteDialog>
        <IconButton
          variant="ghost"
          size="compact"
          :label="t('accessKeys.collection.openDetailsFor', { name: record.name })"
          :disabled="busyIds.has(record.id) || lockedIds.has(record.id)"
          @click="emit('open', source(record.id), $event.currentTarget as HTMLElement)"
        >
          <ArrowRight :size="15" aria-hidden="true" />
        </IconButton>
      </div>
    </article>
  </LedgerRecordList>
</template>

<style scoped>
.access-keys-record-grid {
  --ledger-record-list-grid: minmax(132px, 1.08fr) minmax(184px, 1.3fr) 102px minmax(190px, 1.35fr)
    92px minmax(126px, 0.9fr) minmax(158px, 1.05fr);
  --ledger-record-list-column-gap: 14px;
}

.access-key-name {
  min-width: 0;
  color: var(--color-text);
  font-weight: 600;
  overflow-wrap: anywhere;
}

.access-key-secret-cell,
.access-key-status,
.access-key-scope,
.access-key-rpm,
.access-key-last-request {
  min-width: 0;
}

.access-key-rpm {
  display: grid;
  gap: 2px;
}

.access-key-status {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 5px;
}

.access-key-scope dl {
  display: grid;
  gap: 3px;
  margin: 0;
}

.access-key-scope dl > div {
  display: grid;
  min-width: 0;
  grid-template-columns: 46px minmax(0, 1fr);
  align-items: baseline;
  gap: 6px;
}

.access-key-scope dt {
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
  text-align: right;
}

.access-key-scope dd {
  min-width: 0;
  margin: 0;
  color: var(--color-text-muted);
  font-size: var(--text-label-xs);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.access-key-rpm,
.access-key-last-request {
  color: var(--color-text-muted);
  font-family: var(--font-mono);
  font-size: var(--text-sm);
}

.record-actions {
  display: flex;
  align-items: center;
  gap: 4px;
}

.mobile-label {
  display: none;
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
  font-weight: 560;
}

@media (max-width: 1120px) {
  .access-keys-record-grid {
    --ledger-record-list-grid: minmax(110px, 1.05fr) minmax(156px, 1.2fr) 90px minmax(164px, 1.25fr)
      78px minmax(96px, 0.8fr) minmax(148px, 1fr);
    --ledger-record-list-column-gap: 10px;
  }

  .access-key-last-request :deep(.app-relative-time) {
    line-height: var(--line-compact);
    overflow-wrap: anywhere;
    white-space: normal;
  }
}

@media (max-width: 1023px) and (min-width: 861px) {
  .access-keys-record-grid {
    --ledger-record-list-grid: minmax(110px, 1fr) minmax(156px, 1.2fr) 90px minmax(164px, 1.25fr)
      minmax(144px, 1fr);
  }

  .access-keys-record-grid :deep(.ledger-record-list__header > :nth-child(5)),
  .access-keys-record-grid :deep(.ledger-record-list__header > :nth-child(6)),
  .access-key-rpm,
  .access-key-last-request {
    display: none;
  }
}

@media (max-width: 860px) {
  .access-key-name {
    grid-column: 1 / -1;
  }

  .access-key-secret-cell {
    grid-column: 1 / -1;
    border-top: 1px solid var(--color-border-subtle);
    border-bottom: 1px solid var(--color-border-subtle);
    padding: 11px 0;
  }

  .access-key-scope {
    grid-column: 1 / -1;
  }

  .access-key-status,
  .access-key-rpm,
  .access-key-last-request {
    display: grid;
    align-content: start;
    gap: 5px;
  }

  .access-key-rpm {
    border-right: 1px solid var(--color-border-subtle);
    padding-right: 12px;
  }

  .record-actions {
    grid-column: 1 / -1;
    flex-wrap: wrap;
    border-top: 1px solid var(--color-border-subtle);
    padding-top: 11px;
  }

  .record-actions :deep(.app-button),
  .record-actions :deep(.icon-button) {
    min-height: var(--touch-target);
  }

  .mobile-label {
    display: inline;
  }
}

@media (max-width: 560px) {
  .access-keys-record-grid {
    --ledger-record-list-card-grid: 76px minmax(0, 1fr);
  }

  .access-key-scope dl > div {
    grid-template-columns: 42px minmax(0, 1fr);
  }
}
</style>
