// web/src/frontends/classic/features/settings/SystemInfoSection.vue
<script setup lang="ts">
import { RefreshCw } from '@lucide/vue'
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import { RequestCancelledError } from '@shared/http/errors'
import { useApiClient } from '@/app/api-client-context'
import { useStableLoading } from '@/app/loading-state'
import { controlQueryKeys } from '@shared/control/query-keys'
import {
  systemInfoQueryOptions,
  type DatabaseDriver,
  type SecretSource,
} from '@/app/resources/system-info'
import {
  getSystemUpdate,
  systemUpdateQueryOptions,
  type ReleaseUpdateDto,
} from '@/app/resources/system-update'
import AppButton from '@/components/ui/AppButton.vue'
import CopyButton from '@/components/ui/CopyButton.vue'
import AsyncRefreshIndicator from '@/components/ui/AsyncRefreshIndicator.vue'
import QueryFeedback from '@/components/ui/QueryFeedback.vue'
import SkeletonSurface from '@/components/ui/SkeletonSurface.vue'
import StatusBadge from '@/components/ui/StatusBadge.vue'
import Surface from '@/components/ui/Surface.vue'

const client = useApiClient()
const queryClient = useQueryClient()
const { t } = useI18n()
const infoQuery = useQuery(systemInfoQueryOptions(client))
const initialLoading = useStableLoading(
  () => infoQuery.isPending.value && infoQuery.data.value === undefined,
)
const infoRefreshing = computed(
  () => infoQuery.data.value !== undefined && infoQuery.isFetching.value,
)
const updateQuery = useQuery(systemUpdateQueryOptions(client))
const isDevelopmentBuild = computed(() =>
  /^v?\d+\.\d+\.\d+-dev(?:\.|$)/.test(infoQuery.data.value?.version ?? ''),
)
type UpdateCheckState =
  | { kind: 'checking' }
  | { kind: 'latest' }
  | { kind: 'available'; update: ReleaseUpdateDto }
  | { kind: 'failed' }

const manualUpdateCheck = ref<UpdateCheckState | null>(null)
const updateCheckPending = ref(false)
const updateCheck = computed<UpdateCheckState | null>(() => {
  if (manualUpdateCheck.value) return manualUpdateCheck.value
  const update = updateQuery.data.value?.update
  return update ? { kind: 'available', update } : null
})
const updateCheckTone = computed<'info' | 'success' | 'warning' | 'danger'>(() => {
  switch (updateCheck.value?.kind) {
    case 'latest':
      return 'success'
    case 'available':
      return 'warning'
    case 'failed':
      return 'danger'
    default:
      return 'info'
  }
})

function sourceLabel(source: SecretSource): string {
  return t(`settings.system.sources.${source}`)
}

function databaseLabel(database: DatabaseDriver): string {
  return t(`settings.system.databases.${database}`)
}

async function checkForUpdate(): Promise<void> {
  if (updateCheckPending.value) return
  const previousCheck = updateCheck.value
  updateCheckPending.value = true
  manualUpdateCheck.value = { kind: 'checking' }
  try {
    const result = await getSystemUpdate(client, undefined, true)
    queryClient.setQueryData(controlQueryKeys.systemUpdate(), result)
    manualUpdateCheck.value = result.update
      ? { kind: 'available', update: result.update }
      : { kind: 'latest' }
  } catch (error) {
    if (error instanceof RequestCancelledError) {
      manualUpdateCheck.value = previousCheck
      return
    }
    manualUpdateCheck.value = previousCheck ?? { kind: 'failed' }
  } finally {
    updateCheckPending.value = false
  }
}
</script>

<template>
  <section id="settings-system" class="settings-section" tabindex="-1">
    <header class="settings-section__heading">
      <h2>{{ t('settings.system.title') }}</h2>
      <p>{{ t('settings.system.description') }}</p>
    </header>

    <AsyncRefreshIndicator :active="infoRefreshing" :label="t('settings.system.loading')" />

    <SkeletonSurface
      v-if="(infoQuery.isPending.value && !infoQuery.data.value) || initialLoading"
      variant="panel"
      min-height="320px"
      :concealed="!initialLoading"
      :label="t('settings.system.loading')"
    />
    <QueryFeedback
      v-else-if="infoQuery.isError.value && !infoQuery.data.value"
      state="error"
      :message="t('settings.system.loadFailed')"
      :retry-label="t('common.retry')"
      @retry="infoQuery.refetch()"
    />
    <template v-else-if="infoQuery.data.value">
      <QueryFeedback
        v-if="infoQuery.isError.value"
        state="stale"
        :message="t('settings.system.stale')"
        :retry-label="t('common.retry')"
        @retry="infoQuery.refetch()"
      />
      <Surface variant="sunken" :padded="false" class="settings-system__panel">
        <dl class="settings-system__definition">
          <div class="settings-system__row">
            <dt>{{ t('settings.system.version') }}</dt>
            <dd class="settings-system__version">
              <span class="settings-system__mono">{{ infoQuery.data.value.version }}</span>
              <div v-if="!isDevelopmentBuild" class="settings-system__update-controls">
                <AppButton
                  variant="secondary"
                  size="compact"
                  :busy="updateCheckPending"
                  @click="checkForUpdate"
                >
                  <RefreshCw
                    :size="14"
                    aria-hidden="true"
                    :class="{ 'settings-system__refresh-icon--spinning': updateCheckPending }"
                  />
                  {{ t('settings.system.checkUpdate') }}
                </AppButton>
                <span
                  v-if="updateCheck"
                  class="settings-system__update-result"
                  :class="`settings-system__update-result--${updateCheckTone}`"
                  :role="updateCheck.kind === 'failed' ? 'alert' : 'status'"
                  :aria-live="updateCheck.kind === 'failed' ? 'assertive' : 'polite'"
                  aria-atomic="true"
                >
                  <template v-if="updateCheck.kind === 'checking'">
                    {{ t('settings.system.checkingUpdate') }}
                  </template>
                  <template v-else-if="updateCheck.kind === 'latest'">
                    {{ t('settings.system.latestVersion') }}
                  </template>
                  <template v-else-if="updateCheck.kind === 'available'">
                    {{
                      t('settings.system.updateAvailable', { version: updateCheck.update.version })
                    }}
                    <a
                      class="settings-system__update-link"
                      :href="updateCheck.update.release_url"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      {{ t('settings.system.viewRelease') }}
                    </a>
                  </template>
                  <template v-else>
                    {{ t('settings.system.checkUpdateFailed') }}
                  </template>
                </span>
              </div>
            </dd>
          </div>

          <div class="settings-system__row">
            <dt>{{ t('settings.system.deployment') }}</dt>
            <dd class="settings-system__inline">
              <StatusBadge size="compact">{{ t('settings.system.single') }}</StatusBadge>
              <StatusBadge size="compact">{{
                databaseLabel(infoQuery.data.value.deployment.database)
              }}</StatusBadge>
              <StatusBadge size="compact">{{ t('settings.system.singleBinary') }}</StatusBadge>
            </dd>
          </div>

          <div class="settings-system__row">
            <dt>{{ t('settings.system.dataDir') }}</dt>
            <dd class="settings-system__mono">{{ infoQuery.data.value.data_dir }}</dd>
          </div>

          <div class="settings-system__row">
            <dt>{{ t('settings.system.authKey') }}</dt>
            <dd class="settings-system__inline">
              <StatusBadge size="compact">{{
                sourceLabel(infoQuery.data.value.auth_key.source)
              }}</StatusBadge>
              <span
                v-if="infoQuery.data.value.auth_key.path"
                class="settings-system__path settings-system__mono"
              >
                <span>{{ infoQuery.data.value.auth_key.path }}</span>
                <CopyButton
                  :value="infoQuery.data.value.auth_key.path"
                  :label="t('settings.system.copyPath')"
                  :success-label="t('common.copied')"
                  :failure-label="t('common.copyFailed')"
                />
              </span>
            </dd>
          </div>

          <div class="settings-system__row">
            <dt>{{ t('settings.system.encryption') }}</dt>
            <dd class="settings-system__inline">
              <StatusBadge tone="success" size="compact">{{
                t('settings.system.enabled')
              }}</StatusBadge>
              <StatusBadge size="compact">{{
                sourceLabel(infoQuery.data.value.encryption.source)
              }}</StatusBadge>
              <span
                v-if="infoQuery.data.value.encryption.path"
                class="settings-system__path settings-system__mono"
              >
                <span>{{ infoQuery.data.value.encryption.path }}</span>
                <CopyButton
                  :value="infoQuery.data.value.encryption.path"
                  :label="t('settings.system.copyPath')"
                  :success-label="t('common.copied')"
                  :failure-label="t('common.copyFailed')"
                />
              </span>
            </dd>
          </div>
        </dl>
      </Surface>
      <p class="settings-system__security-note">{{ t('settings.system.securityNote') }}</p>
    </template>
  </section>
</template>

<style scoped>
.settings-section {
  display: grid;
}

.settings-section {
  gap: var(--space-4);
  scroll-margin-top: 76px;
}

.settings-section__heading h2,
.settings-section__heading p,
.settings-system__definition,
.settings-system__definition dd,
.settings-system__security-note {
  margin: 0;
}

.settings-section__heading h2 {
  font-size: var(--title-section);
  font-weight: 650;
}

.settings-section__heading p {
  margin-top: var(--space-1);
  color: var(--color-text-muted);
  font-size: var(--text-sm);
}

.settings-system__security-note {
  margin-top: var(--space-1);
  color: var(--color-text-muted);
  font-size: var(--text-label-xs);
}

.settings-section > .settings-system__panel {
  border-radius: var(--radius-control);
  padding: var(--space-4);
}

.settings-system__definition {
  display: grid;
}

.settings-system__row {
  display: grid;
  grid-template-columns: minmax(120px, 160px) minmax(0, 1fr);
  column-gap: var(--space-4);
}

.settings-system__definition dt,
.settings-system__definition dd {
  min-width: 0;
  border-bottom: 1px dashed var(--color-border-subtle);
  padding: 10px 0;
}

.settings-system__definition dt {
  display: flex;
  align-items: center;
  color: var(--color-text-muted);
  font-size: var(--text-label-xs);
  font-weight: 650;
}

.settings-system__definition dd {
  display: flex;
  align-items: center;
  color: var(--color-text-muted);
  font-size: var(--text-label-xs);
  overflow-wrap: anywhere;
}

.settings-system__row:last-child dt,
.settings-system__row:last-child dd {
  border-bottom: 0;
}

.settings-system__inline {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
}

.settings-system__path {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  align-items: center;
  gap: var(--space-2);
}

.settings-system__path > span:first-child {
  overflow-wrap: anywhere;
}

.settings-system__mono {
  font-family: var(--font-mono);
}

.settings-system__version {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-3);
}

.settings-system__update-controls {
  display: flex;
  min-width: 0;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--space-2);
}

.settings-system__update-result {
  display: inline-flex;
  align-items: center;
  gap: var(--space-1);
  min-width: 0;
}

.settings-system__update-result--info {
  color: var(--color-action);
}

.settings-system__update-result--success {
  color: var(--color-success);
}

.settings-system__update-result--warning {
  color: var(--color-warning);
}

.settings-system__update-result--danger {
  color: var(--color-danger);
}

.settings-system__update-link {
  color: currentColor;
  font-weight: 650;
  text-decoration: underline;
  text-underline-offset: 2px;
}

.settings-system__refresh-icon--spinning {
  animation: settings-system-refresh-spin 900ms linear infinite;
}

@keyframes settings-system-refresh-spin {
  to {
    transform: rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  .settings-system__refresh-icon--spinning {
    animation: none;
  }
}

@media (max-width: 760px) {
  .settings-system__row {
    grid-template-columns: 115px minmax(0, 1fr);
  }
}
</style>

// web/src/frontends/astryx/features/settings/SystemInfoSection.tsx
import { Badge, Button, Skeleton } from '@astryxdesign/core'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import * as stylex from '@stylexjs/stylex'
import { RefreshCw, TriangleAlert } from 'lucide-react'
import { useState } from 'react'

import { CopyButton } from '../../components/CopyButton'
import { useT } from '../../app/i18n'
import { useAppServices } from '../../app/services'
import { useStableLoading } from '../../app/collection-loading'
import { controlQueryKeys } from '@shared/control/query-keys'
import {
  systemInfoQueryOptions,
  type DatabaseDriver,
  type SecretSource,
} from '@shared/control/resources/system-info'
import {
  getSystemUpdate,
  systemUpdateQueryOptions,
  type ReleaseUpdateDto,
} from '@shared/control/resources/system-update'
import { RequestCancelledError } from '@shared/http/errors'
import { SettingsSectionFrame } from './section-tools'

const narrow = '@media (max-width: 760px)'

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const styles = stylex.create({
  panel: {
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--color-border-subtle)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-surface-sunken)',
    paddingBlock: 'var(--space-4)',
    paddingInline: 'var(--space-4)',
  },
  definition: {
    display: 'grid',
    margin: 0,
  },
  row: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(120px, 160px) minmax(0, 1fr)',
      [narrow]: '115px minmax(0, 1fr)',
    },
    columnGap: 'var(--space-4)',
  },
  term: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    borderBottomWidth: '1px',
    borderBottomStyle: 'dashed',
    borderBottomColor: 'var(--color-border-subtle)',
    paddingBlock: '10px',
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-label-xs)',
    fontWeight: 650,
  },
  termLast: {
    borderBottomWidth: 0,
  },
  detail: {
    display: 'flex',
    minWidth: 0,
    margin: 0,
    alignItems: 'center',
    borderBottomWidth: '1px',
    borderBottomStyle: 'dashed',
    borderBottomColor: 'var(--color-border-subtle)',
    paddingBlock: '10px',
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-label-xs)',
    overflowWrap: 'anywhere',
  },
  detailLast: {
    borderBottomWidth: 0,
  },
  inline: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 'var(--space-2)',
  },
  path: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 'var(--space-2)',
  },
  pathText: {
    overflowWrap: 'anywhere',
  },
  mono: {
    fontFamily: 'var(--font-mono)',
  },
  version: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 'var(--space-3)',
  },
  updateControls: {
    display: 'flex',
    minWidth: 0,
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 'var(--space-2)',
  },
  updateResult: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 'var(--space-1)',
    minWidth: 0,
  },
  updateInfo: { color: 'var(--color-action)' },
  updateSuccess: { color: 'var(--color-success)' },
  updateWarning: { color: 'var(--color-warning)' },
  updateDanger: { color: 'var(--color-danger)' },
  updateLink: {
    color: 'inherit',
    fontWeight: 650,
    textDecoration: 'underline',
    textUnderlineOffset: '2px',
  },
  refreshIcon: {
    animationName: {
      default: spin,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    animationDuration: '900ms',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
  errorBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-2)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--color-danger)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-danger-bg)',
    color: 'var(--color-danger)',
    paddingBlock: 'var(--space-3)',
    paddingInline: 'var(--space-4)',
    fontSize: 'var(--text-sm)',
  },
  staleBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-2)',
    color: 'var(--color-warning)',
    fontSize: 'var(--text-sm)',
  },
  securityNote: {
    margin: 0,
    marginTop: 'var(--space-1)',
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-label-xs)',
  },
})

type UpdateCheckState =
  | { kind: 'checking' }
  | { kind: 'latest' }
  | { kind: 'available'; update: ReleaseUpdateDto }
  | { kind: 'failed' }

export function SystemInfoSection() {
  const t = useT()
  const { apiClient } = useAppServices()
  const queryClient = useQueryClient()
  const infoQuery = useQuery(systemInfoQueryOptions(apiClient))
  const initialLoading = useStableLoading(
    infoQuery.isPending && infoQuery.data === undefined,
  )
  const infoRefreshing = infoQuery.data !== undefined && infoQuery.isFetching
  const updateQuery = useQuery(systemUpdateQueryOptions(apiClient))
  const isDevelopmentBuild = /^v?\d+\.\d+\.\d+-dev(?:\.|$)/.test(
    infoQuery.data?.version ?? '',
  )

  const [manualUpdateCheck, setManualUpdateCheck] = useState<UpdateCheckState | null>(null)
  const [updateCheckPending, setUpdateCheckPending] = useState(false)
  const updateCheck: UpdateCheckState | null =
    manualUpdateCheck ??
    (updateQuery.data?.update ? { kind: 'available', update: updateQuery.data.update } : null)
  const updateCheckTone =
    updateCheck?.kind === 'latest'
      ? 'success'
      : updateCheck?.kind === 'available'
        ? 'warning'
        : updateCheck?.kind === 'failed'
          ? 'danger'
          : 'info'

  const checkForUpdate = async (): Promise<void> => {
    if (updateCheckPending) return
    const previousCheck = updateCheck
    setUpdateCheckPending(true)
    setManualUpdateCheck({ kind: 'checking' })
    try {
      const result = await getSystemUpdate(apiClient, undefined, true)
      queryClient.setQueryData(controlQueryKeys.systemUpdate(), result)
      setManualUpdateCheck(
        result.update ? { kind: 'available', update: result.update } : { kind: 'latest' },
      )
    } catch (error) {
      if (error instanceof RequestCancelledError) {
        setManualUpdateCheck(previousCheck)
        return
      }
      setManualUpdateCheck(previousCheck ?? { kind: 'failed' })
    } finally {
      setUpdateCheckPending(false)
    }
  }

  const sourceLabel = (source: SecretSource): string => t(`settings.system.sources.${source}`)
  const databaseLabel = (database: DatabaseDriver): string =>
    t(`settings.system.databases.${database}`)

  const info = infoQuery.data

  return (
    <SettingsSectionFrame
      id="settings-system"
      title={t('settings.system.title')}
      description={t('settings.system.description')}
    >
      <span aria-live="polite" style={{ position: 'absolute', width: 1, height: 1, overflow: 'hidden', clipPath: 'inset(50%)' }}>
        {infoRefreshing ? t('settings.system.loading') : ''}
      </span>

      {(infoQuery.isPending && info === undefined) || initialLoading ? (
        <div role="status" aria-label={t('settings.system.loading')} style={{ minHeight: 320 }}>
          <Skeleton height={320} radius={2} />
        </div>
      ) : infoQuery.isError && info === undefined ? (
        <div {...stylex.props(styles.errorBox)} role="alert">
          <TriangleAlert size={16} aria-hidden />
          <span>{t('settings.system.loadFailed')}</span>
          <Button
            variant="secondary"
            size="sm"
            label={t('common.retry')}
            onClick={() => void infoQuery.refetch()}
          />
        </div>
      ) : info !== undefined ? (
        <>
          {infoQuery.isError && (
            <div {...stylex.props(styles.staleBanner)} role="status">
              <TriangleAlert size={13} aria-hidden />
              <span>{t('settings.system.stale')}</span>
              <Button
                variant="secondary"
                size="sm"
                label={t('common.retry')}
                onClick={() => void infoQuery.refetch()}
              />
            </div>
          )}
          <div {...stylex.props(styles.panel)}>
            <dl {...stylex.props(styles.definition)}>
              {(
                [
                  {
                    term: t('settings.system.version'),
                    detail: (
                      <span {...stylex.props(styles.version)}>
                        <span {...stylex.props(styles.mono)}>{info.version}</span>
                        {!isDevelopmentBuild && (
                          <span {...stylex.props(styles.updateControls)}>
                            <Button
                              variant="secondary"
                              size="sm"
                              isLoading={updateCheckPending}
                              label={t('settings.system.checkUpdate')}
                              icon={
                                <RefreshCw
                                  size={14}
                                  aria-hidden
                                  {...(updateCheckPending
                                    ? stylex.props(styles.refreshIcon)
                                    : {})}
                                />
                              }
                              onClick={() => void checkForUpdate()}
                            />
                            {updateCheck && (
                              <span
                                {...stylex.props(
                                  styles.updateResult,
                                  updateCheckTone === 'success' && styles.updateSuccess,
                                  updateCheckTone === 'warning' && styles.updateWarning,
                                  updateCheckTone === 'danger' && styles.updateDanger,
                                  updateCheckTone === 'info' && styles.updateInfo,
                                )}
                                role={updateCheck.kind === 'failed' ? 'alert' : 'status'}
                                aria-live={
                                  updateCheck.kind === 'failed' ? 'assertive' : 'polite'
                                }
                                aria-atomic="true"
                              >
                                {updateCheck.kind === 'checking' &&
                                  t('settings.system.checkingUpdate')}
                                {updateCheck.kind === 'latest' &&
                                  t('settings.system.latestVersion')}
                                {updateCheck.kind === 'available' && (
                                  <>
                                    {t('settings.system.updateAvailable', {
                                      version: updateCheck.update.version,
                                    })}
                                    <a
                                      {...stylex.props(styles.updateLink)}
                                      href={updateCheck.update.release_url}
                                      target="_blank"
                                      rel="noopener noreferrer"
                                    >
                                      {t('settings.system.viewRelease')}
                                    </a>
                                  </>
                                )}
                                {updateCheck.kind === 'failed' &&
                                  t('settings.system.checkUpdateFailed')}
                              </span>
                            )}
                          </span>
                        )}
                      </span>
                    ),
                  },
                  {
                    term: t('settings.system.deployment'),
                    detail: (
                      <span {...stylex.props(styles.inline)}>
                        <Badge label={t('settings.system.single')} />
                        <Badge label={databaseLabel(info.deployment.database)} />
                        <Badge label={t('settings.system.singleBinary')} />
                      </span>
                    ),
                  },
                  { term: t('settings.system.dataDir'), detail: info.data_dir, mono: true },
                  {
                    term: t('settings.system.authKey'),
                    detail: (
                      <span {...stylex.props(styles.inline)}>
                        <Badge label={sourceLabel(info.auth_key.source)} />
                        {info.auth_key.path && (
                          <span {...stylex.props(styles.path, styles.mono)}>
                            <span {...stylex.props(styles.pathText)}>
                              {info.auth_key.path}
                            </span>
                            <CopyButton
                              value={info.auth_key.path}
                              label={t('settings.system.copyPath')}
                              successLabel={t('common.copied')}
                              failureLabel={t('common.copyFailed')}
                            />
                          </span>
                        )}
                      </span>
                    ),
                  },
                  {
                    term: t('settings.system.encryption'),
                    detail: (
                      <span {...stylex.props(styles.inline)}>
                        <Badge variant="success" label={t('settings.system.enabled')} />
                        <Badge label={sourceLabel(info.encryption.source)} />
                        {info.encryption.path && (
                          <span {...stylex.props(styles.path, styles.mono)}>
                            <span {...stylex.props(styles.pathText)}>
                              {info.encryption.path}
                            </span>
                            <CopyButton
                              value={info.encryption.path}
                              label={t('settings.system.copyPath')}
                              successLabel={t('common.copied')}
                              failureLabel={t('common.copyFailed')}
                            />
                          </span>
                        )}
                      </span>
                    ),
                  },
                ] as const
              ).map((row, index, list) => (
                <div key={row.term} {...stylex.props(styles.row)}>
                  <dt {...stylex.props(styles.term, index === list.length - 1 && styles.termLast)}>
                    {row.term}
                  </dt>
                  <dd
                    {...stylex.props(
                      styles.detail,
                      index === list.length - 1 && styles.detailLast,
                    )}
                  >
                    {'mono' in row && row.mono ? (
                      <span {...stylex.props(styles.mono)}>{row.detail as string}</span>
                    ) : (
                      row.detail
                    )}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
          <p {...stylex.props(styles.securityNote)}>{t('settings.system.securityNote')}</p>
        </>
      ) : null}
    </SettingsSectionFrame>
  )
}
