// web/src/frontends/astryx/features/groups/GroupDetailView.tsx
import * as stylex from '@stylexjs/stylex'
import { Badge, Button, EmptyState, Skeleton } from '@astryxdesign/core'
import { useQuery } from '@tanstack/react-query'
import { useRouterState } from '@tanstack/react-router'
import { RefreshCw, TriangleAlert } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'

import type { CredentialCollectionFilters, CredentialItemDto } from '@shared/control/types'
import { credentialCollectionQueryOptions } from '@shared/control/resources/credentials'
import {
  groupModelsQueryOptions,
  groupSettingsQueryOptions,
  groupSummaryQueryOptions,
} from '@shared/control/resources/groups'
import { pagePath } from '@shared/routing/page-routes'
import { parseCredentialRouteQuery, parsePositiveId } from '@shared/routing/group-detail-route'
import { scalarRouteQuery, type SharedRouteQuery } from '@shared/routing/route-query'

import { useStableLoading } from '../../app/collection-loading'
import { useT } from '../../app/i18n'
import { RouteLink } from '../../app/route-link'
import { useAppServices } from '../../app/services'
import { StickySaveBar } from '../../components/StickySaveBar'
import { GroupApiKeyEditor } from './credentials/GroupApiKeyEditor'
import { GroupCredentialsTab } from './credentials/GroupCredentialsTab'
import { GroupDeleteDialog } from './settings/GroupDeleteDialog'
import { GroupSettingsTab } from './settings/GroupSettingsTab'
import { GroupModelsTab } from './models/GroupModelsTab'
import { GroupHeader } from './GroupHeader'
import type { GroupEditorHandle, GroupEditorState, GroupModelsEditorHandle } from './editor-handles'
import { credentialStatusBadgeVariant, type OperationalStatus } from './credential-status'

const idleEditorState: GroupEditorState = {
  dirty: false,
  pending: false,
  error: '',
  saved: false,
}

const unifiedCredentialFilters: CredentialCollectionFilters = { page: 1, page_size: 20 }

const spin = stylex.keyframes({
  to: { transform: 'rotate(360deg)' },
})

const styles = stylex.create({
  page: {
    display: 'grid',
    alignContent: 'start',
    gap: 'var(--space-3)',
    paddingBottom: 'var(--space-3)',
  },
  invalid: {
    display: 'grid',
    maxWidth: '640px',
    gap: 'var(--space-3)',
  },
  invalidHeading: {
    margin: 0,
  },
  invalidText: {
    margin: 0,
    color: 'var(--color-text-muted)',
  },
  credentials: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr)',
    rowGap: '8px',
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingTop: { default: '12px', '@media (max-width: 640px)': '10px' },
    paddingBottom: { default: '12px', '@media (max-width: 640px)': '10px' },
  },
  credentialList: {
    display: 'grid',
    minWidth: 0,
    gridColumn: '1',
    gap: 6,
  },
  credentialRow: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'flex-end',
    gap: 'var(--space-3)',
  },
  credentialField: {
    display: 'grid',
    minWidth: 0,
    flexGrow: 1,
    gap: 4,
  },
  credentialFieldLabel: {
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-sm)',
  },
  credentialFieldInput: {
    width: '100%',
    minHeight: 'var(--control-md)',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'var(--color-border-control)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-surface)',
    color: 'var(--color-text)',
    paddingTop: 0,
    paddingBottom: 0,
    paddingInline: 'var(--space-3)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'inherit',
  },
  credentialRowEnd: {
    flexShrink: 0,
    marginBottom: '1px',
  },
  empty: {
    gridColumn: '1',
    margin: 0,
    color: 'var(--color-text-muted)',
    fontSize: 'var(--text-sm)',
  },
  staleBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-2)',
    color: 'var(--color-warning)',
    fontSize: 'var(--text-sm)',
  },
  refreshing: {
    color: 'var(--color-text-faint)',
    animationName: {
      default: spin,
      '@media (prefers-reduced-motion: reduce)': 'none',
    },
    animationDuration: '900ms',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
})

function unifiedCredentialSummary(
  credential: CredentialItemDto,
  t: ReturnType<typeof useT>,
): { status: OperationalStatus; label: string } {
  if (credential.auth_state === 'refreshing') {
    return { status: 'unknown', label: t('group.credentials.subscription.status.refreshing') }
  }
  if (credential.auth_state === 'reauthorization_required') {
    return {
      status: 'unavailable',
      label: t('group.credentials.subscription.status.needs_reauth'),
    }
  }
  if (credential.auth_state === 'outcome_unknown') {
    return { status: 'unknown', label: t('group.credentials.subscription.status.outcome_unknown') }
  }
  return {
    status: credential.effective_status,
    label: t(`group.credentials.effective.${credential.effective_status}`),
  }
}

export function GroupDetailView() {
  const t = useT()
  const { apiClient, queryClient } = useAppServices()
  const { id, rawSearch } = useRouterState({
    select: (state) => ({
      id: (state.matches.at(-1)?.params as { id?: string } | undefined)?.id,
      rawSearch: state.location.search as SharedRouteQuery,
    }),
  })
  const groupId = parsePositiveId(id)
  const summaryQuery = useQuery(groupSummaryQueryOptions(apiClient, groupId))
  // The summary omits the enabled flag, so the models tab reads it from the
  // settings query (same cache entry the settings tab prefetches).
  const settingsQuery = useQuery(groupSettingsQueryOptions(apiClient, groupId))
  const credentialsQuery = useQuery({
    ...credentialCollectionQueryOptions(apiClient, groupId ?? 0, unifiedCredentialFilters),
    enabled: groupId !== undefined,
  })
  // managementOpen reads the RAW query — an absent/unknown tab renders the
  // unified settings+models view, matching classic.
  const managementOpen = scalarRouteQuery(rawSearch.tab) === 'credentials'
  const initialLoading = useStableLoading(summaryQuery.isPending && summaryQuery.data === undefined)
  const summaryRefreshing = summaryQuery.data !== undefined && summaryQuery.isFetching

  const [settingsState, setSettingsState] = useState<GroupEditorState>(idleEditorState)
  const [modelsState, setModelsState] = useState<GroupEditorState>(idleEditorState)
  const [deletePending, setDeletePending] = useState(false)
  const settingsEditorRef = useRef<GroupEditorHandle>(null)
  const modelsEditorRef = useRef<GroupModelsEditorHandle>(null)

  const unifiedDirty = settingsState.dirty || modelsState.dirty
  const unifiedPending = settingsState.pending || modelsState.pending || deletePending
  const unifiedInvalid = settingsState.invalid === true || (modelsState.invalidRowCount ?? 0) > 0
  const unifiedError = settingsState.error || modelsState.error
  const unifiedSaved = !unifiedDirty && (settingsState.saved || modelsState.saved)
  const unifiedSaveStatus: 'idle' | 'saved' | 'error' = unifiedError
    ? 'error'
    : unifiedSaved
      ? 'saved'
      : 'idle'
  const unifiedErrorActionLabel = modelsState.invalidRowCount
    ? t('group.modelEditor.locateFirstInvalid')
    : ''

  function saveUnified(): void {
    if (settingsState.dirty) settingsEditorRef.current?.requestSave()
    if (modelsState.dirty) modelsEditorRef.current?.requestSave()
  }

  function discardUnified(): void {
    if (settingsState.dirty) settingsEditorRef.current?.discard()
    if (modelsState.dirty) modelsEditorRef.current?.discard()
  }

  // Warm the tab queries as soon as the id resolves — classic prefetches on
  // the same immediate groupId watch.
  useEffect(() => {
    if (groupId === undefined) return
    void Promise.allSettled([
      queryClient.prefetchQuery(
        credentialCollectionQueryOptions(apiClient, groupId, parseCredentialRouteQuery(rawSearch)),
      ),
      queryClient.prefetchQuery(groupModelsQueryOptions(apiClient, groupId)),
      queryClient.prefetchQuery(groupSettingsQueryOptions(apiClient, groupId)),
    ])
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [groupId, apiClient, queryClient])

  return (
    <section {...stylex.props(styles.page)} aria-labelledby="group-detail-title">
      {groupId === undefined ? (
        <div {...stylex.props(styles.invalid)} role="alert">
          <h1 id="group-detail-title" {...stylex.props(styles.invalidHeading)}>
            {t('group.invalidTitle')}
          </h1>
          <p {...stylex.props(styles.invalidText)}>{t('group.invalidDescription')}</p>
          <RouteLink to={pagePath('groups')}>{t('group.backToGroups')}</RouteLink>
        </div>
      ) : (
        <>
          {summaryRefreshing && (
            <div role="status" aria-label={t('group.loading')} {...stylex.props(styles.refreshing)}>
              <RefreshCw size={13} aria-hidden />
            </div>
          )}
          {summaryQuery.isPending || initialLoading ? (
            <div role="status" aria-label={t('group.loading')}>
              <Skeleton height={220} radius={2} />
            </div>
          ) : summaryQuery.isError && !summaryQuery.data ? (
            <div role="alert">
              <EmptyState
                title={t('group.loadFailed')}
                icon={<TriangleAlert size={20} />}
                actions={
                  <Button
                    variant="secondary"
                    size="sm"
                    label={t('common.retry')}
                    onClick={() => void summaryQuery.refetch()}
                  />
                }
              />
            </div>
          ) : summaryQuery.data ? (
            <>
              {summaryQuery.isError && (
                <div {...stylex.props(styles.staleBanner)} role="status">
                  <TriangleAlert size={13} aria-hidden />
                  <span>{t('group.stale')}</span>
                  <Button
                    variant="secondary"
                    size="sm"
                    label={t('common.retry')}
                    onClick={() => void summaryQuery.refetch()}
                  />
                </div>
              )}
              <GroupHeader group={summaryQuery.data} />
              {managementOpen ? (
                <GroupCredentialsTab
                  key={`management-${groupId}`}
                  groupId={groupId}
                  channelId={summaryQuery.data.channel_id}
                  connectionType={summaryQuery.data.connection_type}
                />
              ) : (
                <>
                  <GroupSettingsTab
                    ref={settingsEditorRef}
                    key={`settings-${groupId}`}
                    groupId={groupId}
                    unified
                    blocked={deletePending}
                    onStateChange={setSettingsState}
                  />
                  <section
                    aria-label={t('group.credentials.title')}
                    {...stylex.props(styles.credentials)}
                  >
                    {credentialsQuery.data?.items.length ? (
                      <div {...stylex.props(styles.credentialList)}>
                        {credentialsQuery.data.items.map((credential) => {
                          const summary = unifiedCredentialSummary(credential, t)
                          return (
                            <div key={credential.mask} {...stylex.props(styles.credentialRow)}>
                              {credential.connection_type === 'subscription' ? (
                                <label {...stylex.props(styles.credentialField)}>
                                  <span {...stylex.props(styles.credentialFieldLabel)}>
                                    {t('group.credentials.full.kind.account')}
                                  </span>
                                  <input
                                    {...stylex.props(styles.credentialFieldInput)}
                                    value={credential.mask}
                                    readOnly
                                    autoComplete="off"
                                  />
                                </label>
                              ) : (
                                <GroupApiKeyEditor
                                  groupId={groupId}
                                  credential={credential}
                                  disabled={unifiedPending}
                                />
                              )}
                              <span {...stylex.props(styles.credentialRowEnd)}>
                                <Badge
                                  variant={credentialStatusBadgeVariant(summary.status)}
                                  label={summary.label}
                                />
                              </span>
                            </div>
                          )
                        })}
                      </div>
                    ) : (
                      <p {...stylex.props(styles.empty)}>{t('group.unified.noCredentials')}</p>
                    )}
                  </section>
                  <GroupModelsTab
                    ref={modelsEditorRef}
                    key={`models-${groupId}`}
                    groupId={groupId}
                    channelId={summaryQuery.data.channel_id}
                    enabled={settingsQuery.data?.enabled ?? true}
                    unified
                    blocked={deletePending}
                    readonlyRouteFields
                    onStateChange={setModelsState}
                  />
                  {/* Unified-mode portal target: GroupSettingsTab portals its
                      advanced section here via createPortal. Contractual id. */}
                  <div id="group-settings-advanced-target" />
                  <StickySaveBar
                    appearance="ledger"
                    alwaysVisible
                    dirty={unifiedDirty}
                    pending={unifiedPending}
                    status={unifiedSaveStatus}
                    error={unifiedError}
                    errorActionLabel={unifiedErrorActionLabel}
                    onErrorAction={() => void modelsEditorRef.current?.focusFirstInvalid()}
                    statusContent={
                      <div>
                        <strong>
                          {unifiedPending
                            ? t('group.settings.saving')
                            : unifiedSaved
                              ? t('group.settings.savedFeedback')
                              : unifiedDirty
                                ? t('group.settings.unsaved')
                                : t('group.settings.saved')}
                        </strong>
                        <span>{unifiedError || t('group.settings.saveNote')}</span>
                      </div>
                    }
                    actions={
                      <>
                        <Button
                          variant="ghost"
                          size="sm"
                          label={t('common.discard')}
                          isDisabled={unifiedPending || !unifiedDirty}
                          onClick={discardUnified}
                        />
                        <GroupDeleteDialog
                          groupId={groupId}
                          groupName={summaryQuery.data.name}
                          disabled={unifiedPending || unifiedDirty}
                          onPendingChange={setDeletePending}
                        />
                        <Button
                          size="sm"
                          label={t('group.settings.save')}
                          isDisabled={unifiedPending || !unifiedDirty || unifiedInvalid}
                          onClick={saveUnified}
                        />
                      </>
                    }
                  />
                </>
              )}
            </>
          ) : null}
        </>
      )}
    </section>
  )
}

// web/src/features/groups/GroupDetailView.vue
<script setup lang="ts">
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'

import { useApiClient } from '@/api/client-context'
import { useStableLoading } from '@/app/loading-state'
import {
  groupModelsQueryOptions,
  groupSettingsQueryOptions,
  groupSummaryQueryOptions,
} from '@/app/resources/groups'
import { credentialCollectionQueryOptions } from '@/app/resources/credentials'
import type { CredentialCollectionFilters, CredentialItemDto } from '@/api/control/types'
import { groupsLocation } from '@/app/route-locations'
import LedgerSheet from '@/components/layout/LedgerSheet.vue'
import PageFrame from '@/components/layout/PageFrame.vue'
import AsyncRefreshIndicator from '@/components/ui/AsyncRefreshIndicator.vue'
import AppButton from '@/components/ui/AppButton.vue'
import QueryFeedback from '@/components/ui/QueryFeedback.vue'
import SkeletonSurface from '@/components/ui/SkeletonSurface.vue'
import StickySaveBar from '@/components/ui/StickySaveBar.vue'

import GroupHeader from './GroupHeader.vue'
import GroupCredentialsTab from './credentials/GroupCredentialsTab.vue'
import GroupApiKeyEditor from './credentials/GroupApiKeyEditor.vue'
import GroupModelsTab from './models/GroupModelsTab.vue'
import GroupSettingsTab from './settings/GroupSettingsTab.vue'
import GroupDeleteDialog from './settings/GroupDeleteDialog.vue'
import { parseCredentialRouteQuery, parsePositiveId } from './group-route'
import StatusBadge from '@/components/ui/StatusBadge.vue'
import type { OperationalStatus } from '@/components/ui/status-presenter'

const route = useRoute()
const client = useApiClient()
const queryClient = useQueryClient()
const { t } = useI18n()
const groupId = computed(() => parsePositiveId(route.params.id))
const summaryQuery = useQuery(groupSummaryQueryOptions(client, groupId))
// The summary omits the enabled flag, so the models tab reads it from the
// settings query (same cache entry the settings tab prefetches).
const settingsQuery = useQuery(groupSettingsQueryOptions(client, groupId))
const credentialFilters: CredentialCollectionFilters = { page: 1, page_size: 20 }
const credentialsQuery = useQuery({
  ...credentialCollectionQueryOptions(client, () => groupId.value as number, credentialFilters),
  enabled: computed(() => groupId.value !== undefined),
})
const managementOpen = computed(() => route.query.tab === 'credentials')
const initialLoading = useStableLoading(
  () => summaryQuery.isPending.value && summaryQuery.data.value === undefined,
)
const summaryRefreshing = computed(
  () => summaryQuery.data.value !== undefined && summaryQuery.isFetching.value,
)

type GroupEditorState = {
  dirty: boolean
  pending: boolean
  error: string
  saved: boolean
  invalid?: boolean
  invalidRowCount?: number
}

const settingsState = ref<GroupEditorState>({
  dirty: false,
  pending: false,
  error: '',
  saved: false,
})
const modelsState = ref<GroupEditorState>({
  dirty: false,
  pending: false,
  error: '',
  saved: false,
})
const deletePending = ref(false)
const unifiedDirty = computed(() => settingsState.value.dirty || modelsState.value.dirty)
const unifiedPending = computed(
  () => settingsState.value.pending || modelsState.value.pending || deletePending.value,
)
const unifiedInvalid = computed(
  () => settingsState.value.invalid === true || (modelsState.value.invalidRowCount ?? 0) > 0,
)
const unifiedError = computed(() => settingsState.value.error || modelsState.value.error)
const unifiedSaved = computed(
  () => !unifiedDirty.value && (settingsState.value.saved || modelsState.value.saved),
)
const unifiedSaveStatus = computed<'idle' | 'saved' | 'error'>(() => {
  if (unifiedError.value) return 'error'
  if (unifiedSaved.value) return 'saved'
  return 'idle'
})
const unifiedErrorActionLabel = computed(() =>
  modelsState.value.invalidRowCount ? t('group.modelEditor.locateFirstInvalid') : '',
)
const settingsEditor = ref<{ requestSave: () => void; discard: () => void }>()
const modelsEditor = ref<{
  requestSave: () => void
  discard: () => void
  focusFirstInvalid: () => Promise<void>
}>()

function saveUnified(): void {
  if (settingsState.value.dirty) settingsEditor.value?.requestSave()
  if (modelsState.value.dirty) modelsEditor.value?.requestSave()
}

function discardUnified(): void {
  if (settingsState.value.dirty) settingsEditor.value?.discard()
  if (modelsState.value.dirty) modelsEditor.value?.discard()
}

type UnifiedCredentialSummary = {
  status: OperationalStatus
  label: string
}

function unifiedCredentialSummary(credential: CredentialItemDto): UnifiedCredentialSummary {
  if (credential.auth_state === 'refreshing') {
    return {
      status: 'unknown',
      label: t('group.credentials.subscription.status.refreshing'),
    }
  }
  if (credential.auth_state === 'reauthorization_required') {
    return {
      status: 'unavailable',
      label: t('group.credentials.subscription.status.needs_reauth'),
    }
  }
  if (credential.auth_state === 'outcome_unknown') {
    return {
      status: 'unknown',
      label: t('group.credentials.subscription.status.outcome_unknown'),
    }
  }
  return {
    status: credential.effective_status,
    label: t(`group.credentials.effective.${credential.effective_status}`),
  }
}

watch(
  groupId,
  (id) => {
    if (id === undefined) return
    void Promise.allSettled([
      queryClient.prefetchQuery(
        credentialCollectionQueryOptions(client, id, parseCredentialRouteQuery(route.query)),
      ),
      queryClient.prefetchQuery(groupModelsQueryOptions(client, id)),
      queryClient.prefetchQuery(groupSettingsQueryOptions(client, id)),
    ])
  },
  { immediate: true },
)
</script>

<template>
  <PageFrame wide aria-labelledby="group-detail-title">
    <LedgerSheet class="group-detail-page">
      <div v-if="groupId === undefined" class="group-detail-invalid" role="alert">
        <h1 id="group-detail-title">{{ t('group.invalidTitle') }}</h1>
        <p>{{ t('group.invalidDescription') }}</p>
        <RouterLink class="button-link" :to="groupsLocation()">{{
          t('group.backToGroups')
        }}</RouterLink>
      </div>
      <template v-else>
        <AsyncRefreshIndicator :active="summaryRefreshing" :label="t('group.loading')" />
        <SkeletonSurface
          v-if="(summaryQuery.isPending.value && !summaryQuery.data.value) || initialLoading"
          variant="detail"
          :concealed="!initialLoading"
          :label="t('group.loading')"
        />
        <QueryFeedback
          v-else-if="summaryQuery.isError.value && !summaryQuery.data.value"
          state="error"
          :message="t('group.loadFailed')"
          :retry-label="t('common.retry')"
          @retry="summaryQuery.refetch()"
        />
        <template v-else-if="summaryQuery.data.value">
          <QueryFeedback
            v-if="summaryQuery.isError.value"
            state="stale"
            :message="t('group.stale')"
            :retry-label="t('common.retry')"
            @retry="summaryQuery.refetch()"
          />
          <GroupHeader :group="summaryQuery.data.value" />
          <GroupCredentialsTab
            v-if="managementOpen"
            :key="`management-${groupId}`"
            :group-id="groupId"
            :channel-id="summaryQuery.data.value.channel_id"
            :connection-type="summaryQuery.data.value.connection_type"
          />
          <template v-else>
            <GroupSettingsTab
              ref="settingsEditor"
              :key="`settings-${groupId}`"
              :group-id="groupId"
              unified
              :blocked="deletePending"
              @state="settingsState = $event"
            />
            <section class="group-detail__credentials" :aria-label="t('group.credentials.title')">
              <div
                v-if="credentialsQuery.data.value?.items.length"
                class="group-detail__credential-input-list"
              >
                <div
                  v-for="credential in credentialsQuery.data.value.items"
                  :key="credential.mask"
                  class="group-detail__credential-input-row"
                >
                  <label
                    v-if="credential.connection_type === 'subscription'"
                    class="group-detail__credential-field"
                  >
                    <span>{{
                      credential.connection_type === 'subscription'
                        ? t('group.credentials.full.kind.account')
                        : t('group.credentials.full.kind.key')
                    }}</span>
                    <input :value="credential.mask" readonly autocomplete="off" />
                  </label>
                  <GroupApiKeyEditor
                    v-else
                    :group-id="groupId"
                    :credential="credential"
                    :disabled="unifiedPending"
                  />
                  <StatusBadge :status="unifiedCredentialSummary(credential).status" size="compact">
                    {{ unifiedCredentialSummary(credential).label }}
                  </StatusBadge>
                </div>
              </div>
              <p v-else class="group-detail__empty">{{ t('group.unified.noCredentials') }}</p>
            </section>
            <GroupModelsTab
              ref="modelsEditor"
              :key="`models-${groupId}`"
              :group-id="groupId"
              :channel-id="summaryQuery.data.value.channel_id"
              :enabled="settingsQuery.data.value?.enabled ?? true"
              unified
              :blocked="deletePending"
              readonly-route-fields
              @state="modelsState = $event"
            />
            <div id="group-settings-advanced-target" class="group-detail__advanced-target" />
            <StickySaveBar
              class="group-detail__save-bar"
              appearance="ledger"
              always-visible
              :dirty="unifiedDirty"
              :pending="unifiedPending"
              :status="unifiedSaveStatus"
              :error="unifiedError"
              :error-action-label="unifiedErrorActionLabel"
              @error-action="modelsEditor?.focusFirstInvalid()"
            >
              <template #status>
                <div>
                  <strong>
                    {{
                      unifiedPending
                        ? t('group.settings.saving')
                        : unifiedSaved
                          ? t('group.settings.savedFeedback')
                          : unifiedDirty
                            ? t('group.settings.unsaved')
                            : t('group.settings.saved')
                    }}
                  </strong>
                  <span>{{ unifiedError || t('group.settings.saveNote') }}</span>
                </div>
              </template>
              <template #discard="{ disabled }">
                <AppButton
                  variant="ghost"
                  size="sm"
                  :disabled="disabled || !unifiedDirty"
                  @click="discardUnified"
                >
                  {{ t('common.discard') }}
                </AppButton>
              </template>
              <template #save="{ disabled }">
                <GroupDeleteDialog
                  :group-id="groupId"
                  :group-name="summaryQuery.data.value.name"
                  :disabled="disabled || unifiedPending || unifiedDirty"
                  @update:pending="deletePending = $event"
                />
                <AppButton
                  size="sm"
                  :disabled="disabled || !unifiedDirty || unifiedInvalid"
                  @click="saveUnified"
                >
                  {{ t('group.settings.save') }}
                </AppButton>
              </template>
            </StickySaveBar>
          </template>
        </template>
      </template>
    </LedgerSheet>
  </PageFrame>
</template>

<style scoped>
.group-detail-page {
  display: grid;
  align-content: start;
  gap: var(--space-3);
  padding-bottom: var(--space-3);
}
.group-detail-page :deep(.group-settings),
.group-detail-page :deep(.group-models) {
  padding-top: 15px;
}
.group-detail-page :deep(.panel-header) {
  min-height: 47px;
  margin-bottom: 12px;
  padding-bottom: 10px;
}
.group-detail-page :deep(.group-settings__content) {
  gap: 12px;
}
.group-detail-page :deep(.group-settings__section) {
  gap: 10px;
  padding-top: 12px;
}
.group-detail-page :deep(.group-settings__section:first-child) {
  padding-top: 0;
}
.group-detail-page :deep(.group-settings__grid) {
  gap: 10px 14px;
}
.group-detail-page :deep(.group-settings__field) {
  gap: 4px;
}
.group-detail-page :deep(.group-settings__switch-row) {
  min-height: 42px;
  padding: 4px 2px;
}
.group-detail-page :deep(.group-settings__advanced) {
  padding-top: 8px;
}
.group-detail-page :deep(.group-settings__advanced-content) {
  gap: 8px;
  margin-top: 8px;
}
.group-detail-page :deep(.group-settings__advanced-sections) {
  gap: 12px;
}
.group-detail-page :deep(.group-settings__runtime) {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  column-gap: var(--space-6);
  row-gap: 0;
}
.group-detail-page :deep(.setting-row) {
  padding-block: 5px;
}
.group-detail-page :deep(.setting-row__cluster) {
  min-height: 26px;
  gap: 10px;
}
.group-detail-page :deep(.model-alias-editor__grid) {
  --ledger-record-list-record-min-height: 48px;
  --ledger-record-list-record-padding: 6px 0;
  --ledger-record-list-column-gap: 12px;
}
.group-detail-page :deep(.group-settings__section header p) {
  max-width: 720px;
}
.group-detail-page :deep(.group-detail__save-bar[data-status='idle']),
.group-detail-page :deep(.group-detail__save-bar[data-status='saved']) {
  position: static;
  margin: 12px 0 0;
}

.group-detail-invalid {
  display: grid;
  max-width: 640px;
  gap: var(--space-3);
}
.group-detail-invalid h1,
.group-detail-invalid p {
  margin: 0;
}
.group-detail-invalid p {
  color: var(--color-text-muted);
}
.group-detail__credentials {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  row-gap: 8px;
  border-top: 1px solid var(--color-border-subtle);
  padding: 12px 0;
}
.group-detail__empty,
.group-detail__credential-field > span {
  color: var(--color-text-muted);
  font-size: var(--text-sm);
}
.group-detail__credential-input-list {
  display: grid;
  min-width: 0;
  grid-column: 1;
  gap: 6px;
}
.group-detail__credential-input-row {
  display: flex;
  min-width: 0;
  align-items: end;
  gap: var(--space-3);
}
.group-detail__credential-field {
  display: grid;
  min-width: 0;
  flex: 1;
  gap: 4px;
}
.group-detail__credential-field input {
  width: 100%;
  min-height: var(--control-md);
  border: 1px solid var(--color-border-control);
  border-radius: var(--radius-control);
  background: var(--color-surface);
  color: var(--color-text);
  padding: 0 var(--space-3);
  font: inherit;
  font-family: var(--font-mono);
}
.group-detail__credential-input-row > :last-child {
  flex: none;
  margin-bottom: 1px;
}
.group-detail__empty {
  grid-column: 1;
  margin: 0;
}
@media (min-width: 1100px) {
  .group-detail-page :deep(.group-settings__grid) {
    grid-template-columns: repeat(3, minmax(0, 1fr));
  }
  .group-detail-page :deep(.group-settings__base-url-input) {
    grid-column: span 2;
  }
}
@media (max-width: 960px) {
  .group-detail-page :deep(.group-settings__runtime) {
    grid-template-columns: minmax(0, 1fr);
  }
}
@media (max-width: 640px) {
  .group-detail__credentials {
    padding-top: 10px;
    padding-bottom: 10px;
  }
}
</style>
