// web/src/frontends/classic/features/groups/settings/GroupDeleteDialog.vue
<script setup lang="ts">
import { useQueryClient } from '@tanstack/vue-query'
import { computed, nextTick, onBeforeUnmount, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { isNavigationFailure, useRouter } from 'vue-router'

import { useApiClient } from '@/app/api-client-context'
import {
  clearGroupResourceCaches,
  deleteGroup,
  isGroupInUseData,
  type AccessKeyReferenceDto,
} from '@/app/resources/groups'
import { ApiError, RequestCancelledError } from '@shared/http/errors'
import { applyInvalidationPlan, mutationInvalidationPlans } from '@shared/control/invalidation'
import { groupsLocation } from '@/app/route-locations'
import AppButton from '@/components/ui/AppButton.vue'
import AppConfirmDialog from '@/components/ui/AppConfirmDialog.vue'
import AppTypedConfirmation from '@/components/ui/AppTypedConfirmation.vue'
import InlineFeedback from '@/components/ui/InlineFeedback.vue'

import GroupInUseFeedback from './GroupInUseFeedback.vue'

const props = withDefaults(
  defineProps<{ groupId: number; groupName: string; disabled?: boolean }>(),
  {
    disabled: false,
  },
)
const emit = defineEmits<{
  deleted: []
  'update:pending': [value: boolean]
}>()
const client = useApiClient()
const queryClient = useQueryClient()
const router = useRouter()
const { t } = useI18n()
const open = ref(false)
const typedName = ref('')
const nameInput = ref<InstanceType<typeof AppTypedConfirmation>>()
const pending = ref(false)
const genericError = ref(false)
const references = ref<AccessKeyReferenceDto[]>([])
let controller: AbortController | undefined

const confirmed = computed(() => typedName.value === props.groupName)

async function focusNameInput(): Promise<void> {
  await nextTick()
  await nextTick()
  nameInput.value?.focus()
}

function setOpen(value: boolean): void {
  if ((pending.value || props.disabled) && !value) return
  if (props.disabled && value) return
  open.value = value
  if (value) {
    genericError.value = false
    references.value = []
    void focusNameInput()
  } else {
    typedName.value = ''
  }
}

async function confirmDelete(): Promise<void> {
  if (!confirmed.value || pending.value || props.disabled) return
  pending.value = true
  emit('update:pending', true)
  genericError.value = false
  references.value = []
  controller = new AbortController()
  const activeController = controller
  let completed = false
  try {
    await deleteGroup(client, props.groupId, activeController.signal)
    emit('deleted')
    clearGroupResourceCaches(queryClient, props.groupId)
    await applyInvalidationPlan(queryClient, mutationInvalidationPlans.group.delete)
    completed = true
  } catch (error: unknown) {
    if (error instanceof RequestCancelledError) return
    if (
      error instanceof ApiError &&
      error.code === 'GROUP_IN_USE' &&
      isGroupInUseData(error.data)
    ) {
      references.value = error.data.access_keys
    } else {
      genericError.value = true
    }
  } finally {
    if (controller === activeController) controller = undefined
    pending.value = false
    emit('update:pending', false)
  }
  if (!completed) return
  open.value = false
  typedName.value = ''
  try {
    const failure = await router.replace(groupsLocation())
    if (isNavigationFailure(failure)) window.location.assign(router.resolve(groupsLocation()).href)
  } catch {
    window.location.assign(router.resolve(groupsLocation()).href)
  }
}

onBeforeUnmount(() => controller?.abort())
</script>

<template>
  <AppConfirmDialog
    appearance="ledger"
    :open="open"
    :title="t('group.settings.delete.title')"
    :description="t('group.settings.delete.description', { name: groupName })"
    :close-label="t('group.settings.delete.close')"
    :cancel-label="t('group.settings.delete.cancel')"
    :confirm-label="t('group.settings.delete.confirm')"
    tone="danger"
    :pending="pending"
    :confirm-disabled="!confirmed || disabled"
    @update:open="setOpen"
    @confirm="confirmDelete"
  >
    <template #trigger>
      <AppButton
        class="group-delete__open"
        variant="secondary"
        size="compact"
        :disabled="disabled"
        @click="setOpen(true)"
      >
        {{ t('group.settings.delete.open') }}
      </AppButton>
    </template>

    <div class="group-delete__body">
      <AppTypedConfirmation
        id="group-delete-name"
        ref="nameInput"
        v-model="typedName"
        :label="t('group.settings.delete.typeName', { name: groupName })"
        :disabled="pending"
      />
      <GroupInUseFeedback v-if="references.length" :references="references" />
      <InlineFeedback v-else-if="genericError" tone="danger">
        {{ t('group.settings.delete.failed') }}
      </InlineFeedback>
    </div>
  </AppConfirmDialog>
</template>

<style scoped>
.group-delete__open {
  border-color: var(--color-danger);
  color: var(--color-danger);
}
.group-delete__open :deep(button),
.group-delete__open {
  gap: var(--space-2);
}
.group-delete__body {
  display: grid;
  gap: var(--space-3);
}
</style>

// web/src/frontends/astryx/features/groups/settings/GroupDeleteDialog.tsx
import * as stylex from '@stylexjs/stylex'
import {
  Button,
  Dialog,
  DialogHeader,
  Layout,
  LayoutContent,
  LayoutFooter,
  TextInput,
} from '@astryxdesign/core'
import { useQueryClient } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'
import { useEffect, useRef, useState } from 'react'

import { applyInvalidationPlan, mutationInvalidationPlans } from '@shared/control/invalidation'
import {
  clearGroupResourceCaches,
  deleteGroup,
  isGroupInUseData,
  type AccessKeyReferenceDto,
} from '@shared/control/resources/groups'
import { ApiError, RequestCancelledError } from '@shared/http/errors'
import { pagePath } from '@shared/routing/page-routes'

import { useT } from '../../../app/i18n'
import { useAppServices } from '../../../app/services'
import { InlineNotice } from '../../../components/InlineNotice'
import { plainTextInputAttrs } from '../../../components/input-attrs'
import { GroupInUseFeedback } from './GroupInUseFeedback'

const styles = stylex.create({
  body: {
    display: 'grid',
    gap: 'var(--space-3)',
  },
})

/**
 * Typed-confirmation group delete — the Astryx counterpart of classic
 * GroupDeleteDialog. Owns its trigger button (classic trigger slot inverts to
 * this plain secondary button in the save bar).
 */
export function GroupDeleteDialog({
  groupId,
  groupName,
  disabled = false,
  onDeleted,
  onPendingChange,
}: {
  groupId: number
  groupName: string
  disabled?: boolean
  onDeleted?(): void
  onPendingChange?(pending: boolean): void
}) {
  const t = useT()
  const { apiClient } = useAppServices()
  const queryClient = useQueryClient()
  const navigate = useNavigate()
  const [open, setOpen] = useState(false)
  const [typedName, setTypedName] = useState('')
  const nameInputRef = useRef<HTMLInputElement | null>(null)
  const [pending, setPending] = useState(false)
  const [genericError, setGenericError] = useState(false)
  const [references, setReferences] = useState<AccessKeyReferenceDto[]>([])
  const controllerRef = useRef<AbortController | undefined>(undefined)

  const confirmed = typedName === groupName

  useEffect(() => {
    onPendingChange?.(pending)
  }, [pending, onPendingChange])

  // Classic awaits two nextTicks before focusing the confirmation input.
  useEffect(() => {
    if (!open) return
    const frame = requestAnimationFrame(() => nameInputRef.current?.focus())
    return () => cancelAnimationFrame(frame)
  }, [open])

  useEffect(() => () => controllerRef.current?.abort(), [])

  function setDialogOpen(value: boolean): void {
    if ((pending || disabled) && !value) return
    if (disabled && value) return
    setOpen(value)
    if (value) {
      setGenericError(false)
      setReferences([])
    } else {
      setTypedName('')
    }
  }

  async function confirmDelete(): Promise<void> {
    if (!confirmed || pending || disabled) return
    setPending(true)
    setGenericError(false)
    setReferences([])
    const controller = new AbortController()
    controllerRef.current = controller
    let completed = false
    try {
      await deleteGroup(apiClient, groupId, controller.signal)
      onDeleted?.()
      clearGroupResourceCaches(queryClient, groupId)
      await applyInvalidationPlan(queryClient, mutationInvalidationPlans.group.delete)
      completed = true
    } catch (error: unknown) {
      if (error instanceof RequestCancelledError) return
      if (
        error instanceof ApiError &&
        error.code === 'GROUP_IN_USE' &&
        isGroupInUseData(error.data)
      ) {
        setReferences(error.data.access_keys)
      } else {
        setGenericError(true)
      }
    } finally {
      if (controllerRef.current === controller) controllerRef.current = undefined
      setPending(false)
    }
    if (!completed) return
    setOpen(false)
    setTypedName('')
    // Classic router.replace(groupsLocation()) with a full-navigation fallback.
    try {
      await navigate({ to: pagePath('groups'), replace: true })
    } catch {
      window.location.assign(pagePath('groups'))
    }
  }

  return (
    <>
      <Button
        variant="secondary"
        size="sm"
        isDisabled={disabled}
        label={t('group.settings.delete.open')}
        onClick={() => setDialogOpen(true)}
      />
      <Dialog isOpen={open} onOpenChange={setDialogOpen} width={440}>
        <Layout
          header={
            <DialogHeader
              title={t('group.settings.delete.title')}
              subtitle={t('group.settings.delete.description', { name: groupName })}
              onOpenChange={setDialogOpen}
              hasDivider
            />
          }
          content={
            <LayoutContent isScrollable>
              <div {...stylex.props(styles.body)}>
                <TextInput
                  ref={nameInputRef}
                  id="group-delete-name"
                  label={t('group.settings.delete.typeName', { name: groupName })}
                  value={typedName}
                  onChange={setTypedName}
                  isDisabled={pending}
                  autoComplete="off"
                  {...plainTextInputAttrs}
                />
                {references.length > 0 ? (
                  <GroupInUseFeedback references={references} />
                ) : genericError ? (
                  <InlineNotice tone="danger">
                    {t('group.settings.delete.failed')}
                  </InlineNotice>
                ) : null}
              </div>
            </LayoutContent>
          }
          footer={
            <LayoutFooter hasDivider>
              <Button
                variant="secondary"
                size="sm"
                label={t('group.settings.delete.cancel')}
                isDisabled={pending}
                onClick={() => setDialogOpen(false)}
              />
              <Button
                variant="destructive"
                size="sm"
                label={t('group.settings.delete.confirm')}
                isDisabled={!confirmed || disabled}
                isLoading={pending}
                onClick={() => void confirmDelete()}
              />
            </LayoutFooter>
          }
        />
      </Dialog>
    </>
  )
}
