// web/src/frontends/classic/features/access-keys/AccessKeyRotateDialog.vue
<script setup lang="ts">
import { RotateCcw } from '@lucide/vue'
import { useQueryClient } from '@tanstack/vue-query'
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import { useApiClient } from '@shared/http/client-context'
import type { AccessKeyDto, AccessKeyRotateResultDto } from '@/api/control/types'
import { RequestCancelledError } from '@shared/http/errors'
import { classifyMutationOutcome } from '@/app/mutation-outcome'
import { accessKeyResources, revealAccessKey, rotateAccessKey } from '@/app/resources/access-keys'
import { applyInvalidationPlan, mutationInvalidationPlans } from '@/app/resources/invalidation'
import AppButton from '@/components/ui/AppButton.vue'
import AppConfirmDialog from '@/components/ui/AppConfirmDialog.vue'
import CopyChip from '@/components/ui/CopyChip.vue'
import InlineFeedback from '@/components/ui/InlineFeedback.vue'
import { createUUID } from '@/lib/uuid'

import { findAccessKeyForReconciliation } from './access-key-edit-operation'
import type { PendingAccessKeyRotateOperation } from './access-key-rotate-operation'

const props = withDefaults(
  defineProps<{
    accessKey: AccessKeyDto
    disabled?: boolean
    operation?: PendingAccessKeyRotateOperation | null
  }>(),
  { disabled: false, operation: null },
)
const emit = defineEmits<{
  rotated: [accessKey: AccessKeyDto]
  'update:pending': [pending: boolean]
  'update:operation': [operation: PendingAccessKeyRotateOperation | null]
}>()
const client = useApiClient()
const queryClient = useQueryClient()
const { t } = useI18n()
const open = ref(false)
const pending = ref(false)
const failed = ref(false)
const refreshFailed = ref(false)
const operationState = ref<'idle' | 'indeterminate' | 'reconciling'>(
  props.operation?.state ?? 'idle',
)
const operationID = ref(props.operation?.idempotencyKey ?? createUUID())
const result = ref<AccessKeyRotateResultDto | null>(null)
const current = ref<AccessKeyDto | null>(null)
let controller: AbortController | undefined

const feedbackKey = computed(() => {
  if (operationState.value === 'reconciling') return 'accessKeys.rotate.reconciling'
  if (operationState.value === 'indeterminate') return 'accessKeys.rotate.indeterminate'
  return ''
})
const confirmLabel = computed(() => {
  if (result.value) return t('accessKeys.rotate.done')
  if (operationState.value !== 'idle') return t('accessKeys.rotate.checkResult')
  return t('accessKeys.rotate.confirm')
})
const triggerLabel = computed(() =>
  operationState.value === 'idle'
    ? t('accessKeys.rotate.open')
    : t('accessKeys.rotate.checkResult'),
)
const displayKey = computed(() =>
  result.value?.key ? result.value.key : (current.value?.masked_key ?? props.accessKey.masked_key),
)

watch(pending, (value) => emit('update:pending', value))
watch(
  () => props.operation,
  (operation) => {
    if (pending.value || result.value) return
    if (operation) {
      operationID.value = operation.idempotencyKey
      operationState.value = operation.state
    } else if (operationState.value !== 'idle') {
      operationID.value = createUUID()
      operationState.value = 'idle'
    }
  },
)

function resetOperation(): void {
  controller?.abort()
  controller = undefined
  pending.value = false
  failed.value = false
  refreshFailed.value = false
  operationState.value = 'idle'
  operationID.value = createUUID()
  result.value = null
  current.value = null
  emit('update:operation', null)
}

function setOpen(value: boolean): void {
  if (!value && pending.value) return
  const refreshAfterClose = !value && result.value !== null
  if (refreshAfterClose) resetOperation()
  open.value = value
  if (refreshAfterClose) void refreshQueries()
}

function openDialog(): void {
  if (props.disabled) return
  open.value = true
}

async function refreshCurrent(signal: AbortSignal): Promise<AccessKeyDto | null> {
  try {
    return (await findAccessKeyForReconciliation(client, props.accessKey.id, signal)) ?? null
  } catch {
    refreshFailed.value = true
    return null
  }
}

async function resolveCurrentKey(): Promise<string> {
  const value = await revealAccessKey(client, props.accessKey.id)
  return value.key
}

async function refreshQueries(): Promise<void> {
  try {
    await applyInvalidationPlan(queryClient, mutationInvalidationPlans.accessKey.rotate)
  } catch {
    void queryClient.invalidateQueries({ queryKey: accessKeyResources.collection.queryKey })
  }
}

async function completeRotation(
  rotation: AccessKeyRotateResultDto,
  signal: AbortSignal,
): Promise<void> {
  result.value = rotation
  current.value = rotation
  if (rotation.replayed) {
    current.value = (await refreshCurrent(signal)) ?? rotation
  }
  emit('rotated', current.value)
  emit('update:operation', null)
  operationState.value = 'idle'
}

async function confirmRotate(): Promise<void> {
  if (pending.value) return
  if (result.value) {
    setOpen(false)
    return
  }
  pending.value = true
  failed.value = false
  refreshFailed.value = false
  controller?.abort()
  controller = new AbortController()
  const activeController = controller
  try {
    const rotation = await rotateAccessKey(
      client,
      props.accessKey.id,
      operationID.value,
      activeController.signal,
    )
    if (controller !== activeController || !open.value) return
    await completeRotation(rotation, activeController.signal)
  } catch (error: unknown) {
    if (controller !== activeController || !open.value || error instanceof RequestCancelledError) {
      return
    }
    const outcome = classifyMutationOutcome({ kind: 'error', error, requestSent: true })
    if (outcome.kind === 'indeterminate' || outcome.kind === 'reconciling') {
      operationState.value = outcome.kind
      emit('update:operation', {
        base: props.accessKey,
        idempotencyKey: operationID.value,
        state: outcome.kind,
      })
    } else if (outcome.kind === 'failed' && outcome.reason === 'expired-known') {
      const latest = await refreshCurrent(activeController.signal)
      if (latest) {
        current.value = latest
        result.value = { ...latest, replayed: true }
        emit('rotated', latest)
        emit('update:operation', null)
        operationState.value = 'idle'
      } else {
        operationState.value = 'indeterminate'
        emit('update:operation', {
          base: props.accessKey,
          idempotencyKey: operationID.value,
          state: 'indeterminate',
        })
      }
    } else if (outcome.kind === 'failed' && outcome.reason === 'retryable-precondition') {
      operationState.value = 'reconciling'
      emit('update:operation', {
        base: props.accessKey,
        idempotencyKey: operationID.value,
        state: 'reconciling',
      })
    } else {
      failed.value = true
      if (outcome.kind === 'failed' && outcome.reason === 'rejected') {
        operationID.value = createUUID()
        operationState.value = 'idle'
        emit('update:operation', null)
      }
    }
  } finally {
    if (controller === activeController) {
      controller = undefined
      pending.value = false
    }
  }
}

onBeforeUnmount(() => controller?.abort())
</script>

<template>
  <AppConfirmDialog
    :open="open"
    :title="t('accessKeys.rotate.title')"
    :description="t('accessKeys.rotate.description', { name: accessKey.name })"
    :close-label="t('accessKeys.rotate.close')"
    :cancel-label="result ? t('common.close') : t('common.cancel')"
    :confirm-label="confirmLabel"
    tone="danger"
    description-tone="warning"
    :pending="pending"
    @update:open="setOpen"
    @confirm="confirmRotate"
  >
    <template #trigger>
      <AppButton variant="secondary" size="compact" :disabled="disabled" @click="openDialog">
        <RotateCcw :size="16" aria-hidden="true" />
        {{ triggerLabel }}
      </AppButton>
    </template>

    <div class="access-key-rotate__body">
      <InlineFeedback tone="warning" appearance="hint">
        {{ t('accessKeys.rotate.impact') }}
      </InlineFeedback>
      <InlineFeedback v-if="feedbackKey" tone="warning">
        {{ t(feedbackKey) }}
      </InlineFeedback>
      <InlineFeedback v-if="failed" tone="danger">{{
        t('accessKeys.rotate.failed')
      }}</InlineFeedback>
      <InlineFeedback v-if="refreshFailed" tone="warning">
        {{ t('accessKeys.rotate.refreshFailed') }}
      </InlineFeedback>
      <div v-if="result" class="access-key-rotate__result" aria-live="polite">
        <strong>{{
          t(result.key ? 'accessKeys.rotate.newKey' : 'accessKeys.rotate.currentKey')
        }}</strong>
        <CopyChip
          v-if="open"
          :key="`${accessKey.id}:${result.updated_at_ms}`"
          :value="displayKey"
          :label="t('accessKeys.copy')"
          :success-label="t('common.copied')"
          :failure-label="t('common.copyFailed')"
          :resolve-value="result.key ? undefined : resolveCurrentKey"
        />
        <small>{{
          t(result.key ? 'accessKeys.rotate.newKeyHint' : 'accessKeys.rotate.replayedHint')
        }}</small>
      </div>
    </div>
  </AppConfirmDialog>
</template>

<style scoped>
.access-key-rotate__body,
.access-key-rotate__result {
  display: grid;
  gap: 10px;
}

.access-key-rotate__result {
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-control);
  background: var(--color-surface-sunken);
  padding: 10px 12px;
}

.access-key-rotate__result strong {
  font-size: var(--text-sm);
}

.access-key-rotate__result small {
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
}
</style>

// web/src/frontends/astryx/features/access-keys/AccessKeyRotateDialog.tsx
import * as stylex from '@stylexjs/stylex'
import {
  Banner,
  Button,
  Dialog,
  DialogHeader,
  Layout,
  LayoutContent,
  LayoutFooter,
} from '@astryxdesign/core'
import { useQueryClient } from '@tanstack/react-query'
import { useEffect, useRef, useState } from 'react'

import { applyInvalidationPlan, mutationInvalidationPlans } from '@shared/control/invalidation'
import { classifyMutationOutcome } from '@shared/control/mutation-outcome'
import {
  accessKeyResources,
  revealAccessKey,
  rotateAccessKey,
} from '@shared/control/resources/access-keys'
import type { AccessKeyDto, AccessKeyRotateResultDto } from '@shared/control/types'
import { RequestCancelledError } from '@shared/http/errors'
import { createUUID } from '@shared/lib/uuid'
import type { MessageId } from '@shared/i18n/message-ids'
import { findAccessKeyForReconciliation } from '@shared/domain/access-keys/access-key-edit-operation'
import type { PendingAccessKeyRotateOperation } from '@shared/domain/access-keys/access-key-rotate-operation'

import { useT } from '../../app/i18n'
import { useAppServices } from '../../app/services'
import { CopyChip } from './AccessKeyCopyChip'

const styles = stylex.create({
  body: {
    display: 'grid',
    gap: 10,
  },
  result: {
    display: 'grid',
    gap: 10,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border-subtle)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-surface-sunken)',
    paddingBlock: 10,
    paddingInline: 12,
  },
  resultLabel: {
    fontSize: 'var(--text-sm)',
  },
  resultHint: {
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
  },
})

type RotateOperationState = 'idle' | 'indeterminate' | 'reconciling'

export function AccessKeyRotateDialog({
  accessKey,
  open,
  onOpenChange,
  operation = null,
  onRotated,
  onPendingChange,
  onOperationChange,
}: {
  accessKey: AccessKeyDto
  open: boolean
  onOpenChange(open: boolean): void
  operation?: PendingAccessKeyRotateOperation | null
  onRotated(accessKey: AccessKeyDto): void
  onPendingChange(pending: boolean): void
  onOperationChange(operation: PendingAccessKeyRotateOperation | null): void
}) {
  const t = useT()
  const { apiClient } = useAppServices()
  const queryClient = useQueryClient()
  const [pending, setPending] = useState(false)
  const [failed, setFailed] = useState(false)
  const [refreshFailed, setRefreshFailed] = useState(false)
  const [operationState, setOperationState] = useState<RotateOperationState>(
    operation?.state ?? 'idle',
  )
  const [operationID, setOperationID] = useState(operation?.idempotencyKey ?? createUUID())
  const [result, setResult] = useState<AccessKeyRotateResultDto | null>(null)
  const [current, setCurrent] = useState<AccessKeyDto | null>(null)
  const controllerRef = useRef<AbortController | null>(null)

  // Mirror the classic watch on props.operation: an externally surfaced
  // pending operation adopts the dialog's idempotency key/state; clearing it
  // while idle resets to a fresh key. Render-phase adjustment, not an effect —
  // the state must be consistent in the same commit that renders the dialog.
  const [lastOperation, setLastOperation] = useState(operation ?? null)
  if (lastOperation !== (operation ?? null)) {
    setLastOperation(operation ?? null)
    if (!pending && !result) {
      if (operation) {
        setOperationID(operation.idempotencyKey)
        setOperationState(operation.state)
      } else if (operationState !== 'idle') {
        setOperationID(createUUID())
        setOperationState('idle')
      }
    }
  }

  // Classic `watch(pending)` → emit only on transitions. The callback goes
  // through a ref so the effect depends on `pending` alone — the parent's
  // inline `setRotationPending` changes identity every commit and would
  // otherwise re-fire notify → forceStoreRerender in a loop.
  const onPendingChangeRef = useRef(onPendingChange)
  useEffect(() => {
    onPendingChangeRef.current = onPendingChange
  })
  useEffect(() => {
    onPendingChangeRef.current(pending)
  }, [pending])

  useEffect(
    () => () => {
      controllerRef.current?.abort()
    },
    [],
  )

  const feedbackKey =
    operationState === 'reconciling'
      ? 'accessKeys.rotate.reconciling'
      : operationState === 'indeterminate'
        ? 'accessKeys.rotate.indeterminate'
        : ''
  const confirmLabel = result
    ? t('accessKeys.rotate.done')
    : operationState !== 'idle'
      ? t('accessKeys.rotate.checkResult')
      : t('accessKeys.rotate.confirm')
  const displayKey = result?.key ?? current?.masked_key ?? accessKey.masked_key

  const resetOperation = () => {
    controllerRef.current?.abort()
    controllerRef.current = null
    setPending(false)
    setFailed(false)
    setRefreshFailed(false)
    setOperationState('idle')
    setOperationID(createUUID())
    setResult(null)
    setCurrent(null)
    onOperationChange(null)
  }

  const refreshQueries = async () => {
    try {
      await applyInvalidationPlan(queryClient, mutationInvalidationPlans.accessKey.rotate)
    } catch {
      void queryClient.invalidateQueries({ queryKey: accessKeyResources.collection.queryKey })
    }
  }

  const setDialogOpen = (value: boolean) => {
    if (!value && pending) return
    const refreshAfterClose = !value && result !== null
    if (refreshAfterClose) resetOperation()
    onOpenChange(value)
    if (refreshAfterClose) void refreshQueries()
  }

  const refreshCurrent = async (signal: AbortSignal): Promise<AccessKeyDto | null> => {
    try {
      return (await findAccessKeyForReconciliation(apiClient, accessKey.id, signal)) ?? null
    } catch {
      setRefreshFailed(true)
      return null
    }
  }

  const resolveCurrentKey = async (): Promise<string> => {
    const value = await revealAccessKey(apiClient, accessKey.id)
    return value.key
  }

  const completeRotation = async (
    rotation: AccessKeyRotateResultDto,
    signal: AbortSignal,
  ): Promise<void> => {
    setResult(rotation)
    let resolved: AccessKeyDto = rotation
    if (rotation.replayed) {
      resolved = (await refreshCurrent(signal)) ?? rotation
    }
    setCurrent(resolved)
    onRotated(resolved)
    onOperationChange(null)
    setOperationState('idle')
  }

  const confirmRotate = async () => {
    if (pending) return
    if (result) {
      setDialogOpen(false)
      return
    }
    setPending(true)
    setFailed(false)
    setRefreshFailed(false)
    controllerRef.current?.abort()
    const controller = new AbortController()
    controllerRef.current = controller
    const stale = () => controllerRef.current !== controller || !open
    try {
      const rotation = await rotateAccessKey(
        apiClient,
        accessKey.id,
        operationID,
        controller.signal,
      )
      if (stale()) return
      await completeRotation(rotation, controller.signal)
    } catch (error: unknown) {
      if (stale() || error instanceof RequestCancelledError) return
      const outcome = classifyMutationOutcome({ kind: 'error', error, requestSent: true })
      if (outcome.kind === 'indeterminate' || outcome.kind === 'reconciling') {
        setOperationState(outcome.kind)
        onOperationChange({
          base: accessKey,
          idempotencyKey: operationID,
          state: outcome.kind,
        })
      } else if (outcome.kind === 'failed' && outcome.reason === 'expired-known') {
        const latest = await refreshCurrent(controller.signal)
        if (latest) {
          setCurrent(latest)
          setResult({ ...latest, replayed: true })
          onRotated(latest)
          onOperationChange(null)
          setOperationState('idle')
        } else {
          setOperationState('indeterminate')
          onOperationChange({
            base: accessKey,
            idempotencyKey: operationID,
            state: 'indeterminate',
          })
        }
      } else if (outcome.kind === 'failed' && outcome.reason === 'retryable-precondition') {
        setOperationState('reconciling')
        onOperationChange({
          base: accessKey,
          idempotencyKey: operationID,
          state: 'reconciling',
        })
      } else {
        setFailed(true)
        if (outcome.kind === 'failed' && outcome.reason === 'rejected') {
          setOperationID(createUUID())
          setOperationState('idle')
          onOperationChange(null)
        }
      }
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null
        setPending(false)
      }
    }
  }

  return (
    <Dialog isOpen={open} onOpenChange={setDialogOpen} width={440}>
        <Layout
          header={
            <DialogHeader
              title={t('accessKeys.rotate.title')}
              subtitle={t('accessKeys.rotate.description', { name: accessKey.name })}
              onOpenChange={setDialogOpen}
              hasDivider
            />
          }
          content={
            <LayoutContent isScrollable>
              <div {...stylex.props(styles.body)}>
                <Banner status="warning" title={t('accessKeys.rotate.impact')} />
                {feedbackKey !== '' && (
                  <Banner status="warning" title={t(feedbackKey as MessageId)} />
                )}
                {failed && <Banner status="error" title={t('accessKeys.rotate.failed')} />}
                {refreshFailed && (
                  <Banner status="warning" title={t('accessKeys.rotate.refreshFailed')} />
                )}
                {result && (
                  <div
                    {...stylex.props(styles.result)}
                    aria-live="polite"
                  >
                    <strong {...stylex.props(styles.resultLabel)}>
                      {t(result.key ? 'accessKeys.rotate.newKey' : 'accessKeys.rotate.currentKey')}
                    </strong>
                    {open && (
                      <CopyChip
                        key={`${accessKey.id}:${result.updated_at_ms}`}
                        value={displayKey}
                        label={t('accessKeys.copy')}
                        successLabel={t('common.copied')}
                        failureLabel={t('common.copyFailed')}
                        resolveValue={result.key ? undefined : resolveCurrentKey}
                      />
                    )}
                    <small {...stylex.props(styles.resultHint)}>
                      {t(result.key ? 'accessKeys.rotate.newKeyHint' : 'accessKeys.rotate.replayedHint')}
                    </small>
                  </div>
                )}
              </div>
            </LayoutContent>
          }
          footer={
            <LayoutFooter hasDivider>
              <Button
                variant="secondary"
                label={result ? t('common.close') : t('common.cancel')}
                isDisabled={pending}
                onClick={() => setDialogOpen(false)}
              />
              <Button
                variant="destructive"
                label={confirmLabel}
                isLoading={pending}
                onClick={() => void confirmRotate()}
              />
            </LayoutFooter>
          }
        />
    </Dialog>
  )
}
