// web/src/frontends/classic/features/access-keys/AccessKeyCostLimitEditor.vue
<script setup lang="ts">
import { Plus, X } from '@lucide/vue'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type {
  AccessKeyCostLimitRuleStatusDto,
  AccessKeyCostLimitStatusDto,
} from '@shared/control/types'
import AppSwitch from '@/components/ui/AppSwitch.vue'
import AppSelect from '@/components/ui/AppSelect.vue'
import AppTextInput from '@/components/ui/AppTextInput.vue'
import IconButton from '@/components/ui/IconButton.vue'
import QuotaProgressBar from '@/components/ui/QuotaProgressBar.vue'
import { quotaProgressTone } from '@shared/lib/quota-progress'
import { createUUID } from '@shared/lib/uuid'

import AccessKeyCostLimitWindowTime from './AccessKeyCostLimitWindowTime.vue'
import type { AccessKeyCostLimitRuleDraft } from './access-key-patch'

const props = defineProps<{
  modelValue: AccessKeyCostLimitRuleDraft[]
  runtimeStatus: AccessKeyCostLimitStatusDto | null
  disabled: boolean
}>()
const emit = defineEmits<{
  'update:modelValue': [value: AccessKeyCostLimitRuleDraft[]]
}>()
const { n, t } = useI18n()

const totalCount = computed(() => props.modelValue.filter((rule) => rule.kind === 'total').length)
const periodicCount = computed(
  () => props.modelValue.filter((rule) => rule.kind === 'periodic').length,
)
const runtimeByID = computed(
  () => new Map((props.runtimeStatus?.rules ?? []).map((rule) => [rule.id, rule])),
)
const totalRules = computed(() => props.modelValue.filter((rule) => rule.kind === 'total'))
const periodicRules = computed(() => props.modelValue.filter((rule) => rule.kind === 'periodic'))
const totalEnabled = computed({
  get: () => totalCount.value > 0,
  set: (enabled: boolean) => {
    if (props.disabled) return
    if (enabled) {
      if (totalCount.value === 0) addRule('total')
      return
    }
    removeRules('total')
  },
})
const periodicEnabled = computed({
  get: () => periodicCount.value > 0,
  set: (enabled: boolean) => {
    if (props.disabled) return
    if (enabled) {
      if (periodicCount.value === 0) addRule('periodic')
      return
    }
    removeRules('periodic')
  },
})

type PeriodUnit = 'seconds' | 'minutes' | 'hours' | 'days'
const periodUnits: ReadonlyArray<{ value: PeriodUnit; seconds: number }> = [
  { value: 'seconds', seconds: 1 },
  { value: 'minutes', seconds: 60 },
  { value: 'hours', seconds: 3_600 },
  { value: 'days', seconds: 86_400 },
]
const periodUnitOptions = computed(() =>
  periodUnits.map((unit) => ({
    value: unit.value,
    label: t(`accessKeys.drawer.costLimits.units.${unit.value}`),
  })),
)

function updateRule(clientKey: string, patch: Partial<AccessKeyCostLimitRuleDraft>): void {
  emit(
    'update:modelValue',
    props.modelValue.map((rule) => (rule.clientKey === clientKey ? { ...rule, ...patch } : rule)),
  )
}

function removeRule(clientKey: string): void {
  emit(
    'update:modelValue',
    props.modelValue.filter((rule) => rule.clientKey !== clientKey),
  )
}

function removeRules(kind: 'total' | 'periodic'): void {
  emit(
    'update:modelValue',
    props.modelValue.filter((rule) => rule.kind !== kind),
  )
}

function addRule(kind: 'total' | 'periodic'): void {
  if (props.disabled || (kind === 'total' ? totalCount.value >= 1 : periodicCount.value >= 10)) {
    return
  }
  emit('update:modelValue', [
    ...props.modelValue,
    {
      clientKey: createUUID(),
      kind,
      limit_usd: kind === 'total' ? '100' : '20',
      ...(kind === 'periodic' ? { period_seconds: 18_000 } : {}),
    },
  ])
}

function periodUnit(seconds: number | undefined): PeriodUnit {
  const value = seconds ?? 0
  for (const unit of [...periodUnits].reverse()) {
    if (value > 0 && value % unit.seconds === 0) return unit.value
  }
  return 'seconds'
}

function unitSeconds(unit: PeriodUnit): number {
  return periodUnits.find((candidate) => candidate.value === unit)?.seconds ?? 1
}

function periodValue(seconds: number | undefined): number {
  const unit = periodUnit(seconds)
  return Math.max(1, Math.floor((seconds ?? 0) / unitSeconds(unit)))
}

function updatePeriodValue(rule: AccessKeyCostLimitRuleDraft, raw: string): void {
  const value = Number(raw)
  updateRule(rule.clientKey, {
    period_seconds: Number.isFinite(value)
      ? value * unitSeconds(periodUnit(rule.period_seconds))
      : 0,
  })
}

function updatePeriodUnit(rule: AccessKeyCostLimitRuleDraft, unit: PeriodUnit): void {
  updateRule(rule.clientKey, {
    period_seconds: periodValue(rule.period_seconds) * unitSeconds(unit),
  })
}

function runtimeFor(
  rule: AccessKeyCostLimitRuleDraft,
): AccessKeyCostLimitRuleStatusDto | undefined {
  return rule.id === undefined ? undefined : runtimeByID.value.get(rule.id)
}

function remainingPercent(runtime: AccessKeyCostLimitRuleStatusDto): number {
  if (runtime.status === 'inactive') return 100
  const limit = Number(runtime.limit_usd)
  const remaining = Number(runtime.remaining_usd)
  if (!Number.isFinite(limit) || !Number.isFinite(remaining) || limit <= 0) return 0
  return Math.round(Math.max(0, Math.min(100, (remaining / limit) * 100)))
}

function runtimeProgressValue(runtime: AccessKeyCostLimitRuleStatusDto): number {
  return remainingPercent(runtime)
}

function runtimeValueText(runtime: AccessKeyCostLimitRuleStatusDto): string {
  return t('accessKeys.costLimits.remainingPercent', { value: n(remainingPercent(runtime)) })
}
</script>

<template>
  <div class="cost-limit-editor">
    <section class="cost-limit-section">
      <header class="cost-limit-section__header">
        <div class="cost-limit-section__intro">
          <h3>{{ t('accessKeys.drawer.costLimits.total') }}</h3>
          <p>{{ t('accessKeys.drawer.costLimits.totalDescription') }}</p>
        </div>
        <div class="cost-limit-section__toggle">
          <AppSwitch
            v-model="totalEnabled"
            :label="t('accessKeys.drawer.costLimits.enableTotal')"
            :disabled="disabled"
          />
        </div>
      </header>

      <div v-if="totalEnabled" class="cost-limit-section__content">
        <div class="cost-limit-fields-header cost-limit-fields-header--total">
          <span>{{ t('accessKeys.drawer.costLimits.amount') }}</span>
        </div>
        <article v-for="rule in totalRules" :key="rule.clientKey" class="cost-limit-rule">
          <div
            class="cost-limit-input-group cost-limit-input-group--total"
            role="group"
            :aria-label="t('accessKeys.drawer.costLimits.total')"
          >
            <AppTextInput
              :id="`cost-limit-amount-${rule.clientKey}`"
              v-model="rule.limit_usd"
              :label="t('accessKeys.drawer.costLimits.amount')"
              appearance="surface"
              size="compact"
              monospace
              inputmode="decimal"
              :disabled="disabled"
            >
              <template #leading>$</template>
            </AppTextInput>
          </div>
          <div v-if="runtimeFor(rule)" class="cost-limit-rule__runtime">
            <QuotaProgressBar
              :value="runtimeProgressValue(runtimeFor(rule)!)"
              :tone="
                quotaProgressTone(
                  remainingPercent(runtimeFor(rule)!),
                  runtimeFor(rule)!.status === 'exhausted',
                )
              "
              :label="t('accessKeys.drawer.costLimits.total')"
              :value-text="runtimeValueText(runtimeFor(rule)!)"
              compact
            />
            <strong>{{ runtimeValueText(runtimeFor(rule)!) }}</strong>
            <span v-if="runtimeFor(rule)!.status === 'exhausted'">
              {{ t('accessKeys.costLimits.notAutomatic') }}
            </span>
          </div>
        </article>
      </div>
    </section>

    <section class="cost-limit-section">
      <header class="cost-limit-section__header">
        <div class="cost-limit-section__intro">
          <h3>{{ t('accessKeys.drawer.costLimits.periodic') }}</h3>
          <p>{{ t('accessKeys.drawer.costLimits.periodicDescription') }}</p>
        </div>
        <div class="cost-limit-section__toggle">
          <AppSwitch
            v-model="periodicEnabled"
            :label="t('accessKeys.drawer.costLimits.enablePeriodic')"
            :disabled="disabled"
          />
        </div>
      </header>

      <div v-if="periodicEnabled" class="cost-limit-section__content">
        <div class="cost-limit-fields-header cost-limit-fields-header--periodic">
          <span>{{ t('accessKeys.drawer.costLimits.amount') }}</span>
          <span>{{ t('accessKeys.drawer.costLimits.period') }}</span>
          <span>{{ t('accessKeys.drawer.costLimits.unit') }}</span>
          <span aria-hidden="true"></span>
        </div>
        <div class="cost-limit-rule-list">
          <article
            v-for="(rule, index) in periodicRules"
            :key="rule.clientKey"
            class="cost-limit-rule"
          >
            <div class="cost-limit-rule__row">
              <div
                class="cost-limit-input-group cost-limit-input-group--periodic"
                role="group"
                :aria-label="t('accessKeys.drawer.costLimits.periodic')"
              >
                <AppTextInput
                  :id="`cost-limit-amount-${rule.clientKey}`"
                  v-model="rule.limit_usd"
                  :label="t('accessKeys.drawer.costLimits.amount')"
                  appearance="surface"
                  size="compact"
                  monospace
                  inputmode="decimal"
                  :disabled="disabled"
                >
                  <template #leading>$</template>
                </AppTextInput>
                <AppTextInput
                  :id="`cost-limit-period-${rule.clientKey}`"
                  :model-value="String(periodValue(rule.period_seconds))"
                  :label="t('accessKeys.drawer.costLimits.period')"
                  type="number"
                  appearance="surface"
                  size="compact"
                  monospace
                  inputmode="numeric"
                  :disabled="disabled"
                  @update:model-value="updatePeriodValue(rule, $event)"
                />
                <AppSelect
                  :model-value="periodUnit(rule.period_seconds)"
                  :label="t('accessKeys.drawer.costLimits.unit')"
                  :options="periodUnitOptions"
                  variant="embedded"
                  size="compact"
                  :disabled="disabled"
                  @update:model-value="updatePeriodUnit(rule, $event as PeriodUnit)"
                />
              </div>
              <div class="cost-limit-rule__actions">
                <IconButton
                  v-if="index > 0"
                  class="cost-limit-rule__remove"
                  variant="ghost"
                  size="xs"
                  :label="t('accessKeys.drawer.costLimits.remove')"
                  :disabled="disabled"
                  @click="removeRule(rule.clientKey)"
                >
                  <X :size="14" aria-hidden="true" />
                </IconButton>
                <span v-else aria-hidden="true"></span>
                <IconButton
                  v-if="index === periodicRules.length - 1"
                  class="cost-limit-rule__add"
                  variant="ghost"
                  size="xs"
                  :label="t('accessKeys.drawer.costLimits.addPeriodic')"
                  :disabled="disabled || periodicCount >= 10"
                  @click="addRule('periodic')"
                >
                  <Plus :size="14" aria-hidden="true" />
                </IconButton>
                <span v-else aria-hidden="true"></span>
              </div>
            </div>
            <div v-if="runtimeFor(rule)" class="cost-limit-rule__runtime">
              <QuotaProgressBar
                :value="runtimeProgressValue(runtimeFor(rule)!)"
                :tone="
                  quotaProgressTone(
                    remainingPercent(runtimeFor(rule)!),
                    runtimeFor(rule)!.status === 'exhausted',
                  )
                "
                :label="t('accessKeys.drawer.costLimits.periodic')"
                :value-text="runtimeValueText(runtimeFor(rule)!)"
                compact
              />
              <strong>{{ runtimeValueText(runtimeFor(rule)!) }}</strong>
              <AccessKeyCostLimitWindowTime :rule="runtimeFor(rule)!" />
            </div>
          </article>
        </div>
      </div>
    </section>
  </div>
</template>

<style scoped>
.cost-limit-editor {
  display: grid;
  min-width: 0;
  gap: var(--space-4);
}
.cost-limit-section {
  display: grid;
  min-width: 0;
  gap: var(--space-3);
}
.cost-limit-section + .cost-limit-section {
  border-top: 1px solid var(--color-border-subtle);
  padding-top: var(--space-4);
}
.cost-limit-section__header,
.cost-limit-section__toggle {
  display: flex;
  align-items: center;
}
.cost-limit-section__header {
  justify-content: space-between;
  gap: var(--space-3);
}
.cost-limit-section__intro {
  min-width: 0;
}
.cost-limit-section__intro h3 {
  margin: 0;
  color: var(--color-text);
  font-size: var(--text-body-sm);
  font-weight: 700;
}
.cost-limit-section__intro p {
  margin: var(--space-1) 0 0;
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
  line-height: 1.45;
}
.cost-limit-section__toggle {
  flex: 0 0 auto;
}
.cost-limit-section__content,
.cost-limit-rule-list {
  display: grid;
  min-width: 0;
  gap: var(--space-2);
}
.cost-limit-rule {
  display: grid;
  min-width: 0;
  gap: var(--space-2);
}
.cost-limit-rule__row {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 56px;
  min-width: 0;
  align-items: center;
  gap: var(--space-2);
}
.cost-limit-rule__actions {
  display: grid;
  width: 56px;
  grid-auto-flow: column;
  grid-auto-columns: 28px;
  align-items: center;
}
.cost-limit-rule__remove,
.cost-limit-rule__add {
  color: var(--color-text-faint);
}
.cost-limit-rule__remove:hover:not(:disabled) {
  color: var(--color-danger);
}
.cost-limit-rule__add:hover:not(:disabled) {
  color: var(--color-action);
}
.cost-limit-fields-header {
  display: grid;
  min-width: 0;
  align-items: end;
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
}
.cost-limit-fields-header--total {
  grid-template-columns: minmax(0, 1fr);
}
.cost-limit-fields-header--periodic {
  grid-template-columns: minmax(0, 1fr) 76px 96px 64px;
}
.cost-limit-input-group {
  display: grid;
  width: 100%;
  min-width: 0;
  border: 1px solid var(--color-border-control);
  border-radius: var(--radius-control);
  background: var(--color-surface);
}
.cost-limit-input-group--total {
  grid-template-columns: minmax(0, 1fr);
}
.cost-limit-input-group--periodic {
  grid-template-columns: minmax(0, 1fr) 76px 96px;
}
.cost-limit-input-group:focus-within {
  border-color: var(--color-focus);
  outline: 0;
  box-shadow: var(--focus-ring);
}
.cost-limit-input-group :deep(.app-text-input) {
  border: 0;
  border-left: 1px solid var(--color-border-subtle);
  border-radius: 0;
  background: none;
  padding-left: var(--space-2);
}
.cost-limit-input-group :deep(.app-text-input:first-child) {
  border-left: 0;
}
.cost-limit-input-group :deep(.app-text-input[data-input-shell]:focus-within) {
  border-color: var(--color-border-subtle);
  outline: 0;
  box-shadow: none;
}
.cost-limit-input-group :deep(.app-select__trigger) {
  align-self: stretch;
  height: 100%;
  min-height: var(--control-xs);
  border-left: 1px solid var(--color-border-subtle);
  background: transparent;
  font-size: var(--text-meta);
}
.cost-limit-rule__runtime {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto minmax(54px, auto);
  min-height: 18px;
  align-items: center;
  gap: var(--space-2);
  color: var(--color-text-faint);
  font-size: var(--text-label-xs);
}
.cost-limit-rule__runtime strong {
  color: var(--color-text-muted);
  font-family: var(--font-mono);
  font-size: var(--text-label-xs);
  font-variant-numeric: tabular-nums;
  font-weight: 650;
  white-space: nowrap;
}
.cost-limit-rule__runtime > :last-child {
  min-width: 0;
  overflow: hidden;
  text-align: right;
  text-overflow: ellipsis;
  white-space: nowrap;
}
@media (max-width: 560px) {
  .cost-limit-section__header {
    align-items: flex-start;
  }

  .cost-limit-fields-header--periodic {
    grid-template-columns: minmax(0, 1fr) 58px 76px 64px;
  }

  .cost-limit-input-group--periodic {
    grid-template-columns: minmax(0, 1fr) 58px 76px;
  }
}
</style>

// web/src/frontends/astryx/features/access-keys/AccessKeyCostLimitEditor.tsx
import * as stylex from '@stylexjs/stylex'
import { IconButton, Selector, Switch, TextInput } from '@astryxdesign/core'
import { Plus, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import { useIntl } from 'react-intl'

import type {
  AccessKeyCostLimitRuleStatusDto,
  AccessKeyCostLimitStatusDto,
} from '@shared/control/types'
import type { AccessKeyCostLimitRuleDraft } from '@shared/domain/access-keys/access-key-patch'
import type { MessageId } from '@shared/i18n/message-ids'
import { quotaProgressTone, type QuotaProgressTone } from '@shared/lib/quota-progress'
import { createUUID } from '@shared/lib/uuid'

import { useT } from '../../app/i18n'
import { decimalInputAttrs, numericInputAttrs } from '../../components/input-attrs'
import { AccessKeyCostLimitWindowTime } from './AccessKeyCostLimitWindowTime'

const COMPACT = '@media (max-width: 560px)'
const NARROW = '@media (max-width: 860px)'

const styles = stylex.create({
  editor: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-4)',
  },
  section: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-3)',
  },
  // `.cost-limit-section + .cost-limit-section` — StyleX has no sibling
  // selectors, so the divider rides on the second section.
  sectionSibling: {
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--color-border-subtle)',
    paddingTop: 'var(--space-4)',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: { default: 'center', [COMPACT]: 'flex-start' },
    justifyContent: 'space-between',
    gap: 'var(--space-3)',
  },
  sectionIntro: {
    minWidth: 0,
  },
  sectionTitle: {
    margin: 0,
    color: 'var(--color-text)',
    fontSize: 'var(--text-body-sm)',
    fontWeight: 700,
  },
  sectionDescription: {
    margin: 0,
    marginTop: 'var(--space-1)',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
    lineHeight: 1.45,
  },
  sectionToggle: {
    display: 'flex',
    alignItems: 'center',
    flex: '0 0 auto',
  },
  sectionContent: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-2)',
  },
  ruleList: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-2)',
  },
  rule: {
    display: 'grid',
    minWidth: 0,
    gap: 'var(--space-2)',
  },
  ruleRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) 56px',
    minWidth: 0,
    alignItems: 'center',
    gap: 'var(--space-2)',
  },
  ruleActions: {
    display: 'grid',
    width: '56px',
    gridAutoFlow: 'column',
    gridAutoColumns: '28px',
    alignItems: 'center',
  },
  // `.cost-limit-rule__remove/__add` — ghost icon tint. `xstyle` arrays reject
  // `false` entries, and StyleX pseudos can't express `:hover:not(:disabled)`,
  // so the enabled/disabled variants are two whole style objects.
  ruleActionTint: {
    color: 'var(--color-text-faint)',
  },
  ruleRemoveTint: {
    color: {
      default: 'var(--color-text-faint)',
      ':hover': 'var(--color-danger)',
    },
  },
  ruleAddTint: {
    color: {
      default: 'var(--color-text-faint)',
      ':hover': 'var(--color-action)',
    },
  },
  fieldsHeader: {
    display: 'grid',
    minWidth: 0,
    alignItems: 'end',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
  },
  fieldsHeaderTotal: {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  fieldsHeaderPeriodic: {
    gridTemplateColumns: {
      default: 'minmax(0, 1fr) 76px 96px 64px',
      [COMPACT]: 'minmax(0, 1fr) 58px 76px 64px',
    },
  },
  inputGroup: {
    display: 'grid',
    width: '100%',
    minWidth: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border-control)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-surface)',
  },
  inputGroupTotal: {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  inputGroupPeriodic: {
    gridTemplateColumns: {
      default: 'minmax(0, 1fr) 76px 96px',
      [COMPACT]: 'minmax(0, 1fr) 58px 76px',
    },
  },
  // JS-driven `:focus-within` equivalent — the group frame owns the focus ring
  // while embedded controls stay borderless (same idiom as ModelPriceMatrix).
  inputGroupFocused: {
    borderColor: 'var(--color-focus)',
    boxShadow: 'var(--focus-ring)',
  },
  embeddedCell: {
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
    height: { default: 'var(--control-xs)', [NARROW]: 'var(--touch-target)' },
  },
  // Classic: `:deep(.app-text-input) { padding-left: var(--space-2) }` — the
  // selector trigger keeps its own padding, so this rides on text inputs only.
  embeddedTextInput: {
    paddingInlineStart: 'var(--space-2)',
  },
  embeddedDivider: {
    borderInlineStartWidth: 1,
    borderInlineStartStyle: 'solid',
    borderInlineStartColor: 'var(--color-border-subtle)',
  },
  embeddedSelector: {
    alignSelf: 'stretch',
    minHeight: { default: 'var(--control-xs)', [NARROW]: 'var(--touch-target)' },
    fontSize: 'var(--text-meta)',
  },
  runtime: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto minmax(54px, auto)',
    minHeight: '18px',
    alignItems: 'center',
    gap: 'var(--space-2)',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-label-xs)',
  },
  runtimeValue: {
    color: 'var(--color-text-muted)',
    fontFamily: 'var(--font-mono)',
    fontSize: 'var(--text-label-xs)',
    fontVariantNumeric: 'tabular-nums',
    fontWeight: 650,
    whiteSpace: 'nowrap',
  },
  // `.cost-limit-rule__runtime > :last-child` — applied to whichever element
  // closes the row (the runtime value when no tail cell renders).
  runtimeTail: {
    minWidth: 0,
    overflow: 'hidden',
    textAlign: 'right',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
})

const quotaStyles = stylex.create({
  quota: {
    position: 'relative',
    display: 'block',
    width: '100%',
    minWidth: 0,
    height: '8px',
    overflow: 'hidden',
    borderRadius: '999px',
    backgroundColor: 'light-dark(#e9edf1, #29313a)',
  },
  quotaCompact: {
    height: '6px',
  },
  quotaSuccess: {
    backgroundColor: 'light-dark(#dff6e6, #1b3c29)',
  },
  quotaWarning: {
    backgroundColor: 'light-dark(#fff4cc, #3b310f)',
  },
  quotaDanger: {
    backgroundColor: 'light-dark(#ffe5e8, #421d25)',
  },
  quotaUnknown: {
    backgroundImage:
      'repeating-linear-gradient(135deg, var(--color-border-subtle), var(--color-border-subtle) 6px, var(--color-surface-sunken) 6px, var(--color-surface-sunken) 12px)',
  },
  quotaFill: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 'auto',
    borderRadius: 'inherit',
    backgroundColor: '#42be65',
  },
  quotaFillWarning: {
    backgroundColor: '#f1c21b',
  },
  quotaFillDanger: {
    backgroundColor: '#fa4d56',
  },
})

/** Port of classic `QuotaProgressBar` — fixed-tone strip with ARIA progress semantics. */
function QuotaBar({
  value,
  tone = 'success',
  label,
  valueText,
  compact = false,
}: {
  value?: number
  tone?: QuotaProgressTone
  label: string
  valueText: string
  compact?: boolean
}) {
  const normalized =
    value === undefined || !Number.isFinite(value)
      ? undefined
      : Math.max(0, Math.min(100, value))
  const toneStyle =
    tone === 'warning'
      ? quotaStyles.quotaWarning
      : tone === 'danger'
        ? quotaStyles.quotaDanger
        : quotaStyles.quotaSuccess
  const fillToneStyle =
    tone === 'warning'
      ? quotaStyles.quotaFillWarning
      : tone === 'danger'
        ? quotaStyles.quotaFillDanger
        : undefined

  if (normalized === undefined) {
    return (
      <span
        {...stylex.props(quotaStyles.quota, quotaStyles.quotaUnknown, compact && quotaStyles.quotaCompact)}
        role="img"
        aria-label={`${label}: ${valueText}`}
      />
    )
  }
  return (
    <span
      {...stylex.props(quotaStyles.quota, toneStyle, compact && quotaStyles.quotaCompact)}
      role="progressbar"
      aria-label={label}
      aria-valuenow={normalized}
      aria-valuetext={valueText}
      aria-valuemin={0}
      aria-valuemax={100}
    >
      <span
        {...stylex.props(quotaStyles.quotaFill, fillToneStyle)}
        style={{ width: `${normalized}%` }}
      />
    </span>
  )
}

/** Bordered multi-control box that owns the focus ring for its cells. */
function InputGroup({
  label,
  periodic,
  children,
}: {
  label: string
  periodic: boolean
  children: ReactNode
}) {
  const [focused, setFocused] = useState(false)
  return (
    <div
      {...stylex.props(
        styles.inputGroup,
        periodic ? styles.inputGroupPeriodic : styles.inputGroupTotal,
        focused && styles.inputGroupFocused,
      )}
      role="group"
      aria-label={label}
      onFocusCapture={() => setFocused(true)}
      onBlurCapture={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget as Node | null)) {
          setFocused(false)
        }
      }}
    >
      {children}
    </div>
  )
}

type PeriodUnit = 'seconds' | 'minutes' | 'hours' | 'days'

const periodUnits: ReadonlyArray<{ value: PeriodUnit; seconds: number }> = [
  { value: 'seconds', seconds: 1 },
  { value: 'minutes', seconds: 60 },
  { value: 'hours', seconds: 3_600 },
  { value: 'days', seconds: 86_400 },
]

function periodUnit(seconds: number | undefined): PeriodUnit {
  const value = seconds ?? 0
  for (const unit of [...periodUnits].reverse()) {
    if (value > 0 && value % unit.seconds === 0) return unit.value
  }
  return 'seconds'
}

function unitSeconds(unit: PeriodUnit): number {
  return periodUnits.find((candidate) => candidate.value === unit)?.seconds ?? 1
}

function periodValue(seconds: number | undefined): number {
  const unit = periodUnit(seconds)
  return Math.max(1, Math.floor((seconds ?? 0) / unitSeconds(unit)))
}

function remainingPercent(runtime: AccessKeyCostLimitRuleStatusDto): number {
  if (runtime.status === 'inactive') return 100
  const limit = Number(runtime.limit_usd)
  const remaining = Number(runtime.remaining_usd)
  if (!Number.isFinite(limit) || !Number.isFinite(remaining) || limit <= 0) return 0
  return Math.round(Math.max(0, Math.min(100, (remaining / limit) * 100)))
}

/** Runtime row: remaining-quota bar + percent text + trailing status cell. */
function RuleRuntime({
  runtime,
  label,
  tail,
}: {
  runtime: AccessKeyCostLimitRuleStatusDto
  label: string
  tail?: ReactNode
}) {
  const t = useT()
  const intl = useIntl()
  const percent = remainingPercent(runtime)
  const valueText = t('accessKeys.costLimits.remainingPercent', {
    value: intl.formatNumber(percent),
  })
  return (
    <div {...stylex.props(styles.runtime)}>
      <QuotaBar
        value={percent}
        tone={quotaProgressTone(percent, runtime.status === 'exhausted')}
        label={label}
        valueText={valueText}
        compact
      />
      <strong {...stylex.props(styles.runtimeValue, tail === undefined && styles.runtimeTail)}>
        {valueText}
      </strong>
      {tail !== undefined && <span {...stylex.props(styles.runtimeTail)}>{tail}</span>}
    </div>
  )
}

/**
 * Port of classic `AccessKeyCostLimitEditor.vue` — `modelValue` maps to
 * `value`/`onChange`. The enable switches materialize as "add one rule when
 * enabling an empty section, drop all rules of the kind when disabling".
 */
export function AccessKeyCostLimitEditor({
  value,
  runtimeStatus,
  disabled,
  onChange,
}: {
  value: AccessKeyCostLimitRuleDraft[]
  runtimeStatus: AccessKeyCostLimitStatusDto | null
  disabled: boolean
  onChange: (value: AccessKeyCostLimitRuleDraft[]) => void
}) {
  const t = useT()

  const totalRules = value.filter((rule) => rule.kind === 'total')
  const periodicRules = value.filter((rule) => rule.kind === 'periodic')
  const totalCount = totalRules.length
  const periodicCount = periodicRules.length
  const runtimeByID = new Map((runtimeStatus?.rules ?? []).map((rule) => [rule.id, rule]))
  const runtimeFor = (rule: AccessKeyCostLimitRuleDraft) =>
    rule.id === undefined ? undefined : runtimeByID.get(rule.id)

  const periodUnitOptions = periodUnits.map((unit) => ({
    value: unit.value,
    label: t(`accessKeys.drawer.costLimits.units.${unit.value}` as MessageId),
  }))

  const updateRule = (
    clientKey: string,
    patch: Partial<AccessKeyCostLimitRuleDraft>,
  ): void => {
    onChange(value.map((rule) => (rule.clientKey === clientKey ? { ...rule, ...patch } : rule)))
  }

  const removeRule = (clientKey: string): void => {
    onChange(value.filter((rule) => rule.clientKey !== clientKey))
  }

  const removeRules = (kind: 'total' | 'periodic'): void => {
    onChange(value.filter((rule) => rule.kind !== kind))
  }

  const addRule = (kind: 'total' | 'periodic'): void => {
    if (disabled || (kind === 'total' ? totalCount >= 1 : periodicCount >= 10)) return
    onChange([
      ...value,
      {
        clientKey: createUUID(),
        kind,
        limit_usd: kind === 'total' ? '100' : '20',
        ...(kind === 'periodic' ? { period_seconds: 18_000 } : {}),
      },
    ])
  }

  // `totalEnabled`/`periodicEnabled` computed setters in classic.
  const setKindEnabled = (kind: 'total' | 'periodic', enabled: boolean): void => {
    if (disabled) return
    if (enabled) {
      if ((kind === 'total' ? totalCount : periodicCount) === 0) addRule(kind)
      return
    }
    removeRules(kind)
  }

  const updatePeriodValue = (rule: AccessKeyCostLimitRuleDraft, raw: string): void => {
    const parsed = Number(raw)
    updateRule(rule.clientKey, {
      period_seconds: Number.isFinite(parsed)
        ? parsed * unitSeconds(periodUnit(rule.period_seconds))
        : 0,
    })
  }

  const updatePeriodUnit = (rule: AccessKeyCostLimitRuleDraft, unit: PeriodUnit): void => {
    updateRule(rule.clientKey, {
      period_seconds: periodValue(rule.period_seconds) * unitSeconds(unit),
    })
  }

  const amountLabel = t('accessKeys.drawer.costLimits.amount')
  const periodLabel = t('accessKeys.drawer.costLimits.period')
  const unitLabel = t('accessKeys.drawer.costLimits.unit')
  const totalLabel = t('accessKeys.drawer.costLimits.total')
  const periodicLabel = t('accessKeys.drawer.costLimits.periodic')

  return (
    <div {...stylex.props(styles.editor)}>
      <section {...stylex.props(styles.section)}>
        <header {...stylex.props(styles.sectionHeader)}>
          <div {...stylex.props(styles.sectionIntro)}>
            <h3 {...stylex.props(styles.sectionTitle)}>{totalLabel}</h3>
            <p {...stylex.props(styles.sectionDescription)}>
              {t('accessKeys.drawer.costLimits.totalDescription')}
            </p>
          </div>
          <div {...stylex.props(styles.sectionToggle)}>
            <Switch
              value={totalCount > 0}
              isDisabled={disabled}
              label={t('accessKeys.drawer.costLimits.enableTotal')}
              isLabelHidden
              size="sm"
              onChange={(enabled) => setKindEnabled('total', enabled)}
            />
          </div>
        </header>

        {totalCount > 0 && (
          <div {...stylex.props(styles.sectionContent)}>
            <div {...stylex.props(styles.fieldsHeader, styles.fieldsHeaderTotal)}>
              <span>{amountLabel}</span>
            </div>
            {totalRules.map((rule) => {
              const runtime = runtimeFor(rule)
              return (
                <article key={rule.clientKey} {...stylex.props(styles.rule)}>
                  <InputGroup label={totalLabel} periodic={false}>
                    <TextInput
                      id={`cost-limit-amount-${rule.clientKey}`}
                      label={amountLabel}
                      isLabelHidden
                      size="sm"
                      value={rule.limit_usd}
                      isDisabled={disabled}
                      startIcon={<span aria-hidden="true">$</span>}
                      xstyle={[styles.embeddedCell, styles.embeddedTextInput]}
                      data-gptload-mono
                      {...decimalInputAttrs}
                      onChange={(next) => updateRule(rule.clientKey, { limit_usd: next })}
                    />
                  </InputGroup>
                  {runtime !== undefined && (
                    <RuleRuntime
                      runtime={runtime}
                      label={totalLabel}
                      tail={
                        runtime.status === 'exhausted'
                          ? t('accessKeys.costLimits.notAutomatic')
                          : undefined
                      }
                    />
                  )}
                </article>
              )
            })}
          </div>
        )}
      </section>

      <section {...stylex.props(styles.section, styles.sectionSibling)}>
        <header {...stylex.props(styles.sectionHeader)}>
          <div {...stylex.props(styles.sectionIntro)}>
            <h3 {...stylex.props(styles.sectionTitle)}>{periodicLabel}</h3>
            <p {...stylex.props(styles.sectionDescription)}>
              {t('accessKeys.drawer.costLimits.periodicDescription')}
            </p>
          </div>
          <div {...stylex.props(styles.sectionToggle)}>
            <Switch
              value={periodicCount > 0}
              isDisabled={disabled}
              label={t('accessKeys.drawer.costLimits.enablePeriodic')}
              isLabelHidden
              size="sm"
              onChange={(enabled) => setKindEnabled('periodic', enabled)}
            />
          </div>
        </header>

        {periodicCount > 0 && (
          <div {...stylex.props(styles.sectionContent)}>
            <div {...stylex.props(styles.fieldsHeader, styles.fieldsHeaderPeriodic)}>
              <span>{amountLabel}</span>
              <span>{periodLabel}</span>
              <span>{unitLabel}</span>
              <span aria-hidden="true" />
            </div>
            <div {...stylex.props(styles.ruleList)}>
              {periodicRules.map((rule, index) => {
                const runtime = runtimeFor(rule)
                return (
                  <article key={rule.clientKey} {...stylex.props(styles.rule)}>
                    <div {...stylex.props(styles.ruleRow)}>
                      <InputGroup label={periodicLabel} periodic>
                        <TextInput
                          id={`cost-limit-amount-${rule.clientKey}`}
                          label={amountLabel}
                          isLabelHidden
                          size="sm"
                          value={rule.limit_usd}
                          isDisabled={disabled}
                          startIcon={<span aria-hidden="true">$</span>}
                          xstyle={[styles.embeddedCell, styles.embeddedTextInput]}
                          data-gptload-mono
                          {...decimalInputAttrs}
                          onChange={(next) => updateRule(rule.clientKey, { limit_usd: next })}
                        />
                        <TextInput
                          id={`cost-limit-period-${rule.clientKey}`}
                          label={periodLabel}
                          isLabelHidden
                          size="sm"
                          value={String(periodValue(rule.period_seconds))}
                          isDisabled={disabled}
                          xstyle={[
                            styles.embeddedCell,
                            styles.embeddedTextInput,
                            styles.embeddedDivider,
                          ]}
                          data-gptload-mono
                          {...numericInputAttrs}
                          onChange={(raw) => updatePeriodValue(rule, raw)}
                        />
                        <Selector
                          label={unitLabel}
                          isLabelHidden
                          variant="ghost"
                          size="sm"
                          width="100%"
                          options={periodUnitOptions}
                          value={periodUnit(rule.period_seconds)}
                          isDisabled={disabled}
                          xstyle={[
                            styles.embeddedCell,
                            styles.embeddedDivider,
                            styles.embeddedSelector,
                          ]}
                          onChange={(unit) => {
                            const periodUnitValue = periodUnits.find(
                              (candidate) => candidate.value === unit,
                            )
                            if (periodUnitValue) updatePeriodUnit(rule, periodUnitValue.value)
                          }}
                        />
                      </InputGroup>
                      <div {...stylex.props(styles.ruleActions)}>
                        {index > 0 ? (
                          <IconButton
                            variant="ghost"
                            size="sm"
                            label={t('accessKeys.drawer.costLimits.remove')}
                            icon={<X size={14} aria-hidden="true" />}
                            isDisabled={disabled}
                            xstyle={disabled ? styles.ruleActionTint : styles.ruleRemoveTint}
                            onClick={() => removeRule(rule.clientKey)}
                          />
                        ) : (
                          <span aria-hidden="true" />
                        )}
                        {index === periodicRules.length - 1 ? (
                          <IconButton
                            variant="ghost"
                            size="sm"
                            label={t('accessKeys.drawer.costLimits.addPeriodic')}
                            icon={<Plus size={14} aria-hidden="true" />}
                            isDisabled={disabled || periodicCount >= 10}
                            xstyle={
                              disabled || periodicCount >= 10
                                ? styles.ruleActionTint
                                : styles.ruleAddTint
                            }
                            onClick={() => addRule('periodic')}
                          />
                        ) : (
                          <span aria-hidden="true" />
                        )}
                      </div>
                    </div>
                    {runtime !== undefined && (
                      <RuleRuntime
                        runtime={runtime}
                        label={periodicLabel}
                        tail={
                          <AccessKeyCostLimitWindowTime
                            rule={runtime}
                          />
                        }
                      />
                    )}
                  </article>
                )
              })}
            </div>
          </div>
        )}
      </section>
    </div>
  )
}
