// web/src/frontends/classic/features/access-keys/AccessKeyDeleteDialog.vue
<script setup lang="ts">
import { Trash2 } from '@lucide/vue'
import { computed, nextTick, onBeforeUnmount, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import { useApiClient } from '@/app/api-client-context'
import { deleteAccessKey } from '@/app/resources/access-keys'
import type { AccessKeyDto } from '@/api/control/types'
import { RequestCancelledError } from '@shared/http/errors'
import AppButton from '@/components/ui/AppButton.vue'
import AppConfirmDialog from '@/components/ui/AppConfirmDialog.vue'
import AppTypedConfirmation from '@/components/ui/AppTypedConfirmation.vue'
import InlineFeedback from '@/components/ui/InlineFeedback.vue'

const props = withDefaults(
  defineProps<{ accessKey: AccessKeyDto; total: number; disabled?: boolean }>(),
  { disabled: false },
)
const emit = defineEmits<{ deleted: [name: string] }>()
const client = useApiClient()
const { t } = useI18n()
const open = ref(false)
const typedName = ref('')
const nameInput = ref<InstanceType<typeof AppTypedConfirmation>>()
const pending = ref(false)
const failed = ref(false)
let controller: AbortController | undefined

const confirmed = computed(() => typedName.value === props.accessKey.name)

async function focusNameInput(): Promise<void> {
  await nextTick()
  await nextTick()
  nameInput.value?.focus()
}

function setOpen(value: boolean): void {
  if (!value && pending.value) return
  if (!value) {
    controller?.abort()
    controller = undefined
    failed.value = false
    typedName.value = ''
  }
  open.value = value
  if (value) void focusNameInput()
}

function openDialog(): void {
  if (props.disabled) return
  setOpen(true)
}

async function confirmDelete(): Promise<void> {
  if (!confirmed.value || pending.value) return
  pending.value = true
  failed.value = false
  controller = new AbortController()
  const activeController = controller
  try {
    await deleteAccessKey(client, props.accessKey.id, activeController.signal)
    open.value = false
    typedName.value = ''
    emit('deleted', props.accessKey.name)
  } catch (error: unknown) {
    if (!(error instanceof RequestCancelledError)) failed.value = true
  } finally {
    if (controller === activeController) controller = undefined
    pending.value = false
  }
}

onBeforeUnmount(() => controller?.abort())
</script>

<template>
  <AppConfirmDialog
    :open="open"
    :title="t('accessKeys.delete.title')"
    :description="t('accessKeys.delete.description', { name: accessKey.name })"
    :close-label="t('accessKeys.delete.close')"
    :cancel-label="t('common.cancel')"
    :confirm-label="t('accessKeys.delete.confirm')"
    tone="danger"
    :pending="pending"
    :confirm-disabled="!confirmed"
    @update:open="setOpen"
    @confirm="confirmDelete"
  >
    <template #trigger>
      <slot name="trigger" :open="openDialog">
        <AppButton variant="danger" size="compact" :disabled="disabled" @click="openDialog">
          <Trash2 :size="16" aria-hidden="true" />
          {{ t('accessKeys.delete.open') }}
        </AppButton>
      </slot>
    </template>

    <div class="access-key-delete__body">
      <div class="access-key-delete__summary">
        <strong>{{ accessKey.name }}</strong>
        <code>{{ accessKey.masked_key }}</code>
      </div>
      <InlineFeedback v-if="total === 1" tone="warning" appearance="hint">
        {{ t('accessKeys.delete.lastWarning') }}
      </InlineFeedback>
      <InlineFeedback tone="warning" appearance="hint">
        {{ t('accessKeys.delete.impact') }}
      </InlineFeedback>
      <AppTypedConfirmation
        id="access-key-delete-name"
        ref="nameInput"
        v-model="typedName"
        :label="t('accessKeys.delete.typeName', { name: accessKey.name })"
        :disabled="pending"
      />
      <InlineFeedback v-if="failed" tone="danger">{{
        t('accessKeys.delete.failed')
      }}</InlineFeedback>
    </div>
  </AppConfirmDialog>
</template>

<style scoped>
.access-key-delete__body {
  display: grid;
  gap: 12px;
}
.access-key-delete__summary {
  display: flex;
  min-width: 0;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-3);
  border: 1px solid var(--color-border-subtle);
  border-radius: var(--radius-control);
  background: var(--color-surface-sunken);
  padding: 9px 10px;
}
.access-key-delete__summary strong {
  font-size: var(--text-sm);
}
.access-key-delete__summary code {
  min-width: 0;
  color: var(--color-code);
  font-size: var(--text-label-xs);
  overflow-wrap: anywhere;
}
</style>

// web/src/frontends/astryx/features/access-keys/AccessKeyDeleteDialog.tsx
import * as stylex from '@stylexjs/stylex'
import {
  Banner,
  Button,
  Dialog,
  DialogHeader,
  Layout,
  LayoutContent,
  LayoutFooter,
  TextInput,
} from '@astryxdesign/core'
import { useEffect, useRef, useState } from 'react'

import { deleteAccessKey } from '@shared/control/resources/access-keys'
import type { AccessKeyDto } from '@shared/control/types'
import { RequestCancelledError } from '@shared/http/errors'

import { useT } from '../../app/i18n'
import { useAppServices } from '../../app/services'
import { plainTextInputAttrs } from '../../components/input-attrs'

const styles = stylex.create({
  body: {
    display: 'grid',
    gap: 'var(--space-3)',
  },
  summary: {
    display: 'flex',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 'var(--space-3)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border-subtle)',
    borderRadius: 'var(--radius-control)',
    backgroundColor: 'var(--color-surface-sunken)',
    paddingBlock: 9,
    paddingInline: 10,
  },
  summaryName: {
    fontSize: 'var(--text-sm)',
  },
  summaryKey: {
    minWidth: 0,
    color: 'var(--color-code)',
    fontSize: 'var(--text-label-xs)',
    overflowWrap: 'anywhere',
  },
})

/**
 * Typed-confirmation delete — the Astryx counterpart of classic
 * AccessKeyDeleteDialog. `open` is controlled by the caller (the classic
 * trigger slot inverts to a plain button in the row actions).
 */
export function AccessKeyDeleteDialog({
  accessKey,
  total,
  open,
  onOpenChange,
  onDeleted,
}: {
  accessKey: AccessKeyDto
  total: number
  open: boolean
  onOpenChange(open: boolean): void
  onDeleted(name: string): void
}) {
  const t = useT()
  const { apiClient } = useAppServices()
  const [typedName, setTypedName] = useState('')
  const [pending, setPending] = useState(false)
  const [failed, setFailed] = useState(false)
  const controllerRef = useRef<AbortController | null>(null)
  const nameInputRef = useRef<HTMLInputElement | null>(null)

  const confirmed = typedName === accessKey.name

  const setDialogOpen = (value: boolean) => {
    if (!value && pending) return
    if (!value) {
      controllerRef.current?.abort()
      controllerRef.current = null
      setFailed(false)
      setTypedName('')
    }
    onOpenChange(value)
  }

  // Classic awaits two nextTicks before focusing the confirmation input — the
  // rAF lands after the <dialog> mounts and its own focus-on-open settles.
  useEffect(() => {
    if (!open) return
    const frame = requestAnimationFrame(() => nameInputRef.current?.focus())
    return () => cancelAnimationFrame(frame)
  }, [open])

  useEffect(
    () => () => {
      controllerRef.current?.abort()
    },
    [],
  )

  const confirmDelete = async () => {
    if (!confirmed || pending) return
    setPending(true)
    setFailed(false)
    const controller = new AbortController()
    controllerRef.current = controller
    try {
      await deleteAccessKey(apiClient, accessKey.id, controller.signal)
      onOpenChange(false)
      setTypedName('')
      onDeleted(accessKey.name)
    } catch (error: unknown) {
      if (!(error instanceof RequestCancelledError)) setFailed(true)
    } finally {
      if (controllerRef.current === controller) controllerRef.current = null
      setPending(false)
    }
  }

  return (
    <Dialog isOpen={open} onOpenChange={setDialogOpen} width={440}>
      <Layout
        header={
          <DialogHeader
            title={t('accessKeys.delete.title')}
            subtitle={t('accessKeys.delete.description', { name: accessKey.name })}
            onOpenChange={setDialogOpen}
            hasDivider
          />
        }
        content={
          <LayoutContent isScrollable>
            <div {...stylex.props(styles.body)}>
              <div {...stylex.props(styles.summary)}>
                <strong {...stylex.props(styles.summaryName)}>{accessKey.name}</strong>
                <code {...stylex.props(styles.summaryKey)}>{accessKey.masked_key}</code>
              </div>
              {total === 1 && (
                <Banner status="warning" title={t('accessKeys.delete.lastWarning')} />
              )}
              <Banner status="warning" title={t('accessKeys.delete.impact')} />
              <TextInput
                ref={nameInputRef}
                label={t('accessKeys.delete.typeName', { name: accessKey.name })}
                value={typedName}
                onChange={setTypedName}
                isDisabled={pending}
                autoComplete="off"
                {...plainTextInputAttrs}
              />
              {failed && <Banner status="error" title={t('accessKeys.delete.failed')} />}
            </div>
          </LayoutContent>
        }
        footer={
          <LayoutFooter hasDivider>
            <Button
              variant="secondary"
              label={t('common.cancel')}
              isDisabled={pending}
              onClick={() => setDialogOpen(false)}
            />
            <Button
              variant="destructive"
              label={t('accessKeys.delete.confirm')}
              isDisabled={!confirmed}
              isLoading={pending}
              onClick={() => void confirmDelete()}
            />
          </LayoutFooter>
        }
      />
    </Dialog>
  )
}
