// web/src/frontends/astryx/features/import/ImportConnectionSection.tsx
import * as stylex from '@stylexjs/stylex'
import { Field, Selector, Switch, TextInput } from '@astryxdesign/core'

import type { ChannelDto } from '@shared/control/resources/channels'
import { proxyMutation } from '@shared/control/resources/proxy'
import type { ProxyConfiguredMode } from '@shared/control/types'
import { isValidPriceMultiplier } from '@shared/lib/price-multiplier'
import {
  hasUpstreamBaseURLVersionMismatch,
  isValidUpstreamBaseURL,
} from '@shared/lib/upstream-base-url'
import type { ImportProxyDraft } from '@shared/domain/import/model-draft'

import { useT } from '../../app/i18n'
import { plainTextInputAttrs } from '../../components/input-attrs'

const styles = stylex.create({
  root: {
    minWidth: 0,
    marginTop: '12px',
  },
  fields: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(180px, 260px) minmax(0, 1fr)',
      '@media (max-width: 860px)': 'minmax(0, 1fr)',
    },
    alignItems: 'start',
    gap: '10px 14px',
  },
  params: {
    display: 'grid',
    gridColumn: '1 / -1',
    gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 280px), 1fr))',
    gap: '10px 14px',
  },
  fullWidth: {
    gridColumn: { default: '1 / -1', '@media (max-width: 860px)': 'auto' },
    minWidth: 0,
  },
  minWidth: {
    minWidth: 0,
  },
  multiplierInput: {
    maxWidth: '260px',
    fontFamily: 'var(--font-mono)',
  },
  proxyControls: {
    display: 'flex',
    minWidth: 0,
    alignItems: { default: 'center', '@media (max-width: 860px)': 'stretch' },
    flexDirection: { default: 'row', '@media (max-width: 860px)': 'column' },
    gap: 'var(--space-2)',
  },
  proxyInput: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 'auto',
    minWidth: 0,
  },
  urlInput: {
    fontFamily: 'var(--font-mono)',
  },
  switchRow: {
    display: 'flex',
    minHeight: { default: 'var(--control-xs)', '@media (max-width: 860px)': 'var(--touch-target)' },
    alignItems: 'center',
    gap: 'var(--space-3)',
  },
  urlInputWrap: {
    minWidth: 0,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 'auto',
  },
  disabledReason: {
    margin: 0,
    marginTop: '4px',
    color: 'var(--color-text-faint)',
    fontSize: 'var(--text-sm)',
  },
})

export interface ImportConnectionSectionProps {
  channel: ChannelDto | null
  name: string
  providerUrl: string
  priceMultiplier: string
  params: Record<string, string>
  proxy: ImportProxyDraft
  paramErrors: Readonly<Record<string, string>>
  baseUrlOverrideEnabled: boolean
  disabled?: boolean
  proxyDisabled?: boolean
  onNameChange(value: string): void
  onProviderUrlChange(value: string): void
  onPriceMultiplierChange(value: string): void
  onParamChange(key: string, value: string): void
  onProxyChange(value: ImportProxyDraft): void
  onBaseUrlOverrideChange(enabled: boolean): void
  onParamBlur(key: string): void
}

export function ImportConnectionSection({
  channel,
  name,
  providerUrl,
  priceMultiplier,
  params,
  proxy,
  paramErrors,
  baseUrlOverrideEnabled,
  disabled = false,
  proxyDisabled = false,
  onNameChange,
  onProviderUrlChange,
  onPriceMultiplierChange,
  onParamChange,
  onProxyChange,
  onBaseUrlOverrideChange,
  onParamBlur,
}: ImportConnectionSectionProps) {
  const t = useT()
  const proxySupported = channel?.capabilities.outbound_proxy === true
  const proxyModeOptions = [
    { value: 'inherit', label: t('common.proxy.inherit.group') },
    { value: 'direct', label: t('common.proxy.mode.direct') },
    { value: 'custom', label: t('common.proxy.mode.custom') },
  ]
  const proxyError =
    proxySupported && proxy.mode === 'custom' && proxyMutation(proxy.mode, proxy.url) === undefined
      ? t('common.proxy.invalid')
      : undefined
  const proxyDescription =
    !proxySupported || proxy.mode === 'custom' ? undefined : t(`common.proxy.help.${proxy.mode}`)
  const proxyDisabledReason = !proxySupported
    ? t('common.proxy.unsupportedHelp')
    : proxyDisabled
      ? t('import.connection.proxyLocked')
      : undefined

  function updateProxyMode(value: string): void {
    if (value !== 'inherit' && value !== 'direct' && value !== 'custom') return
    onProxyChange({ mode: value as ProxyConfiguredMode, url: '' })
  }

  function updateProxyURL(value: string): void {
    if (proxy.mode !== 'custom') return
    onProxyChange({ mode: 'custom', url: value })
  }

  function fieldError(key: string): string {
    return paramErrors[key] ?? ''
  }

  function isOptionalBaseURL(key: string, required: boolean): boolean {
    return key === 'base_url' && !required
  }

  function baseURLDescription(): string {
    switch (channel?.channel_id) {
      case 'gpt_load':
        return t('import.connection.gptLoadUrlDescription')
      case 'newapi':
        return t('import.connection.newApiUrlDescription')
      case 'cliproxyapi':
        return t('import.connection.cpaUrlDescription')
      case 'sub2api':
        return t('import.connection.sub2ApiUrlDescription')
      case 'openai_compatible':
        return t('import.connection.compatibleUrlDescription')
    }
    if (!channel?.default_base_url) return t('import.connection.urlDescription')
    return t('import.connection.urlDescriptionWithDefault', {
      url: channel.default_base_url,
    })
  }

  function baseURLVersionWarning(key: string): string | undefined {
    if (key !== 'base_url' || !channel?.default_base_url) return undefined
    const value = params[key]?.trim() ?? ''
    if (!value || !isValidUpstreamBaseURL(value)) return undefined
    return hasUpstreamBaseURLVersionMismatch(channel.default_base_url, value)
      ? t('import.connection.urlVersionWarning')
      : undefined
  }

  return (
    <div {...stylex.props(styles.root)}>
      <div {...stylex.props(styles.fields)}>
        <div {...stylex.props(styles.minWidth)}>
          <Field label={t('import.connection.name')} inputID="import-group-name" isOptional>
            <TextInput
              value={name}
              isDisabled={disabled}
              autoComplete="off"
              placeholder={t('import.connection.namePlaceholder')}
              label={t('import.connection.name')}
              isLabelHidden
              onChange={onNameChange}
            />
          </Field>
        </div>

        <div {...stylex.props(styles.minWidth)}>
          <Field
            label={t('common.priceMultiplier.label')}
            description={t('common.priceMultiplier.groupHelp')}
            inputID="import-price-multiplier"
            status={
              isValidPriceMultiplier(priceMultiplier)
                ? undefined
                : { type: 'error', message: t('common.priceMultiplier.invalid') }
            }
          >
            <input
              id="import-price-multiplier"
              {...stylex.props(styles.multiplierInput)}
              value={priceMultiplier}
              inputMode="decimal"
              disabled={disabled}
              aria-invalid={!isValidPriceMultiplier(priceMultiplier) || undefined}
              onChange={(event) => onPriceMultiplierChange(event.target.value)}
            />
          </Field>
        </div>

        {channel !== null && channel.param_fields.length > 0 && (
          <div {...stylex.props(styles.params)}>
            {channel.param_fields.map((param) =>
              isOptionalBaseURL(param.key, param.required) ? (
                <div key={param.key} {...stylex.props(styles.minWidth)}>
                  <Field
                    label={t('import.connection.customUrl')}
                    description={baseURLDescription()}
                    inputID="import-channel-base-url-override"
                    isRequired={baseUrlOverrideEnabled}
                    status={
                      fieldError(param.key)
                        ? { type: 'error', message: fieldError(param.key) }
                        : baseURLVersionWarning(param.key)
                          ? { type: 'warning', message: baseURLVersionWarning(param.key) }
                          : undefined
                    }
                  >
                    <div {...stylex.props(styles.switchRow)}>
                      <Switch
                        value={baseUrlOverrideEnabled}
                        isDisabled={disabled}
                        label={t('import.connection.customUrl')}
                        isLabelHidden
                        onChange={(checked) => onBaseUrlOverrideChange(checked)}
                      />
                      {baseUrlOverrideEnabled && (
                        <div {...stylex.props(styles.urlInputWrap)}>
                          <input
                            id={`import-channel-param-${param.key}`}
                            {...stylex.props(styles.urlInput)}
                            value={params[param.key] ?? ''}
                            type="url"
                            required
                            disabled={disabled}
                            aria-label={t('import.connection.customUrl')}
                            aria-invalid={fieldError(param.key) ? true : undefined}
                            autoComplete="off"
                            autoCapitalize="none"
                            spellCheck={false}
                            placeholder="https://"
                            onChange={(event) => onParamChange(param.key, event.target.value)}
                            onBlur={() => onParamBlur(param.key)}
                          />
                        </div>
                      )}
                    </div>
                  </Field>
                </div>
              ) : (
                <div key={param.key} {...stylex.props(styles.minWidth)}>
                  <Field
                    label={param.key === 'base_url' ? t('import.connection.url') : param.label}
                    description={param.key === 'base_url' ? baseURLDescription() : undefined}
                    inputID={`import-channel-param-${param.key}`}
                    isRequired={param.required}
                    status={
                      fieldError(param.key)
                        ? { type: 'error', message: fieldError(param.key) }
                        : param.key === 'base_url' && baseURLVersionWarning(param.key)
                          ? { type: 'warning', message: baseURLVersionWarning(param.key) }
                          : undefined
                    }
                  >
                    <input
                      id={`import-channel-param-${param.key}`}
                      {...stylex.props(
                        param.input_kind === 'url' ? styles.urlInput : styles.minWidth,
                      )}
                      value={params[param.key] ?? ''}
                      type={param.input_kind === 'url' ? 'url' : 'text'}
                      disabled={disabled}
                      aria-invalid={fieldError(param.key) ? true : undefined}
                      autoComplete="off"
                      autoCapitalize="none"
                      spellCheck={false}
                      placeholder={param.input_kind === 'url' ? 'https://' : undefined}
                      onChange={(event) => onParamChange(param.key, event.target.value)}
                      onBlur={() => onParamBlur(param.key)}
                    />
                  </Field>
                </div>
              ),
            )}
          </div>
        )}

        <div {...stylex.props(styles.fullWidth)}>
          <Field
            label={t('group.settings.base.providerUrl')}
            isOptional
            description={t('group.settings.base.providerUrlHelp')}
            inputID="import-provider-url"
          >
            <input
              id="import-provider-url"
              {...stylex.props(styles.urlInput)}
              value={providerUrl}
              type="url"
              disabled={disabled}
              autoComplete="off"
              autoCapitalize="none"
              spellCheck={false}
              placeholder="https://"
              onChange={(event) => onProviderUrlChange(event.target.value)}
            />
          </Field>
        </div>

        {channel && (
          <div {...stylex.props(styles.fullWidth)}>
            <Field
              label={t('common.proxy.title')}
              description={proxyDescription}
              inputID="import-group-proxy-mode"
              status={proxyError ? { type: 'error', message: proxyError } : undefined}
            >
              <div>
                <div {...stylex.props(styles.proxyControls)}>
                  <Selector
                    label={t('common.proxy.modeLabel')}
                    isLabelHidden
                    options={proxyModeOptions}
                    size="sm"
                    value={proxySupported ? proxy.mode : 'inherit'}
                    isDisabled={disabled || proxyDisabled || !proxySupported}
                    onChange={updateProxyMode}
                  />
                  {proxySupported && proxy.mode === 'custom' && (
                    <TextInput
                      xstyle={styles.proxyInput}
                      data-gptload-mono
                      value={proxy.url}
                      label={t('common.proxy.urlLabel')}
                      isLabelHidden
                      placeholder={t('common.proxy.placeholder')}
                      size="sm"
                      autoComplete="off"
                      {...plainTextInputAttrs}
                      isDisabled={disabled || proxyDisabled}
                      status={proxyError ? { type: 'error', message: proxyError } : undefined}
                      statusVariant="tooltip"
                      onChange={updateProxyURL}
                    />
                  )}
                </div>
                {proxyDisabledReason !== undefined && (
                  <p {...stylex.props(styles.disabledReason)}>{proxyDisabledReason}</p>
                )}
              </div>
            </Field>
          </div>
        )}
      </div>
    </div>
  )
}

// web/src/features/import/ImportConnectionSection.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import type { ProxyConfiguredMode } from '@/api/control/types'
import type { ChannelDto } from '@/app/resources/channels'
import { proxyMutation } from '@/app/resources/proxy'
import AppSelect from '@/components/ui/AppSelect.vue'
import AppSwitch from '@/components/ui/AppSwitch.vue'
import AppTextInput from '@/components/ui/AppTextInput.vue'
import FormField from '@/components/ui/FormField.vue'
import { isValidPriceMultiplier } from '@/lib/price-multiplier'
import { hasUpstreamBaseURLVersionMismatch, isValidUpstreamBaseURL } from '@/lib/upstream-base-url'

import type { ImportProxyDraft } from './model-draft'

const props = defineProps<{
  channel: ChannelDto | null
  name: string
  priceMultiplier: string
  params: Record<string, string>
  proxy: ImportProxyDraft
  paramErrors: Readonly<Record<string, string>>
  baseUrlOverrideEnabled: boolean
  disabled?: boolean
  proxyDisabled?: boolean
}>()
const emit = defineEmits<{
  'update:name': [value: string]
  'update:priceMultiplier': [value: string]
  'update:param': [key: string, value: string]
  'update:proxy': [value: ImportProxyDraft]
  'update:base-url-override': [enabled: boolean]
  'blur:param': [key: string]
}>()
const { t } = useI18n()
const proxySupported = computed(() => props.channel?.capabilities.outbound_proxy === true)
const proxyModeOptions = computed(() => [
  { value: 'inherit', label: t('common.proxy.inherit.group') },
  { value: 'direct', label: t('common.proxy.mode.direct') },
  { value: 'custom', label: t('common.proxy.mode.custom') },
])
const proxyError = computed(() =>
  proxySupported.value &&
  props.proxy.mode === 'custom' &&
  proxyMutation(props.proxy.mode, props.proxy.url) === undefined
    ? t('common.proxy.invalid')
    : undefined,
)
const proxyDescription = computed(() => {
  if (!proxySupported.value || props.proxy.mode === 'custom') return undefined
  return t(`common.proxy.help.${props.proxy.mode}`)
})

function updateProxyMode(value: string): void {
  if (!['inherit', 'direct', 'custom'].includes(value)) return
  emit('update:proxy', { mode: value as ProxyConfiguredMode, url: '' })
}

function updateProxyURL(value: string): void {
  if (props.proxy.mode !== 'custom') return
  emit('update:proxy', { mode: 'custom', url: value })
}

function fieldError(key: string): string {
  return props.paramErrors[key] ?? ''
}

function isOptionalBaseURL(key: string, required: boolean): boolean {
  return key === 'base_url' && !required
}

function baseURLDescription(): string {
  if (props.channel?.channel_id === 'gpt_load') {
    return t('import.connection.gptLoadUrlDescription')
  }
  if (props.channel?.channel_id === 'newapi') {
    return t('import.connection.newApiUrlDescription')
  }
  if (props.channel?.channel_id === 'cliproxyapi') {
    return t('import.connection.cpaUrlDescription')
  }
  if (props.channel?.channel_id === 'sub2api') {
    return t('import.connection.sub2ApiUrlDescription')
  }
  if (props.channel?.channel_id === 'openai_compatible') {
    return t('import.connection.compatibleUrlDescription')
  }
  if (!props.channel?.default_base_url) return t('import.connection.urlDescription')
  return t('import.connection.urlDescriptionWithDefault', {
    url: props.channel.default_base_url,
  })
}

function baseURLVersionWarning(key: string): string | undefined {
  if (key !== 'base_url' || !props.channel?.default_base_url) return undefined
  const value = props.params[key]?.trim() ?? ''
  if (!value || !isValidUpstreamBaseURL(value)) return undefined
  return hasUpstreamBaseURLVersionMismatch(props.channel.default_base_url, value)
    ? t('import.connection.urlVersionWarning')
    : undefined
}
</script>

<template>
  <div class="import-connection">
    <div class="import-connection__fields">
      <FormField
        id="import-group-name"
        class="import-connection__name"
        :label="t('import.connection.name')"
        :label-suffix="t('import.optional')"
        size="compact"
      >
        <template #default="field">
          <input
            id="import-group-name"
            :value="name"
            :disabled="disabled"
            :aria-describedby="field.describedBy"
            autocomplete="off"
            :placeholder="t('import.connection.namePlaceholder')"
            @input="emit('update:name', ($event.target as HTMLInputElement).value)"
          />
        </template>
      </FormField>

      <div v-if="channel?.param_fields.length" class="import-connection__params">
        <template v-for="param in channel.param_fields" :key="param.key">
          <FormField
            v-if="isOptionalBaseURL(param.key, param.required)"
            id="import-channel-base-url-override"
            class="import-connection__param import-connection__param--optional-url"
            :label="t('import.connection.customUrl')"
            :description="baseURLDescription()"
            :description-warning="baseURLVersionWarning(param.key)"
            :error="fieldError(param.key)"
            :required="baseUrlOverrideEnabled"
            :required-text="t('import.required')"
            size="compact"
          >
            <template #default="field">
              <div class="import-connection__switch-row">
                <AppSwitch
                  id="import-channel-base-url-override"
                  :model-value="baseUrlOverrideEnabled"
                  :disabled="disabled"
                  :label="t('import.connection.customUrl')"
                  @update:model-value="emit('update:base-url-override', $event)"
                />
                <div v-if="baseUrlOverrideEnabled" class="import-connection__url-input">
                  <input
                    :id="`import-channel-param-${param.key}`"
                    class="import-connection__url"
                    :value="params[param.key] ?? ''"
                    type="url"
                    required
                    :disabled="disabled"
                    :aria-label="t('import.connection.customUrl')"
                    :aria-invalid="field.invalid || undefined"
                    :aria-describedby="field.describedBy"
                    autocomplete="off"
                    autocapitalize="none"
                    spellcheck="false"
                    placeholder="https://"
                    @input="
                      emit('update:param', param.key, ($event.target as HTMLInputElement).value)
                    "
                    @blur="emit('blur:param', param.key)"
                  />
                </div>
              </div>
            </template>
          </FormField>

          <FormField
            v-else
            :id="`import-channel-param-${param.key}`"
            class="import-connection__param"
            :label="param.key === 'base_url' ? t('import.connection.url') : param.label"
            :description="param.key === 'base_url' ? baseURLDescription() : undefined"
            :description-warning="
              param.key === 'base_url' ? baseURLVersionWarning(param.key) : undefined
            "
            :error="fieldError(param.key)"
            :required="param.required"
            :required-text="t('import.required')"
            size="compact"
          >
            <template #default="field">
              <input
                :id="`import-channel-param-${param.key}`"
                :class="{ 'import-connection__url': param.input_kind === 'url' }"
                :value="params[param.key] ?? ''"
                :type="param.input_kind === 'url' ? 'url' : 'text'"
                :disabled="disabled"
                :aria-invalid="field.invalid || undefined"
                :aria-describedby="field.describedBy"
                autocomplete="off"
                autocapitalize="none"
                spellcheck="false"
                :placeholder="param.input_kind === 'url' ? 'https://' : undefined"
                @input="emit('update:param', param.key, ($event.target as HTMLInputElement).value)"
                @blur="emit('blur:param', param.key)"
              />
            </template>
          </FormField>
        </template>
      </div>

      <FormField
        id="import-price-multiplier"
        class="import-connection__multiplier"
        :label="t('common.priceMultiplier.label')"
        :description="t('common.priceMultiplier.groupHelp')"
        :error="
          isValidPriceMultiplier(priceMultiplier) ? undefined : t('common.priceMultiplier.invalid')
        "
        size="compact"
      >
        <template #default="field">
          <input
            id="import-price-multiplier"
            :value="priceMultiplier"
            inputmode="decimal"
            :disabled="disabled"
            :aria-describedby="field.describedBy"
            :aria-invalid="field.invalid || undefined"
            @input="emit('update:priceMultiplier', ($event.target as HTMLInputElement).value)"
          />
        </template>
      </FormField>

      <FormField
        v-if="channel"
        id="import-group-proxy-mode"
        class="import-connection__proxy"
        :label="t('common.proxy.title')"
        :description="proxyDescription"
        :disabled-reason="
          !proxySupported
            ? t('common.proxy.unsupportedHelp')
            : proxyDisabled
              ? t('import.connection.proxyLocked')
              : undefined
        "
        :error="proxyError"
        size="compact"
      >
        <template #default="field">
          <div class="import-connection__proxy-controls">
            <AppSelect
              id="import-group-proxy-mode"
              :model-value="proxySupported ? proxy.mode : 'inherit'"
              :label="t('common.proxy.modeLabel')"
              :options="proxyModeOptions"
              size="sm"
              :disabled="disabled || proxyDisabled || !proxySupported"
              @update:model-value="updateProxyMode"
            />
            <AppTextInput
              v-if="proxySupported && proxy.mode === 'custom'"
              id="import-group-proxy-url"
              :model-value="proxy.url"
              :label="t('common.proxy.urlLabel')"
              :placeholder="t('common.proxy.placeholder')"
              appearance="surface"
              size="sm"
              autocomplete="off"
              :spellcheck="false"
              monospace
              :disabled="disabled || proxyDisabled"
              :invalid="field.invalid"
              :described-by="field.describedBy"
              @update:model-value="updateProxyURL"
            />
          </div>
        </template>
      </FormField>
    </div>
  </div>
</template>

<style scoped>
.import-connection {
  min-width: 0;
  margin-top: 12px;
}

.import-connection__fields {
  display: grid;
  grid-template-columns: minmax(180px, 260px) minmax(0, 1fr);
  align-items: start;
  gap: 10px 14px;
}

.import-connection__name,
.import-connection__params,
.import-connection__param,
.import-connection__proxy {
  min-width: 0;
}

.import-connection__params {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(min(100%, 280px), 1fr));
  gap: 10px 14px;
}

.import-connection__multiplier {
  grid-column: 1;
}

.import-connection__proxy {
  grid-column: 2;
}

.import-connection__multiplier input {
  max-width: 260px;
  font-family: var(--font-mono);
}

.import-connection__proxy-controls {
  display: flex;
  min-width: 0;
  align-items: center;
  gap: var(--space-2);
}

.import-connection__proxy-controls :deep(.app-text-input) {
  flex: 1 1 auto;
}

.import-connection__url {
  font-family: var(--font-mono);
}

.import-connection__switch-row {
  display: flex;
  min-height: var(--control-xs);
  align-items: center;
  gap: var(--space-3);
}

.import-connection__url-input {
  min-width: 0;
  flex: 1 1 auto;
}

@media (max-width: 860px) {
  .import-connection__fields {
    grid-template-columns: minmax(0, 1fr);
  }

  .import-connection__multiplier,
  .import-connection__proxy {
    grid-column: auto;
  }

  .import-connection__switch-row {
    min-height: var(--touch-target);
  }

  .import-connection__proxy-controls {
    align-items: stretch;
    flex-direction: column;
  }
}
</style>
